// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccessTokensCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "access-tokens",
		Short:       "Get, create, update, and delete access tokens",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccessTokensCreateCmd(flags))
	cmd.AddCommand(newAccessTokensDestroyCmd(flags))
	cmd.AddCommand(newAccessTokensShowCmd(flags))
	cmd.AddCommand(newAccessTokensUpdateCmd(flags))
	cmd.AddCommand(newAccessTokensUserGeneratedTokensCmd(flags))
	return cmd
}
