// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAccountsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAccountName string
	var bodyAccountSisAccountId string
	var bodyAccountDefaultTimeZone string
	var bodyAccountDefaultStorageQuotaMb int
	var bodyAccountDefaultUserStorageQuotaMb int
	var bodyAccountDefaultGroupStorageQuotaMb int
	var bodyAccountCourseTemplateId int
	var bodyAccountParentAccountId int
	var bodyAccountSettingsRestrictStudentPastViewValue bool
	var bodyAccountSettingsRestrictStudentPastViewLocked bool
	var bodyAccountSettingsRestrictStudentFutureViewValue bool
	var bodyAccountSettingsMicrosoftSyncEnabled bool
	var bodyAccountSettingsMicrosoftSyncTenant string
	var bodyAccountSettingsMicrosoftSyncLoginAttribute string
	var bodyAccountSettingsMicrosoftSyncLoginAttributeSuffix string
	var bodyAccountSettingsMicrosoftSyncRemoteAttribute string
	var bodyAccountSettingsRestrictStudentFutureViewLocked bool
	var bodyAccountSettingsLockAllAnnouncementsValue bool
	var bodyAccountSettingsLockAllAnnouncementsLocked bool
	var bodyAccountSettingsUsageRightsRequiredValue bool
	var bodyAccountSettingsUsageRightsRequiredLocked bool
	var bodyAccountSettingsRestrictStudentFutureListingValue bool
	var bodyAccountSettingsRestrictStudentFutureListingLocked bool
	var bodyAccountSettingsConditionalReleaseValue bool
	var bodyAccountSettingsConditionalReleaseLocked bool
	var bodyAccountSettingsEnableCoursePacesValue bool
	var bodyAccountSettingsEnableCoursePacesLocked bool
	var bodyAccountSettingsSuppressNotifications bool
	var bodyAccountSettingsPasswordPolicy string
	var bodyAccountSettingsEnableAsK5AccountValue bool
	var bodyAccountSettingsUseClassicFontInK5Value bool
	var bodyAccountSettingsHorizonAccountValue bool
	var bodyOverrideSisStickiness bool
	var bodyAccountSettingsLockOutcomeProficiencyValue bool
	var bodyAccountLockOutcomeProficiencyLocked bool
	var bodyAccountSettingsLockProficiencyCalculationValue bool
	var bodyAccountLockProficiencyCalculationLocked bool
	var bodyAccountServices string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <id>",
		Short:       "Update an account",
		Example:     "  canvas-cli accounts update 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "accounts.update", "pp:method": "PUT", "pp:path": "/api/v1/accounts/{id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{id}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAccountName != "" {
					body["account[name]"] = bodyAccountName
				}
				if bodyAccountSisAccountId != "" {
					body["account[sis_account_id]"] = bodyAccountSisAccountId
				}
				if bodyAccountDefaultTimeZone != "" {
					body["account[default_time_zone]"] = bodyAccountDefaultTimeZone
				}
				if bodyAccountDefaultStorageQuotaMb != 0 {
					body["account[default_storage_quota_mb]"] = bodyAccountDefaultStorageQuotaMb
				}
				if bodyAccountDefaultUserStorageQuotaMb != 0 {
					body["account[default_user_storage_quota_mb]"] = bodyAccountDefaultUserStorageQuotaMb
				}
				if bodyAccountDefaultGroupStorageQuotaMb != 0 {
					body["account[default_group_storage_quota_mb]"] = bodyAccountDefaultGroupStorageQuotaMb
				}
				if bodyAccountCourseTemplateId != 0 {
					body["account[course_template_id]"] = bodyAccountCourseTemplateId
				}
				if bodyAccountParentAccountId != 0 {
					body["account[parent_account_id]"] = bodyAccountParentAccountId
				}
				if cmd.Flags().Changed("account-settings-restrict-student-past-view-value") {
					body["account[settings][restrict_student_past_view][value]"] = bodyAccountSettingsRestrictStudentPastViewValue
				}
				if cmd.Flags().Changed("account-settings-restrict-student-past-view-locked") {
					body["account[settings][restrict_student_past_view][locked]"] = bodyAccountSettingsRestrictStudentPastViewLocked
				}
				if cmd.Flags().Changed("account-settings-restrict-student-future-view-value") {
					body["account[settings][restrict_student_future_view][value]"] = bodyAccountSettingsRestrictStudentFutureViewValue
				}
				if cmd.Flags().Changed("account-settings-microsoft-sync-enabled") {
					body["account[settings][microsoft_sync_enabled]"] = bodyAccountSettingsMicrosoftSyncEnabled
				}
				if bodyAccountSettingsMicrosoftSyncTenant != "" {
					body["account[settings][microsoft_sync_tenant]"] = bodyAccountSettingsMicrosoftSyncTenant
				}
				if bodyAccountSettingsMicrosoftSyncLoginAttribute != "" {
					body["account[settings][microsoft_sync_login_attribute]"] = bodyAccountSettingsMicrosoftSyncLoginAttribute
				}
				if bodyAccountSettingsMicrosoftSyncLoginAttributeSuffix != "" {
					body["account[settings][microsoft_sync_login_attribute_suffix]"] = bodyAccountSettingsMicrosoftSyncLoginAttributeSuffix
				}
				if bodyAccountSettingsMicrosoftSyncRemoteAttribute != "" {
					body["account[settings][microsoft_sync_remote_attribute]"] = bodyAccountSettingsMicrosoftSyncRemoteAttribute
				}
				if cmd.Flags().Changed("account-settings-restrict-student-future-view-locked") {
					body["account[settings][restrict_student_future_view][locked]"] = bodyAccountSettingsRestrictStudentFutureViewLocked
				}
				if cmd.Flags().Changed("account-settings-lock-all-announcements-value") {
					body["account[settings][lock_all_announcements][value]"] = bodyAccountSettingsLockAllAnnouncementsValue
				}
				if cmd.Flags().Changed("account-settings-lock-all-announcements-locked") {
					body["account[settings][lock_all_announcements][locked]"] = bodyAccountSettingsLockAllAnnouncementsLocked
				}
				if cmd.Flags().Changed("account-settings-usage-rights-required-value") {
					body["account[settings][usage_rights_required][value]"] = bodyAccountSettingsUsageRightsRequiredValue
				}
				if cmd.Flags().Changed("account-settings-usage-rights-required-locked") {
					body["account[settings][usage_rights_required][locked]"] = bodyAccountSettingsUsageRightsRequiredLocked
				}
				if cmd.Flags().Changed("account-settings-restrict-student-future-listing-value") {
					body["account[settings][restrict_student_future_listing][value]"] = bodyAccountSettingsRestrictStudentFutureListingValue
				}
				if cmd.Flags().Changed("account-settings-restrict-student-future-listing-locked") {
					body["account[settings][restrict_student_future_listing][locked]"] = bodyAccountSettingsRestrictStudentFutureListingLocked
				}
				if cmd.Flags().Changed("account-settings-conditional-release-value") {
					body["account[settings][conditional_release][value]"] = bodyAccountSettingsConditionalReleaseValue
				}
				if cmd.Flags().Changed("account-settings-conditional-release-locked") {
					body["account[settings][conditional_release][locked]"] = bodyAccountSettingsConditionalReleaseLocked
				}
				if cmd.Flags().Changed("account-settings-enable-course-paces-value") {
					body["account[settings][enable_course_paces][value]"] = bodyAccountSettingsEnableCoursePacesValue
				}
				if cmd.Flags().Changed("account-settings-enable-course-paces-locked") {
					body["account[settings][enable_course_paces][locked]"] = bodyAccountSettingsEnableCoursePacesLocked
				}
				if cmd.Flags().Changed("account-settings-suppress-notifications") {
					body["account[settings][suppress_notifications]"] = bodyAccountSettingsSuppressNotifications
				}
				if bodyAccountSettingsPasswordPolicy != "" {
					body["account[settings][password_policy]"] = bodyAccountSettingsPasswordPolicy
				}
				if cmd.Flags().Changed("account-settings-enable-as-k5-account-value") {
					body["account[settings][enable_as_k5_account][value]"] = bodyAccountSettingsEnableAsK5AccountValue
				}
				if cmd.Flags().Changed("account-settings-use-classic-font-in-k5-value") {
					body["account[settings][use_classic_font_in_k5][value]"] = bodyAccountSettingsUseClassicFontInK5Value
				}
				if cmd.Flags().Changed("account-settings-horizon-account-value") {
					body["account[settings][horizon_account][value]"] = bodyAccountSettingsHorizonAccountValue
				}
				if cmd.Flags().Changed("override-sis-stickiness") {
					body["override_sis_stickiness"] = bodyOverrideSisStickiness
				}
				if cmd.Flags().Changed("account-settings-lock-outcome-proficiency-value") {
					body["account[settings][lock_outcome_proficiency][value]"] = bodyAccountSettingsLockOutcomeProficiencyValue
				}
				if cmd.Flags().Changed("account-lock-outcome-proficiency-locked") {
					body["account[lock_outcome_proficiency][locked]"] = bodyAccountLockOutcomeProficiencyLocked
				}
				if cmd.Flags().Changed("account-settings-lock-proficiency-calculation-value") {
					body["account[settings][lock_proficiency_calculation][value]"] = bodyAccountSettingsLockProficiencyCalculationValue
				}
				if cmd.Flags().Changed("account-lock-proficiency-calculation-locked") {
					body["account[lock_proficiency_calculation][locked]"] = bodyAccountLockProficiencyCalculationLocked
				}
				if bodyAccountServices != "" {
					body["account[services]"] = bodyAccountServices
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "accounts", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "accounts", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "accounts",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "accounts", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAccountName, "account-name", "", "Updates the account name")
	cmd.Flags().StringVar(&bodyAccountSisAccountId, "account-sis-account-id", "", "Updates the account sis_account_id Must have manage_sis permission and must not be a root_account.")
	cmd.Flags().StringVar(&bodyAccountDefaultTimeZone, "account-default-time-zone", "", "The default time zone of the account. Allowed time zones are IANA time zones or friendlier Ruby on Rails time zones.")
	cmd.Flags().IntVar(&bodyAccountDefaultStorageQuotaMb, "account-default-storage-quota-mb", 0, "The default course storage quota to be used, if not otherwise specified.")
	cmd.Flags().IntVar(&bodyAccountDefaultUserStorageQuotaMb, "account-default-user-storage-quota-mb", 0, "The default user storage quota to be used, if not otherwise specified.")
	cmd.Flags().IntVar(&bodyAccountDefaultGroupStorageQuotaMb, "account-default-group-storage-quota-mb", 0, "The default group storage quota to be used, if not otherwise specified.")
	cmd.Flags().IntVar(&bodyAccountCourseTemplateId, "account-course-template-id", 0, "The ID of a course to be used as a template for all newly created courses.")
	cmd.Flags().IntVar(&bodyAccountParentAccountId, "account-parent-account-id", 0, "The ID of a parent account to move the account to.")
	cmd.Flags().BoolVar(&bodyAccountSettingsRestrictStudentPastViewValue, "account-settings-restrict-student-past-view-value", false, "Restrict students from viewing courses after end date")
	cmd.Flags().BoolVar(&bodyAccountSettingsRestrictStudentPastViewLocked, "account-settings-restrict-student-past-view-locked", false, "Lock this setting for sub-accounts and courses")
	cmd.Flags().BoolVar(&bodyAccountSettingsRestrictStudentFutureViewValue, "account-settings-restrict-student-future-view-value", false, "Restrict students from viewing courses before start date")
	cmd.Flags().BoolVar(&bodyAccountSettingsMicrosoftSyncEnabled, "account-settings-microsoft-sync-enabled", false, "Determines whether this account has Microsoft Teams Sync enabled or not.")
	cmd.Flags().StringVar(&bodyAccountSettingsMicrosoftSyncTenant, "account-settings-microsoft-sync-tenant", "", "The tenant this account should use when using Microsoft Teams Sync.")
	cmd.Flags().StringVar(&bodyAccountSettingsMicrosoftSyncLoginAttribute, "account-settings-microsoft-sync-login-attribute", "", "The attribute this account should use to lookup users when using Microsoft Teams Sync.")
	cmd.Flags().StringVar(&bodyAccountSettingsMicrosoftSyncLoginAttributeSuffix, "account-settings-microsoft-sync-login-attribute-suffix", "", "A suffix that will be appended to the result of the login attribute when associating Canvas users with Microsoft users.")
	cmd.Flags().StringVar(&bodyAccountSettingsMicrosoftSyncRemoteAttribute, "account-settings-microsoft-sync-remote-attribute", "", "The Active Directory attribute to use when associating Canvas users with Microsoft users.")
	cmd.Flags().BoolVar(&bodyAccountSettingsRestrictStudentFutureViewLocked, "account-settings-restrict-student-future-view-locked", false, "Lock this setting for sub-accounts and courses")
	cmd.Flags().BoolVar(&bodyAccountSettingsLockAllAnnouncementsValue, "account-settings-lock-all-announcements-value", false, "Disable comments on announcements")
	cmd.Flags().BoolVar(&bodyAccountSettingsLockAllAnnouncementsLocked, "account-settings-lock-all-announcements-locked", false, "Lock this setting for sub-accounts and courses")
	cmd.Flags().BoolVar(&bodyAccountSettingsUsageRightsRequiredValue, "account-settings-usage-rights-required-value", false, "Copyright and license information must be provided for files before they are published.")
	cmd.Flags().BoolVar(&bodyAccountSettingsUsageRightsRequiredLocked, "account-settings-usage-rights-required-locked", false, "Lock this setting for sub-accounts and courses")
	cmd.Flags().BoolVar(&bodyAccountSettingsRestrictStudentFutureListingValue, "account-settings-restrict-student-future-listing-value", false, "Restrict students from viewing future enrollments in course list")
	cmd.Flags().BoolVar(&bodyAccountSettingsRestrictStudentFutureListingLocked, "account-settings-restrict-student-future-listing-locked", false, "Lock this setting for sub-accounts and courses")
	cmd.Flags().BoolVar(&bodyAccountSettingsConditionalReleaseValue, "account-settings-conditional-release-value", false, "Enable or disable individual learning paths for students based on assessment")
	cmd.Flags().BoolVar(&bodyAccountSettingsConditionalReleaseLocked, "account-settings-conditional-release-locked", false, "Lock this setting for sub-accounts and courses")
	cmd.Flags().BoolVar(&bodyAccountSettingsEnableCoursePacesValue, "account-settings-enable-course-paces-value", false, "Enable or disable course pacing")
	cmd.Flags().BoolVar(&bodyAccountSettingsEnableCoursePacesLocked, "account-settings-enable-course-paces-locked", false, "Lock this setting for sub-accounts and courses")
	cmd.Flags().BoolVar(&bodyAccountSettingsSuppressNotifications, "account-settings-suppress-notifications", false, "Suppress notification messages from being created and sent. When set to +true+, all notifications are suppressed.")
	cmd.Flags().StringVar(&bodyAccountSettingsPasswordPolicy, "account-settings-password-policy", "", "Hash of optional password policy configuration parameters for a root account +allow_login_suspension+ boolean")
	cmd.Flags().BoolVar(&bodyAccountSettingsEnableAsK5AccountValue, "account-settings-enable-as-k5-account-value", false, "Enable or disable Canvas for Elementary for this account")
	cmd.Flags().BoolVar(&bodyAccountSettingsUseClassicFontInK5Value, "account-settings-use-classic-font-in-k5-value", false, "Whether or not the classic font is used on the dashboard. Only applies if enable_as_k5_account is true.")
	cmd.Flags().BoolVar(&bodyAccountSettingsHorizonAccountValue, "account-settings-horizon-account-value", false, "Enable or disable Canvas Career for this account")
	cmd.Flags().BoolVar(&bodyOverrideSisStickiness, "override-sis-stickiness", false, "Default is true. If false, any fields containing “sticky” changes will not be updated.")
	cmd.Flags().BoolVar(&bodyAccountSettingsLockOutcomeProficiencyValue, "account-settings-lock-outcome-proficiency-value", false, "[DEPRECATED] Restrict instructors from changing mastery scale")
	cmd.Flags().BoolVar(&bodyAccountLockOutcomeProficiencyLocked, "account-lock-outcome-proficiency-locked", false, "[DEPRECATED] Lock this setting for sub-accounts and courses")
	cmd.Flags().BoolVar(&bodyAccountSettingsLockProficiencyCalculationValue, "account-settings-lock-proficiency-calculation-value", false, "[DEPRECATED] Restrict instructors from changing proficiency calculation method")
	cmd.Flags().BoolVar(&bodyAccountLockProficiencyCalculationLocked, "account-lock-proficiency-calculation-locked", false, "[DEPRECATED] Lock this setting for sub-accounts and courses")
	cmd.Flags().StringVar(&bodyAccountServices, "account-services", "", "Give this a set of keys and boolean values to enable or disable services matching the keys")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
