// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountCalendarsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "account-calendars",
		Short:       "API for viewing and toggling settings of account calendars.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountCalendarsAllCalendarsCmd(flags))
	cmd.AddCommand(newAccountCalendarsBulkUpdateCmd(flags))
	cmd.AddCommand(newAccountCalendarsIndexCmd(flags))
	cmd.AddCommand(newAccountCalendarsShowCmd(flags))
	cmd.AddCommand(newAccountCalendarsUpdateCmd(flags))
	cmd.AddCommand(newAccountCalendarsVisibleCalendarsCountCmd(flags))
	return cmd
}
