// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountReportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "account-reports",
		Short:       "API for accessing account reports.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountReportsAbortCmd(flags))
	cmd.AddCommand(newAccountReportsAvailableReportsCmd(flags))
	cmd.AddCommand(newAccountReportsCreateCmd(flags))
	cmd.AddCommand(newAccountReportsDestroyCmd(flags))
	cmd.AddCommand(newAccountReportsIndexCmd(flags))
	cmd.AddCommand(newAccountReportsShowCmd(flags))
	return cmd
}
