// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountNotificationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "account-notifications",
		Short:       "API for account notifications.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountNotificationsCreateCmd(flags))
	cmd.AddCommand(newAccountNotificationsShowCmd(flags))
	cmd.AddCommand(newAccountNotificationsUpdateCmd(flags))
	cmd.AddCommand(newAccountNotificationsUserCloseNotificationCmd(flags))
	cmd.AddCommand(newAccountNotificationsUserIndexCmd(flags))
	return cmd
}
