// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "accounts",
		Short:       "API for accessing account data.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountsCourseAccountsCmd(flags))
	cmd.AddCommand(newAccountsCourseCreationAccountsCmd(flags))
	cmd.AddCommand(newAccountsCoursesApiCmd(flags))
	cmd.AddCommand(newAccountsCreateCmd(flags))
	cmd.AddCommand(newAccountsDestroyCmd(flags))
	cmd.AddCommand(newAccountsEnvironmentCmd(flags))
	cmd.AddCommand(newAccountsHelpLinksCmd(flags))
	cmd.AddCommand(newAccountsHorizonAccountsCmd(flags))
	cmd.AddCommand(newAccountsIndexCmd(flags))
	cmd.AddCommand(newAccountsManageableAccountsCmd(flags))
	cmd.AddCommand(newAccountsManuallyCreatedCoursesAccountCmd(flags))
	cmd.AddCommand(newAccountsPermissionsCmd(flags))
	cmd.AddCommand(newAccountsRemoveUserCmd(flags))
	cmd.AddCommand(newAccountsRemoveUsersCmd(flags))
	cmd.AddCommand(newAccountsRestoreUserCmd(flags))
	cmd.AddCommand(newAccountsShowCmd(flags))
	cmd.AddCommand(newAccountsShowSettingsCmd(flags))
	cmd.AddCommand(newAccountsSubAccountsCmd(flags))
	cmd.AddCommand(newAccountsTermsOfServiceCmd(flags))
	cmd.AddCommand(newAccountsUpdateCmd(flags))
	cmd.AddCommand(newAccountsUpdateUsersCmd(flags))
	return cmd
}
