// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newAssignmentsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignmentName string
	var bodyAssignmentPosition int
	var bodyAssignmentSubmissionTypes string
	var bodyAssignmentAllowedExtensions string
	var bodyAssignmentTurnitinEnabled bool
	var bodyAssignmentVericiteEnabled bool
	var bodyAssignmentTurnitinSettings string
	var bodyAssignmentSisAssignmentId string
	var bodyAssignmentIntegrationData string
	var bodyAssignmentIntegrationId string
	var bodyAssignmentPeerReviews bool
	var bodyAssignmentAutomaticPeerReviews bool
	var bodyAssignmentNotifyOfUpdate bool
	var bodyAssignmentGroupCategoryId int
	var bodyAssignmentGradeGroupStudentsIndividually int
	var bodyAssignmentExternalToolTagAttributes string
	var bodyAssignmentPointsPossible float64
	var bodyAssignmentGradingType string
	var bodyAssignmentDueAt string
	var bodyAssignmentLockAt string
	var bodyAssignmentUnlockAt string
	var bodyAssignmentDescription string
	var bodyAssignmentAssignmentGroupId int
	var bodyAssignmentAssignmentOverrides string
	var bodyAssignmentOnlyVisibleToOverrides bool
	var bodyAssignmentPublished bool
	var bodyAssignmentGradingStandardId int
	var bodyAssignmentOmitFromFinalGrade bool
	var bodyAssignmentHideInGradebook bool
	var bodyAssignmentModeratedGrading bool
	var bodyAssignmentGraderCount int
	var bodyAssignmentFinalGraderId int
	var bodyAssignmentGraderCommentsVisibleToGraders bool
	var bodyAssignmentGradersAnonymousToGraders bool
	var bodyAssignmentGradersNamesVisibleToFinalGrader bool
	var bodyAssignmentAnonymousGrading bool
	var bodyAssignmentAllowedAttempts int
	var bodyAssignmentAnnotatableAttachmentId int
	var bodyAssignmentAssetProcessors string
	var bodyAssignmentForceUpdatedAt bool
	var bodyAssignmentPeerReviewPointsPossible float64
	var bodyAssignmentPeerReviewGradingType string
	var bodyAssignmentPeerReviewDueAt string
	var bodyAssignmentPeerReviewLockAt string
	var bodyAssignmentPeerReviewUnlockAt string
	var bodyAssignmentPeerReviewPeerReviewOverrides string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <course_id> <id>",
		Short:       "Edit an assignment",
		Example:     "  canvas-cli assignments update 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "assignments.update", "pp:method": "PUT", "pp:path": "/api/v1/courses/{course_id}/assignments/{id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/courses/{course_id}/assignments/{id}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[1])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAssignmentName != "" {
					body["assignment[name]"] = bodyAssignmentName
				}
				if bodyAssignmentPosition != 0 {
					body["assignment[position]"] = bodyAssignmentPosition
				}
				if bodyAssignmentSubmissionTypes != "" {
					body["assignment[submission_types][]"] = bodyAssignmentSubmissionTypes
				}
				if bodyAssignmentAllowedExtensions != "" {
					body["assignment[allowed_extensions][]"] = bodyAssignmentAllowedExtensions
				}
				if cmd.Flags().Changed("assignment-turnitin-enabled") {
					body["assignment[turnitin_enabled]"] = bodyAssignmentTurnitinEnabled
				}
				if cmd.Flags().Changed("assignment-vericite-enabled") {
					body["assignment[vericite_enabled]"] = bodyAssignmentVericiteEnabled
				}
				if bodyAssignmentTurnitinSettings != "" {
					body["assignment[turnitin_settings]"] = bodyAssignmentTurnitinSettings
				}
				if bodyAssignmentSisAssignmentId != "" {
					body["assignment[sis_assignment_id]"] = bodyAssignmentSisAssignmentId
				}
				if bodyAssignmentIntegrationData != "" {
					body["assignment[integration_data]"] = bodyAssignmentIntegrationData
				}
				if bodyAssignmentIntegrationId != "" {
					body["assignment[integration_id]"] = bodyAssignmentIntegrationId
				}
				if cmd.Flags().Changed("assignment-peer-reviews") {
					body["assignment[peer_reviews]"] = bodyAssignmentPeerReviews
				}
				if cmd.Flags().Changed("assignment-automatic-peer-reviews") {
					body["assignment[automatic_peer_reviews]"] = bodyAssignmentAutomaticPeerReviews
				}
				if cmd.Flags().Changed("assignment-notify-of-update") {
					body["assignment[notify_of_update]"] = bodyAssignmentNotifyOfUpdate
				}
				if bodyAssignmentGroupCategoryId != 0 {
					body["assignment[group_category_id]"] = bodyAssignmentGroupCategoryId
				}
				if bodyAssignmentGradeGroupStudentsIndividually != 0 {
					body["assignment[grade_group_students_individually]"] = bodyAssignmentGradeGroupStudentsIndividually
				}
				if bodyAssignmentExternalToolTagAttributes != "" {
					body["assignment[external_tool_tag_attributes]"] = bodyAssignmentExternalToolTagAttributes
				}
				if bodyAssignmentPointsPossible != 0.0 {
					body["assignment[points_possible]"] = bodyAssignmentPointsPossible
				}
				if bodyAssignmentGradingType != "" {
					body["assignment[grading_type]"] = bodyAssignmentGradingType
				}
				if bodyAssignmentDueAt != "" {
					body["assignment[due_at]"] = bodyAssignmentDueAt
				}
				if bodyAssignmentLockAt != "" {
					body["assignment[lock_at]"] = bodyAssignmentLockAt
				}
				if bodyAssignmentUnlockAt != "" {
					body["assignment[unlock_at]"] = bodyAssignmentUnlockAt
				}
				if bodyAssignmentDescription != "" {
					body["assignment[description]"] = bodyAssignmentDescription
				}
				if bodyAssignmentAssignmentGroupId != 0 {
					body["assignment[assignment_group_id]"] = bodyAssignmentAssignmentGroupId
				}
				if bodyAssignmentAssignmentOverrides != "" {
					body["assignment[assignment_overrides][]"] = bodyAssignmentAssignmentOverrides
				}
				if cmd.Flags().Changed("assignment-only-visible-to-overrides") {
					body["assignment[only_visible_to_overrides]"] = bodyAssignmentOnlyVisibleToOverrides
				}
				if cmd.Flags().Changed("assignment-published") {
					body["assignment[published]"] = bodyAssignmentPublished
				}
				if bodyAssignmentGradingStandardId != 0 {
					body["assignment[grading_standard_id]"] = bodyAssignmentGradingStandardId
				}
				if cmd.Flags().Changed("assignment-omit-from-final-grade") {
					body["assignment[omit_from_final_grade]"] = bodyAssignmentOmitFromFinalGrade
				}
				if cmd.Flags().Changed("assignment-hide-in-gradebook") {
					body["assignment[hide_in_gradebook]"] = bodyAssignmentHideInGradebook
				}
				if cmd.Flags().Changed("assignment-moderated-grading") {
					body["assignment[moderated_grading]"] = bodyAssignmentModeratedGrading
				}
				if bodyAssignmentGraderCount != 0 {
					body["assignment[grader_count]"] = bodyAssignmentGraderCount
				}
				if bodyAssignmentFinalGraderId != 0 {
					body["assignment[final_grader_id]"] = bodyAssignmentFinalGraderId
				}
				if cmd.Flags().Changed("assignment-grader-comments-visible-to-graders") {
					body["assignment[grader_comments_visible_to_graders]"] = bodyAssignmentGraderCommentsVisibleToGraders
				}
				if cmd.Flags().Changed("assignment-graders-anonymous-to-graders") {
					body["assignment[graders_anonymous_to_graders]"] = bodyAssignmentGradersAnonymousToGraders
				}
				if cmd.Flags().Changed("assignment-graders-names-visible-to-final-grader") {
					body["assignment[graders_names_visible_to_final_grader]"] = bodyAssignmentGradersNamesVisibleToFinalGrader
				}
				if cmd.Flags().Changed("assignment-anonymous-grading") {
					body["assignment[anonymous_grading]"] = bodyAssignmentAnonymousGrading
				}
				if bodyAssignmentAllowedAttempts != 0 {
					body["assignment[allowed_attempts]"] = bodyAssignmentAllowedAttempts
				}
				if bodyAssignmentAnnotatableAttachmentId != 0 {
					body["assignment[annotatable_attachment_id]"] = bodyAssignmentAnnotatableAttachmentId
				}
				if bodyAssignmentAssetProcessors != "" {
					body["assignment[asset_processors][]"] = bodyAssignmentAssetProcessors
				}
				if cmd.Flags().Changed("assignment-force-updated-at") {
					body["assignment[force_updated_at]"] = bodyAssignmentForceUpdatedAt
				}
				if bodyAssignmentPeerReviewPointsPossible != 0.0 {
					body["assignment[peer_review][points_possible]"] = bodyAssignmentPeerReviewPointsPossible
				}
				if bodyAssignmentPeerReviewGradingType != "" {
					body["assignment[peer_review][grading_type]"] = bodyAssignmentPeerReviewGradingType
				}
				if bodyAssignmentPeerReviewDueAt != "" {
					body["assignment[peer_review][due_at]"] = bodyAssignmentPeerReviewDueAt
				}
				if bodyAssignmentPeerReviewLockAt != "" {
					body["assignment[peer_review][lock_at]"] = bodyAssignmentPeerReviewLockAt
				}
				if bodyAssignmentPeerReviewUnlockAt != "" {
					body["assignment[peer_review][unlock_at]"] = bodyAssignmentPeerReviewUnlockAt
				}
				if bodyAssignmentPeerReviewPeerReviewOverrides != "" {
					body["assignment[peer_review][peer_review_overrides][]"] = bodyAssignmentPeerReviewPeerReviewOverrides
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "assignments", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "assignments", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "assignments", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "assignments", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "assignments", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "assignments",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "assignments", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "assignments", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAssignmentName, "assignment-name", "", "The assignment name.")
	cmd.Flags().IntVar(&bodyAssignmentPosition, "assignment-position", 0, "The position of this assignment in the group when displaying assignment lists.")
	cmd.Flags().StringVar(&bodyAssignmentSubmissionTypes, "assignment-submission-types", "", "Only applies if the assignment doesn't have student submissions. List of supported submission types for the assignment.")
	cmd.Flags().StringVar(&bodyAssignmentAllowedExtensions, "assignment-allowed-extensions", "", "Allowed extensions if submission_types includes 'online_upload' Example: allowed_extensions: ['docx','ppt']")
	cmd.Flags().BoolVar(&bodyAssignmentTurnitinEnabled, "assignment-turnitin-enabled", false, "Only applies when the Turnitin plugin is enabled for a course and the submission_types array includes 'online_upload'.")
	cmd.Flags().BoolVar(&bodyAssignmentVericiteEnabled, "assignment-vericite-enabled", false, "Only applies when the VeriCite plugin is enabled for a course and the submission_types array includes 'online_upload'.")
	cmd.Flags().StringVar(&bodyAssignmentTurnitinSettings, "assignment-turnitin-settings", "", "Settings to send along to turnitin. See Assignment object definition for format.")
	cmd.Flags().StringVar(&bodyAssignmentSisAssignmentId, "assignment-sis-assignment-id", "", "The sis id of the Assignment")
	cmd.Flags().StringVar(&bodyAssignmentIntegrationData, "assignment-integration-data", "", "Data used for SIS integrations. Requires admin-level token with the 'Manage SIS' permission. JSON string required.")
	cmd.Flags().StringVar(&bodyAssignmentIntegrationId, "assignment-integration-id", "", "Unique ID from third party integrations")
	cmd.Flags().BoolVar(&bodyAssignmentPeerReviews, "assignment-peer-reviews", false, "If submission_types does not include external_tool,discussion_topic, online_quiz, or on_paper")
	cmd.Flags().BoolVar(&bodyAssignmentAutomaticPeerReviews, "assignment-automatic-peer-reviews", false, "Whether peer reviews will be assigned automatically by Canvas or if teachers must manually assign peer reviews.")
	cmd.Flags().BoolVar(&bodyAssignmentNotifyOfUpdate, "assignment-notify-of-update", false, "If true, Canvas will send a notification to students in the class notifying them that the content has changed.")
	cmd.Flags().IntVar(&bodyAssignmentGroupCategoryId, "assignment-group-category-id", 0, "If present, the assignment will become a group assignment assigned to the group.")
	cmd.Flags().IntVar(&bodyAssignmentGradeGroupStudentsIndividually, "assignment-grade-group-students-individually", 0, "If this is a group assignment, teachers have the options to grade students individually.")
	cmd.Flags().StringVar(&bodyAssignmentExternalToolTagAttributes, "assignment-external-tool-tag-attributes", "", "Hash of external tool parameters if submission_types is ['external_tool']. See Assignment object definition for format.")
	cmd.Flags().Float64Var(&bodyAssignmentPointsPossible, "assignment-points-possible", 0.0, "The maximum points possible on the assignment.")
	cmd.Flags().StringVar(&bodyAssignmentGradingType, "assignment-grading-type", "", "The strategy used for grading the assignment. The assignment defaults to 'points' if this field is omitted.")
	cmd.Flags().StringVar(&bodyAssignmentDueAt, "assignment-due-at", "", "The day/time the assignment is due. Accepts times in ISO 8601 format, e.g. 2014-10-21T18:48:00Z.")
	cmd.Flags().StringVar(&bodyAssignmentLockAt, "assignment-lock-at", "", "The day/time the assignment is locked after. Must be after the due date if there is a due date.")
	cmd.Flags().StringVar(&bodyAssignmentUnlockAt, "assignment-unlock-at", "", "The day/time the assignment is unlocked. Must be before the due date if there is a due date.")
	cmd.Flags().StringVar(&bodyAssignmentDescription, "assignment-description", "", "The assignment's description, supports HTML.")
	cmd.Flags().IntVar(&bodyAssignmentAssignmentGroupId, "assignment-assignment-group-id", 0, "The assignment group id to put the assignment in. Defaults to the top assignment group in the course.")
	cmd.Flags().StringVar(&bodyAssignmentAssignmentOverrides, "assignment-assignment-overrides", "", "List of overrides for the assignment.")
	cmd.Flags().BoolVar(&bodyAssignmentOnlyVisibleToOverrides, "assignment-only-visible-to-overrides", false, "Whether this assignment is only visible to overrides (Only useful if 'differentiated assignments' account setting is on)")
	cmd.Flags().BoolVar(&bodyAssignmentPublished, "assignment-published", false, "Whether this assignment is published.")
	cmd.Flags().IntVar(&bodyAssignmentGradingStandardId, "assignment-grading-standard-id", 0, "The grading standard id to set for the course.")
	cmd.Flags().BoolVar(&bodyAssignmentOmitFromFinalGrade, "assignment-omit-from-final-grade", false, "Whether this assignment is counted towards a student's final grade.")
	cmd.Flags().BoolVar(&bodyAssignmentHideInGradebook, "assignment-hide-in-gradebook", false, "Whether this assignment is shown in the gradebook.")
	cmd.Flags().BoolVar(&bodyAssignmentModeratedGrading, "assignment-moderated-grading", false, "Whether this assignment is moderated.")
	cmd.Flags().IntVar(&bodyAssignmentGraderCount, "assignment-grader-count", 0, "The maximum number of provisional graders who may issue grades for this assignment.")
	cmd.Flags().IntVar(&bodyAssignmentFinalGraderId, "assignment-final-grader-id", 0, "The user ID of the grader responsible for choosing final grades for this assignment.")
	cmd.Flags().BoolVar(&bodyAssignmentGraderCommentsVisibleToGraders, "assignment-grader-comments-visible-to-graders", false, "Boolean indicating if provisional graders' comments are visible to other provisional graders.")
	cmd.Flags().BoolVar(&bodyAssignmentGradersAnonymousToGraders, "assignment-graders-anonymous-to-graders", false, "Boolean indicating if provisional graders' identities are hidden from other provisional graders.")
	cmd.Flags().BoolVar(&bodyAssignmentGradersNamesVisibleToFinalGrader, "assignment-graders-names-visible-to-final-grader", false, "Boolean indicating if provisional grader identities are visible to the the final grader.")
	cmd.Flags().BoolVar(&bodyAssignmentAnonymousGrading, "assignment-anonymous-grading", false, "Boolean indicating if the assignment is graded anonymously. If true, graders cannot see student identities.")
	cmd.Flags().IntVar(&bodyAssignmentAllowedAttempts, "assignment-allowed-attempts", 0, "The number of submission attempts allowed for this assignment. Set to -1 or null for unlimited attempts.")
	cmd.Flags().IntVar(&bodyAssignmentAnnotatableAttachmentId, "assignment-annotatable-attachment-id", 0, "The Attachment ID of the document being annotated. Only applies when submission_types includes 'student_annotation'.")
	cmd.Flags().StringVar(&bodyAssignmentAssetProcessors, "assignment-asset-processors", "", "Document processors for this assignment.")
	cmd.Flags().BoolVar(&bodyAssignmentForceUpdatedAt, "assignment-force-updated-at", false, "If true, updated_at will be set even if no changes were made.")
	cmd.Flags().Float64Var(&bodyAssignmentPeerReviewPointsPossible, "assignment-peer-review-points-possible", 0.0, "The maximum points possible for peer reviews.")
	cmd.Flags().StringVar(&bodyAssignmentPeerReviewGradingType, "assignment-peer-review-grading-type", "", "The strategy used for grading peer reviews. Defaults to 'points' if this field is omitted.")
	cmd.Flags().StringVar(&bodyAssignmentPeerReviewDueAt, "assignment-peer-review-due-at", "", "The day/time the peer reviews are due. Must be between the lock dates if there are lock dates.")
	cmd.Flags().StringVar(&bodyAssignmentPeerReviewLockAt, "assignment-peer-review-lock-at", "", "The day/time the peer reviews are locked after. Must be after the due date if there is a due date.")
	cmd.Flags().StringVar(&bodyAssignmentPeerReviewUnlockAt, "assignment-peer-review-unlock-at", "", "The day/time the peer reviews are unlocked. Must be before the due date if there is a due date.")
	cmd.Flags().StringVar(&bodyAssignmentPeerReviewPeerReviewOverrides, "assignment-peer-review-peer-review-overrides", "", "List of overrides for the peer reviews.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
