// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAssignmentGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "assignment-groups",
		Short:       "API for accessing Assignment Group and Assignment information.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAssignmentGroupsCreateCmd(flags))
	cmd.AddCommand(newAssignmentGroupsDestroyCmd(flags))
	cmd.AddCommand(newAssignmentGroupsIndexCmd(flags))
	cmd.AddCommand(newAssignmentGroupsShowCmd(flags))
	cmd.AddCommand(newAssignmentGroupsUpdateCmd(flags))
	return cmd
}
