// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAuthenticationProvidersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "authentication-providers",
		Short:       "Get, create, update, and delete authentication providers",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthenticationProvidersCreateCmd(flags))
	cmd.AddCommand(newAuthenticationProvidersDestroyCmd(flags))
	cmd.AddCommand(newAuthenticationProvidersForcePasswordResetCmd(flags))
	cmd.AddCommand(newAuthenticationProvidersIndexCmd(flags))
	cmd.AddCommand(newAuthenticationProvidersRestoreCmd(flags))
	cmd.AddCommand(newAuthenticationProvidersShowCmd(flags))
	cmd.AddCommand(newAuthenticationProvidersShowSsoSettingsCmd(flags))
	cmd.AddCommand(newAuthenticationProvidersUpdateCmd(flags))
	cmd.AddCommand(newAuthenticationProvidersUpdateSsoSettingsCmd(flags))
	return cmd
}
