// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAuthenticationsLogCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "authentications-log",
		Short:       "Query audit log of authentication events (logins and logouts).",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthenticationsLogForAccountCmd(flags))
	cmd.AddCommand(newAuthenticationsLogForLoginCmd(flags))
	cmd.AddCommand(newAuthenticationsLogForUserCmd(flags))
	return cmd
}
