// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBlackoutDatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "blackout-dates",
		Short:       "API for accessing blackout date information.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBlackoutDatesBulkUpdateCmd(flags))
	cmd.AddCommand(newBlackoutDatesCreateCmd(flags))
	cmd.AddCommand(newBlackoutDatesCreate2Cmd(flags))
	cmd.AddCommand(newBlackoutDatesDestroyCmd(flags))
	cmd.AddCommand(newBlackoutDatesDestroy2Cmd(flags))
	cmd.AddCommand(newBlackoutDatesIndexCmd(flags))
	cmd.AddCommand(newBlackoutDatesIndex2Cmd(flags))
	cmd.AddCommand(newBlackoutDatesNewCmd(flags))
	cmd.AddCommand(newBlackoutDatesNew2Cmd(flags))
	cmd.AddCommand(newBlackoutDatesShowCmd(flags))
	cmd.AddCommand(newBlackoutDatesShow2Cmd(flags))
	cmd.AddCommand(newBlackoutDatesUpdateCmd(flags))
	cmd.AddCommand(newBlackoutDatesUpdate2Cmd(flags))
	return cmd
}
