// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBlueprintCoursesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "blueprint-courses",
		Short:       "Get, create, and update blueprint courses",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBlueprintCoursesGetAssociatedCoursesCmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetBlueprintSubscriptionsCmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetBlueprintTemplatesCmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetDetailsCmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetDetails2Cmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetMigrationsCmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetMigrations2Cmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetMigrations3Cmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetMigrations4Cmd(flags))
	cmd.AddCommand(newBlueprintCoursesGetUnsyncedChangesCmd(flags))
	cmd.AddCommand(newBlueprintCoursesPostMigrationsCmd(flags))
	cmd.AddCommand(newBlueprintCoursesPutRestrictItemCmd(flags))
	cmd.AddCommand(newBlueprintCoursesPutUpdateAssociationsCmd(flags))
	return cmd
}
