// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBookmarksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "bookmarks",
		Short:       "Get, create, update, and delete bookmarks",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBookmarksDeleteBookmarksCmd(flags))
	cmd.AddCommand(newBookmarksGetBookmarksCmd(flags))
	cmd.AddCommand(newBookmarksGetBookmarks2Cmd(flags))
	cmd.AddCommand(newBookmarksPostBookmarksCmd(flags))
	cmd.AddCommand(newBookmarksPutBookmarksCmd(flags))
	return cmd
}
