// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBrandConfigsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "brand-configs",
		Short:       "[BrandConfigsApiController#show](https://github.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newBrandConfigsShowCmd(flags))
	cmd.AddCommand(newBrandConfigsShowContextCmd(flags))
	cmd.AddCommand(newBrandConfigsShowContext2Cmd(flags))
	return cmd
}
