// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCalendarEventsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "calendar-events",
		Short:       "API for creating, accessing and updating calendar events.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCalendarEventsCreateCmd(flags))
	cmd.AddCommand(newCalendarEventsDestroyCmd(flags))
	cmd.AddCommand(newCalendarEventsGetCourseTimetableCmd(flags))
	cmd.AddCommand(newCalendarEventsIndexCmd(flags))
	cmd.AddCommand(newCalendarEventsReserveCmd(flags))
	cmd.AddCommand(newCalendarEventsReserve2Cmd(flags))
	cmd.AddCommand(newCalendarEventsSaveEnabledAccountCalendarsCmd(flags))
	cmd.AddCommand(newCalendarEventsSetCourseTimetableCmd(flags))
	cmd.AddCommand(newCalendarEventsSetCourseTimetableEventsCmd(flags))
	cmd.AddCommand(newCalendarEventsShowCmd(flags))
	cmd.AddCommand(newCalendarEventsUpdateCmd(flags))
	cmd.AddCommand(newCalendarEventsUserIndexCmd(flags))
	return cmd
}
