// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCalendarEventsIndexCmd(flags *rootFlags) *cobra.Command {
	var flagType string
	var flagStartDate string
	var flagEndDate string
	var flagUndated bool
	var flagAllEvents bool
	var flagContextCodes string
	var flagExcludes string
	var flagIncludes string
	var flagImportantDates bool
	var flagBlackoutDate bool

	cmd := &cobra.Command{
		Use:         "index",
		Short:       "List calendar events",
		Example:     "  canvas-cli calendar_events index",
		Annotations: map[string]string{"pp:endpoint": "calendar_events.index", "pp:method": "GET", "pp:path": "/api/v1/calendar_events", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/calendar_events"
			params := map[string]string{}
			if flagType != "" {
				params["type"] = formatCLIParamValue(flagType)
			}
			if flagStartDate != "" {
				params["start_date"] = formatCLIParamValue(flagStartDate)
			}
			if flagEndDate != "" {
				params["end_date"] = formatCLIParamValue(flagEndDate)
			}
			if flagUndated != false {
				params["undated"] = formatCLIParamValue(flagUndated)
			}
			if flagAllEvents != false {
				params["all_events"] = formatCLIParamValue(flagAllEvents)
			}
			if flagContextCodes != "" {
				params["context_codes[]"] = formatCLIParamValue(flagContextCodes)
			}
			if flagExcludes != "" {
				params["excludes[]"] = formatCLIParamValue(flagExcludes)
			}
			if flagIncludes != "" {
				params["includes[]"] = formatCLIParamValue(flagIncludes)
			}
			if flagImportantDates != false {
				params["important_dates"] = formatCLIParamValue(flagImportantDates)
			}
			if flagBlackoutDate != false {
				params["blackout_date"] = formatCLIParamValue(flagBlackoutDate)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "calendar_events", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagType, "type", "", "Defaults to 'event' Allowed values: event, assignment, sub_assignment")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Only return events since the start_date (inclusive). Defaults to today.")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Only return events before the end_date (inclusive). Defaults to start_date.")
	cmd.Flags().BoolVar(&flagUndated, "undated", false, "Defaults to false (dated events only). If true, only return undated events and ignore start_date and end_date.")
	cmd.Flags().BoolVar(&flagAllEvents, "all-events", false, "Defaults to false (uses start_date, end_date, and undated criteria).")
	cmd.Flags().StringVar(&flagContextCodes, "context-codes", "", "List of context codes of courses, groups, users, or accounts whose events you want to see.")
	cmd.Flags().StringVar(&flagExcludes, "excludes", "", "Array of attributes to exclude. Possible values are 'description', 'child_events' and 'assignment'")
	cmd.Flags().StringVar(&flagIncludes, "includes", "", "Array of optional attributes to include. Possible values are 'web_conference' and 'series_natural_language'")
	cmd.Flags().BoolVar(&flagImportantDates, "important-dates", false, "Defaults to false. If true, only events with important dates set to true will be returned.")
	cmd.Flags().BoolVar(&flagBlackoutDate, "blackout-date", false, "Defaults to false. If true, only events with blackout date set to true will be returned.")

	return cmd
}
