// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCanvasCareerExperiencesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "canvas-career-experiences",
		Short:       "API for managing user career experience and role preferences in Canvas.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCanvasCareerExperiencesEnabledCmd(flags))
	cmd.AddCommand(newCanvasCareerExperiencesExperienceSummaryCmd(flags))
	cmd.AddCommand(newCanvasCareerExperiencesSwitchExperienceCmd(flags))
	cmd.AddCommand(newCanvasCareerExperiencesSwitchRoleCmd(flags))
	return cmd
}
