// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCollaborationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "collaborations",
		Short:       "API for accessing course and group collaboration information.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCollaborationsApiIndexCmd(flags))
	cmd.AddCommand(newCollaborationsApiIndex2Cmd(flags))
	cmd.AddCommand(newCollaborationsMembersCmd(flags))
	cmd.AddCommand(newCollaborationsPotentialCollaboratorsCmd(flags))
	cmd.AddCommand(newCollaborationsPotentialCollaborators2Cmd(flags))
	return cmd
}
