// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newContentMigrationsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyMigrationType string
	var bodyPreAttachmentName string
	var bodyPreAttachment string
	var bodySettingsFileUrl string
	var bodySettingsContentExportId string
	var bodySettingsSourceCourseId string
	var bodySettingsFolderId string
	var bodySettingsOverwriteQuizzes bool
	var bodySettingsQuestionBankId int
	var bodySettingsQuestionBankName string
	var bodySettingsInsertIntoModuleId int
	var bodySettingsInsertIntoModuleType string
	var bodySettingsInsertIntoModulePosition int
	var bodySettingsMoveToAssignmentGroupId int
	var bodySettingsImporterSkips string
	var bodySettingsImportBlueprintSettings bool
	var bodyDateShiftOptionsShiftDates bool
	var bodyDateShiftOptionsOldStartDate string
	var bodyDateShiftOptionsOldEndDate string
	var bodyDateShiftOptionsNewStartDate string
	var bodyDateShiftOptionsNewEndDate string
	var bodyDateShiftOptionsDaySubstitutionsX int
	var bodyDateShiftOptionsRemoveDates bool
	var bodySelectiveImport bool
	var bodySelect string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create <account_id>",
		Short: "Create a content migration",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  canvas-cli content_migrations create 550e8400-e29b-41d4-a716-446655440000 --migration-type example-value",
		Annotations: map[string]string{"pp:endpoint": "content_migrations.create", "pp:method": "POST", "pp:path": "/api/v1/accounts/{account_id}/content_migrations"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("migration-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "migration-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{account_id}/content_migrations"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyMigrationType != "" {
					body["migration_type"] = bodyMigrationType
				}
				if bodyPreAttachmentName != "" {
					body["pre_attachment[name]"] = bodyPreAttachmentName
				}
				if bodyPreAttachment != "" {
					body["pre_attachment[*]"] = bodyPreAttachment
				}
				if bodySettingsFileUrl != "" {
					body["settings[file_url]"] = bodySettingsFileUrl
				}
				if bodySettingsContentExportId != "" {
					body["settings[content_export_id]"] = bodySettingsContentExportId
				}
				if bodySettingsSourceCourseId != "" {
					body["settings[source_course_id]"] = bodySettingsSourceCourseId
				}
				if bodySettingsFolderId != "" {
					body["settings[folder_id]"] = bodySettingsFolderId
				}
				if cmd.Flags().Changed("settings-overwrite-quizzes") {
					body["settings[overwrite_quizzes]"] = bodySettingsOverwriteQuizzes
				}
				if bodySettingsQuestionBankId != 0 {
					body["settings[question_bank_id]"] = bodySettingsQuestionBankId
				}
				if bodySettingsQuestionBankName != "" {
					body["settings[question_bank_name]"] = bodySettingsQuestionBankName
				}
				if bodySettingsInsertIntoModuleId != 0 {
					body["settings[insert_into_module_id]"] = bodySettingsInsertIntoModuleId
				}
				if bodySettingsInsertIntoModuleType != "" {
					body["settings[insert_into_module_type]"] = bodySettingsInsertIntoModuleType
				}
				if bodySettingsInsertIntoModulePosition != 0 {
					body["settings[insert_into_module_position]"] = bodySettingsInsertIntoModulePosition
				}
				if bodySettingsMoveToAssignmentGroupId != 0 {
					body["settings[move_to_assignment_group_id]"] = bodySettingsMoveToAssignmentGroupId
				}
				if bodySettingsImporterSkips != "" {
					body["settings[importer_skips]"] = bodySettingsImporterSkips
				}
				if cmd.Flags().Changed("settings-import-blueprint-settings") {
					body["settings[import_blueprint_settings]"] = bodySettingsImportBlueprintSettings
				}
				if cmd.Flags().Changed("date-shift-options-shift-dates") {
					body["date_shift_options[shift_dates]"] = bodyDateShiftOptionsShiftDates
				}
				if bodyDateShiftOptionsOldStartDate != "" {
					body["date_shift_options[old_start_date]"] = bodyDateShiftOptionsOldStartDate
				}
				if bodyDateShiftOptionsOldEndDate != "" {
					body["date_shift_options[old_end_date]"] = bodyDateShiftOptionsOldEndDate
				}
				if bodyDateShiftOptionsNewStartDate != "" {
					body["date_shift_options[new_start_date]"] = bodyDateShiftOptionsNewStartDate
				}
				if bodyDateShiftOptionsNewEndDate != "" {
					body["date_shift_options[new_end_date]"] = bodyDateShiftOptionsNewEndDate
				}
				if bodyDateShiftOptionsDaySubstitutionsX != 0 {
					body["date_shift_options[day_substitutions][X]"] = bodyDateShiftOptionsDaySubstitutionsX
				}
				if cmd.Flags().Changed("date-shift-options-remove-dates") {
					body["date_shift_options[remove_dates]"] = bodyDateShiftOptionsRemoveDates
				}
				if cmd.Flags().Changed("selective-import") {
					body["selective_import"] = bodySelectiveImport
				}
				if bodySelect != "" {
					body["select"] = bodySelect
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "content_migrations", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "content_migrations", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "content_migrations", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "content_migrations", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "content_migrations", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "content_migrations",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "content_migrations", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "content_migrations", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyMigrationType, "migration-type", "", "The type of the migration. Use the Migrator endpoint to see all available migrators.")
	cmd.Flags().StringVar(&bodyPreAttachmentName, "pre-attachment-name", "", "Required if uploading a file. This is the first step in uploading a file to the content migration.")
	cmd.Flags().StringVar(&bodyPreAttachment, "pre-attachment", "", "Other file upload properties, See [File Upload Documentation](/services/canvas/basics/file.file_uploads)")
	cmd.Flags().StringVar(&bodySettingsFileUrl, "settings-file-url", "", "A URL to download the file from. Must not require authentication.")
	cmd.Flags().StringVar(&bodySettingsContentExportId, "settings-content-export-id", "", "The id of a ContentExport to import.")
	cmd.Flags().StringVar(&bodySettingsSourceCourseId, "settings-source-course-id", "", "The course to copy from for a course copy migration. (required if doing course copy)")
	cmd.Flags().StringVar(&bodySettingsFolderId, "settings-folder-id", "", "The folder to unzip the .zip file into for a zip_file_import.")
	cmd.Flags().BoolVar(&bodySettingsOverwriteQuizzes, "settings-overwrite-quizzes", false, "Whether to overwrite quizzes with the same identifiers between content packages.")
	cmd.Flags().IntVar(&bodySettingsQuestionBankId, "settings-question-bank-id", 0, "The existing question bank ID to import questions into if not specified in the content package.")
	cmd.Flags().StringVar(&bodySettingsQuestionBankName, "settings-question-bank-name", "", "The question bank to import questions into if not specified in the content package, if both bank id and name are set")
	cmd.Flags().IntVar(&bodySettingsInsertIntoModuleId, "settings-insert-into-module-id", 0, "The id of a module in the target course.")
	cmd.Flags().StringVar(&bodySettingsInsertIntoModuleType, "settings-insert-into-module-type", "", "If provided (and +insert_into_module_id+ is supplied), only add objects of the specified type to the module.")
	cmd.Flags().IntVar(&bodySettingsInsertIntoModulePosition, "settings-insert-into-module-position", 0, "The (1-based) position to insert the imported items into the course (if +insert_into_module_id+ is supplied).")
	cmd.Flags().IntVar(&bodySettingsMoveToAssignmentGroupId, "settings-move-to-assignment-group-id", 0, "The id of an assignment group in the target course.")
	cmd.Flags().StringVar(&bodySettingsImporterSkips, "settings-importer-skips", "", "Set of importers to skip, even if otherwise selected by migration settings.")
	cmd.Flags().BoolVar(&bodySettingsImportBlueprintSettings, "settings-import-blueprint-settings", false, "Import the 'use as blueprint course' setting as well as the list of locked items from the source course or package.")
	cmd.Flags().BoolVar(&bodyDateShiftOptionsShiftDates, "date-shift-options-shift-dates", false, "Whether to shift dates in the copied course")
	cmd.Flags().StringVar(&bodyDateShiftOptionsOldStartDate, "date-shift-options-old-start-date", "", "The original start date of the source content/course")
	cmd.Flags().StringVar(&bodyDateShiftOptionsOldEndDate, "date-shift-options-old-end-date", "", "The original end date of the source content/course")
	cmd.Flags().StringVar(&bodyDateShiftOptionsNewStartDate, "date-shift-options-new-start-date", "", "The new start date for the content/course")
	cmd.Flags().StringVar(&bodyDateShiftOptionsNewEndDate, "date-shift-options-new-end-date", "", "The new end date for the source content/course")
	cmd.Flags().IntVar(&bodyDateShiftOptionsDaySubstitutionsX, "date-shift-options-day-substitutions-x", 0, "Move anything scheduled for day 'X' to the specified day.")
	cmd.Flags().BoolVar(&bodyDateShiftOptionsRemoveDates, "date-shift-options-remove-dates", false, "Whether to remove dates in the copied course. Cannot be used in conjunction with shift_dates.")
	cmd.Flags().BoolVar(&bodySelectiveImport, "selective-import", false, "If set, perform a selective import instead of importing all content.")
	cmd.Flags().StringVar(&bodySelect, "select", "", "For +course_copy_importer+ migrations")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
