// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContentSharesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "content-shares",
		Short:       "API for creating, accessing and updating Content Sharing.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newContentSharesAddUsersCmd(flags))
	cmd.AddCommand(newContentSharesCreateCmd(flags))
	cmd.AddCommand(newContentSharesDestroyCmd(flags))
	cmd.AddCommand(newContentSharesIndexCmd(flags))
	cmd.AddCommand(newContentSharesIndex2Cmd(flags))
	cmd.AddCommand(newContentSharesShowCmd(flags))
	cmd.AddCommand(newContentSharesUnreadCountCmd(flags))
	cmd.AddCommand(newContentSharesUpdateCmd(flags))
	return cmd
}
