// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newContentMigrationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "content-migrations",
		Short:       "API for accessing content migrations and migration issues",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newContentMigrationsAssetIdMappingCmd(flags))
	cmd.AddCommand(newContentMigrationsAvailableMigratorsCmd(flags))
	cmd.AddCommand(newContentMigrationsAvailableMigrators2Cmd(flags))
	cmd.AddCommand(newContentMigrationsAvailableMigrators3Cmd(flags))
	cmd.AddCommand(newContentMigrationsAvailableMigrators4Cmd(flags))
	cmd.AddCommand(newContentMigrationsContentListCmd(flags))
	cmd.AddCommand(newContentMigrationsContentList2Cmd(flags))
	cmd.AddCommand(newContentMigrationsContentList3Cmd(flags))
	cmd.AddCommand(newContentMigrationsContentList4Cmd(flags))
	cmd.AddCommand(newContentMigrationsCreateCmd(flags))
	cmd.AddCommand(newContentMigrationsCreate2Cmd(flags))
	cmd.AddCommand(newContentMigrationsCreate3Cmd(flags))
	cmd.AddCommand(newContentMigrationsCreate4Cmd(flags))
	cmd.AddCommand(newContentMigrationsIndexCmd(flags))
	cmd.AddCommand(newContentMigrationsIndex2Cmd(flags))
	cmd.AddCommand(newContentMigrationsIndex3Cmd(flags))
	cmd.AddCommand(newContentMigrationsIndex4Cmd(flags))
	cmd.AddCommand(newContentMigrationsIndex5Cmd(flags))
	cmd.AddCommand(newContentMigrationsIndex6Cmd(flags))
	cmd.AddCommand(newContentMigrationsIndex7Cmd(flags))
	cmd.AddCommand(newContentMigrationsIndex8Cmd(flags))
	cmd.AddCommand(newContentMigrationsShowCmd(flags))
	cmd.AddCommand(newContentMigrationsShow2Cmd(flags))
	cmd.AddCommand(newContentMigrationsShow3Cmd(flags))
	cmd.AddCommand(newContentMigrationsShow4Cmd(flags))
	cmd.AddCommand(newContentMigrationsShow5Cmd(flags))
	cmd.AddCommand(newContentMigrationsShow6Cmd(flags))
	cmd.AddCommand(newContentMigrationsShow7Cmd(flags))
	cmd.AddCommand(newContentMigrationsShow8Cmd(flags))
	cmd.AddCommand(newContentMigrationsUpdateCmd(flags))
	cmd.AddCommand(newContentMigrationsUpdate2Cmd(flags))
	cmd.AddCommand(newContentMigrationsUpdate3Cmd(flags))
	cmd.AddCommand(newContentMigrationsUpdate4Cmd(flags))
	cmd.AddCommand(newContentMigrationsUpdate5Cmd(flags))
	cmd.AddCommand(newContentMigrationsUpdate6Cmd(flags))
	cmd.AddCommand(newContentMigrationsUpdate7Cmd(flags))
	cmd.AddCommand(newContentMigrationsUpdate8Cmd(flags))
	return cmd
}
