// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newConversationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "conversations",
		Short:       "API for creating, accessing and updating user conversations.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newConversationsAddMessageCmd(flags))
	cmd.AddCommand(newConversationsAddRecipientsCmd(flags))
	cmd.AddCommand(newConversationsBatchUpdateCmd(flags))
	cmd.AddCommand(newConversationsBatchesCmd(flags))
	cmd.AddCommand(newConversationsCreateCmd(flags))
	cmd.AddCommand(newConversationsDestroyCmd(flags))
	cmd.AddCommand(newConversationsFindRecipientsCmd(flags))
	cmd.AddCommand(newConversationsIndexCmd(flags))
	cmd.AddCommand(newConversationsMarkAllAsReadCmd(flags))
	cmd.AddCommand(newConversationsRemoveMessagesCmd(flags))
	cmd.AddCommand(newConversationsShowCmd(flags))
	cmd.AddCommand(newConversationsUnreadCountCmd(flags))
	cmd.AddCommand(newConversationsUpdateCmd(flags))
	return cmd
}
