// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newConversationsIndexCmd(flags *rootFlags) *cobra.Command {
	var flagScope string
	var flagFilter string
	var flagFilterMode string
	var flagInterleaveSubmissions bool
	var flagIncludeAllConversationIds bool
	var flagInclude string

	cmd := &cobra.Command{
		Use:         "index",
		Short:       "List conversations",
		Example:     "  canvas-cli conversations index",
		Annotations: map[string]string{"pp:endpoint": "conversations.index", "pp:method": "GET", "pp:path": "/api/v1/conversations", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/conversations"
			params := map[string]string{}
			if flagScope != "" {
				params["scope"] = formatCLIParamValue(flagScope)
			}
			if flagFilter != "" {
				params["filter[]"] = formatCLIParamValue(flagFilter)
			}
			if flagFilterMode != "" {
				params["filter_mode"] = formatCLIParamValue(flagFilterMode)
			}
			if flagInterleaveSubmissions != false {
				params["interleave_submissions"] = formatCLIParamValue(flagInterleaveSubmissions)
			}
			if flagIncludeAllConversationIds != false {
				params["include_all_conversation_ids"] = formatCLIParamValue(flagIncludeAllConversationIds)
			}
			if flagInclude != "" {
				params["include[]"] = formatCLIParamValue(flagInclude)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "conversations", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagScope, "scope", "", "When set, only return conversations of the specified type.")
	cmd.Flags().StringVar(&flagFilter, "filter", "", "When set, only return conversations for the specified courses, groups or users.")
	cmd.Flags().StringVar(&flagFilterMode, "filter-mode", "", "When filter[] contains multiple filters, combine them with this mode")
	cmd.Flags().BoolVar(&flagInterleaveSubmissions, "interleave-submissions", false, "(Obsolete) Submissions are no longer linked to conversations. This parameter is ignored.")
	cmd.Flags().BoolVar(&flagIncludeAllConversationIds, "include-all-conversation-ids", false, "Default is false.")
	cmd.Flags().StringVar(&flagInclude, "include", "", "'participant_avatars':: Optionally include an 'avatar_url' key for each user participating in the conversation 'uuid'")

	return cmd
}
