// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesUsers2Cmd(flags *rootFlags) *cobra.Command {
	var flagSearchTerm string
	var flagSort string
	var flagEnrollmentType string
	var flagEnrollmentRole string
	var flagEnrollmentRoleId string
	var flagSectionIds int
	var flagInclude string
	var flagUserId string
	var flagUserIds int
	var flagEnrollmentState string

	cmd := &cobra.Command{
		Use:         "users-2 <course_id>",
		Short:       "List users in course",
		Example:     "  canvas-pp-cli courses users-2 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "courses.users_2", "pp:method": "GET", "pp:path": "/api/v1/courses/{course_id}/search_users", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/courses/{course_id}/search_users"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[0])
			params := map[string]string{}
			if flagSearchTerm != "" {
				params["search_term"] = formatCLIParamValue(flagSearchTerm)
			}
			if flagSort != "" {
				params["sort"] = formatCLIParamValue(flagSort)
			}
			if flagEnrollmentType != "" {
				params["enrollment_type[]"] = formatCLIParamValue(flagEnrollmentType)
			}
			if flagEnrollmentRole != "" {
				params["enrollment_role"] = formatCLIParamValue(flagEnrollmentRole)
			}
			if flagEnrollmentRoleId != "" {
				params["enrollment_role_id"] = formatCLIParamValue(flagEnrollmentRoleId)
			}
			if flagSectionIds != 0 {
				params["section_ids[]"] = formatCLIParamValue(flagSectionIds)
			}
			if flagInclude != "" {
				params["include[]"] = formatCLIParamValue(flagInclude)
			}
			if flagUserId != "" {
				params["user_id"] = formatCLIParamValue(flagUserId)
			}
			if flagUserIds != 0 {
				params["user_ids[]"] = formatCLIParamValue(flagUserIds)
			}
			if flagEnrollmentState != "" {
				params["enrollment_state[]"] = formatCLIParamValue(flagEnrollmentState)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "courses", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "The partial name or full ID of the users to match and return in the results list.")
	cmd.Flags().StringVar(&flagSort, "sort", "", "When set, sort the results of the search based on the given field. Allowed values: username, last_login, email, sis_id")
	cmd.Flags().StringVar(&flagEnrollmentType, "enrollment-type", "", "When set, only return users where the user is enrolled as this type. 'student_view' implies include[]=test_student.")
	cmd.Flags().StringVar(&flagEnrollmentRole, "enrollment-role", "", "Deprecated When set, only return users enrolled with the specified course-level role.")
	cmd.Flags().StringVar(&flagEnrollmentRoleId, "enrollment-role-id", "", "When set, only return courses where the user is enrolled with the specified course-level role.")
	cmd.Flags().IntVar(&flagSectionIds, "section-ids", 0, "When set, only return users who are enrolled in the given section(s).")
	cmd.Flags().StringVar(&flagInclude, "include", "", "- 'enrollments': Optionally include with each Course the user's current and invited enrollments.")
	cmd.Flags().StringVar(&flagUserId, "user-id", "", "If this parameter is given and it corresponds to a user in the course")
	cmd.Flags().IntVar(&flagUserIds, "user-ids", 0, "If included, the course users set will only include users with IDs specified by the param.")
	cmd.Flags().StringVar(&flagEnrollmentState, "enrollment-state", "", "When set, only return users where the enrollment workflow state is of one of the given types.")

	return cmd
}
