// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCoursesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "courses",
		Short:       "API for accessing course information.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCoursesActivityStreamCmd(flags))
	cmd.AddCommand(newCoursesActivityStreamSummaryCmd(flags))
	cmd.AddCommand(newCoursesApiSettingsCmd(flags))
	cmd.AddCommand(newCoursesBatchUpdateCmd(flags))
	cmd.AddCommand(newCoursesBulkUserProgressCmd(flags))
	cmd.AddCommand(newCoursesContentShareUsersCmd(flags))
	cmd.AddCommand(newCoursesCopyCourseContentCmd(flags))
	cmd.AddCommand(newCoursesCopyCourseStatusCmd(flags))
	cmd.AddCommand(newCoursesCreateCmd(flags))
	cmd.AddCommand(newCoursesCreateFileCmd(flags))
	cmd.AddCommand(newCoursesDestroyCmd(flags))
	cmd.AddCommand(newCoursesDismissMigrationLimitationMsgCmd(flags))
	cmd.AddCommand(newCoursesEffectiveDueDatesCmd(flags))
	cmd.AddCommand(newCoursesIndexCmd(flags))
	cmd.AddCommand(newCoursesPermissionsCmd(flags))
	cmd.AddCommand(newCoursesPreviewHtmlCmd(flags))
	cmd.AddCommand(newCoursesRecentStudentsCmd(flags))
	cmd.AddCommand(newCoursesResetContentCmd(flags))
	cmd.AddCommand(newCoursesRestoreVersionCmd(flags))
	cmd.AddCommand(newCoursesShowCmd(flags))
	cmd.AddCommand(newCoursesShow2Cmd(flags))
	cmd.AddCommand(newCoursesStudentViewStudentCmd(flags))
	cmd.AddCommand(newCoursesStudentsCmd(flags))
	cmd.AddCommand(newCoursesTodoItemsCmd(flags))
	cmd.AddCommand(newCoursesUpdateCmd(flags))
	cmd.AddCommand(newCoursesUpdateSettingsCmd(flags))
	cmd.AddCommand(newCoursesUserCmd(flags))
	cmd.AddCommand(newCoursesUserIndexCmd(flags))
	cmd.AddCommand(newCoursesUserProgressCmd(flags))
	cmd.AddCommand(newCoursesUsersCmd(flags))
	cmd.AddCommand(newCoursesUsers2Cmd(flags))
	return cmd
}
