// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesUpdateSettingsCmd(flags *rootFlags) *cobra.Command {
	var bodyAllowFinalGradeOverride bool
	var bodyAllowStudentDiscussionTopics bool
	var bodyAllowStudentForumAttachments bool
	var bodyAllowStudentDiscussionEditing bool
	var bodyAllowStudentOrganizedGroups bool
	var bodyAllowStudentDiscussionReporting bool
	var bodyAllowStudentAnonymousDiscussionTopics bool
	var bodyFilterSpeedGraderByStudentGroup bool
	var bodyHideFinalGrades bool
	var bodyHideDistributionGraphs bool
	var bodyHideSectionsOnCourseUsersPage bool
	var bodyLockAllAnnouncements bool
	var bodyUsageRightsRequired bool
	var bodyRestrictStudentPastView bool
	var bodyRestrictStudentFutureView bool
	var bodyShowAnnouncementsOnHomePage bool
	var bodyHomePageAnnouncementLimit int
	var bodySyllabusCourseSummary bool
	var bodyDefaultDueTime string
	var bodyConditionalRelease bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-settings <course_id>",
		Short:       "Update course settings",
		Example:     "  canvas-cli courses update-settings 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "courses.update_settings", "pp:method": "PUT", "pp:path": "/api/v1/courses/{course_id}/settings"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/courses/{course_id}/settings"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if cmd.Flags().Changed("allow-final-grade-override") {
					body["allow_final_grade_override"] = bodyAllowFinalGradeOverride
				}
				if cmd.Flags().Changed("allow-student-discussion-topics") {
					body["allow_student_discussion_topics"] = bodyAllowStudentDiscussionTopics
				}
				if cmd.Flags().Changed("allow-student-forum-attachments") {
					body["allow_student_forum_attachments"] = bodyAllowStudentForumAttachments
				}
				if cmd.Flags().Changed("allow-student-discussion-editing") {
					body["allow_student_discussion_editing"] = bodyAllowStudentDiscussionEditing
				}
				if cmd.Flags().Changed("allow-student-organized-groups") {
					body["allow_student_organized_groups"] = bodyAllowStudentOrganizedGroups
				}
				if cmd.Flags().Changed("allow-student-discussion-reporting") {
					body["allow_student_discussion_reporting"] = bodyAllowStudentDiscussionReporting
				}
				if cmd.Flags().Changed("allow-student-anonymous-discussion-topics") {
					body["allow_student_anonymous_discussion_topics"] = bodyAllowStudentAnonymousDiscussionTopics
				}
				if cmd.Flags().Changed("filter-speed-grader-by-student-group") {
					body["filter_speed_grader_by_student_group"] = bodyFilterSpeedGraderByStudentGroup
				}
				if cmd.Flags().Changed("hide-final-grades") {
					body["hide_final_grades"] = bodyHideFinalGrades
				}
				if cmd.Flags().Changed("hide-distribution-graphs") {
					body["hide_distribution_graphs"] = bodyHideDistributionGraphs
				}
				if cmd.Flags().Changed("hide-sections-on-course-users-page") {
					body["hide_sections_on_course_users_page"] = bodyHideSectionsOnCourseUsersPage
				}
				if cmd.Flags().Changed("lock-all-announcements") {
					body["lock_all_announcements"] = bodyLockAllAnnouncements
				}
				if cmd.Flags().Changed("usage-rights-required") {
					body["usage_rights_required"] = bodyUsageRightsRequired
				}
				if cmd.Flags().Changed("restrict-student-past-view") {
					body["restrict_student_past_view"] = bodyRestrictStudentPastView
				}
				if cmd.Flags().Changed("restrict-student-future-view") {
					body["restrict_student_future_view"] = bodyRestrictStudentFutureView
				}
				if cmd.Flags().Changed("show-announcements-on-home-page") {
					body["show_announcements_on_home_page"] = bodyShowAnnouncementsOnHomePage
				}
				if bodyHomePageAnnouncementLimit != 0 {
					body["home_page_announcement_limit"] = bodyHomePageAnnouncementLimit
				}
				if cmd.Flags().Changed("syllabus-course-summary") {
					body["syllabus_course_summary"] = bodySyllabusCourseSummary
				}
				if bodyDefaultDueTime != "" {
					body["default_due_time"] = bodyDefaultDueTime
				}
				if cmd.Flags().Changed("conditional-release") {
					body["conditional_release"] = bodyConditionalRelease
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "courses", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "courses", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "courses",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&bodyAllowFinalGradeOverride, "allow-final-grade-override", false, "Let student final grades for a grading period or the total grades for the course be overridden")
	cmd.Flags().BoolVar(&bodyAllowStudentDiscussionTopics, "allow-student-discussion-topics", false, "Let students create discussion topics")
	cmd.Flags().BoolVar(&bodyAllowStudentForumAttachments, "allow-student-forum-attachments", false, "Let students attach files to discussions")
	cmd.Flags().BoolVar(&bodyAllowStudentDiscussionEditing, "allow-student-discussion-editing", false, "Let students edit or delete their own discussion replies")
	cmd.Flags().BoolVar(&bodyAllowStudentOrganizedGroups, "allow-student-organized-groups", false, "Let students organize their own groups")
	cmd.Flags().BoolVar(&bodyAllowStudentDiscussionReporting, "allow-student-discussion-reporting", false, "Let students report offensive discussion content")
	cmd.Flags().BoolVar(&bodyAllowStudentAnonymousDiscussionTopics, "allow-student-anonymous-discussion-topics", false, "Let students create anonymous discussion topics")
	cmd.Flags().BoolVar(&bodyFilterSpeedGraderByStudentGroup, "filter-speed-grader-by-student-group", false, "Filter SpeedGrader to only the selected student group")
	cmd.Flags().BoolVar(&bodyHideFinalGrades, "hide-final-grades", false, "Hide totals in student grades summary")
	cmd.Flags().BoolVar(&bodyHideDistributionGraphs, "hide-distribution-graphs", false, "Hide grade distribution graphs from students")
	cmd.Flags().BoolVar(&bodyHideSectionsOnCourseUsersPage, "hide-sections-on-course-users-page", false, "Disallow students from viewing students in sections they do not belong to")
	cmd.Flags().BoolVar(&bodyLockAllAnnouncements, "lock-all-announcements", false, "Disable comments on announcements")
	cmd.Flags().BoolVar(&bodyUsageRightsRequired, "usage-rights-required", false, "Copyright and license information must be provided for files before they are published.")
	cmd.Flags().BoolVar(&bodyRestrictStudentPastView, "restrict-student-past-view", false, "Restrict students from viewing courses after end date")
	cmd.Flags().BoolVar(&bodyRestrictStudentFutureView, "restrict-student-future-view", false, "Restrict students from viewing courses before start date")
	cmd.Flags().BoolVar(&bodyShowAnnouncementsOnHomePage, "show-announcements-on-home-page", false, "Show the most recent announcements on the Course home page (if a Wiki, defaults to five announcements")
	cmd.Flags().IntVar(&bodyHomePageAnnouncementLimit, "home-page-announcement-limit", 0, "Limit the number of announcements on the home page if enabled via show_announcements_on_home_page")
	cmd.Flags().BoolVar(&bodySyllabusCourseSummary, "syllabus-course-summary", false, "Show the course summary (list of assignments and calendar events) on the syllabus page. Default is true.")
	cmd.Flags().StringVar(&bodyDefaultDueTime, "default-due-time", "", "Set the default due time for assignments.")
	cmd.Flags().BoolVar(&bodyConditionalRelease, "conditional-release", false, "Enable or disable individual learning paths for students based on assessment")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
