// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newCoursesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyCourseName string
	var bodyCourseCourseCode string
	var bodyCourseStartAt string
	var bodyCourseEndAt string
	var bodyCourseLicense string
	var bodyCourseIsPublic bool
	var bodyCourseIsPublicToAuthUsers bool
	var bodyCoursePublicSyllabus bool
	var bodyCoursePublicSyllabusToAuth bool
	var bodyCoursePublicDescription string
	var bodyCourseAllowStudentWikiEdits bool
	var bodyCourseAllowWikiComments bool
	var bodyCourseAllowStudentForumAttachments bool
	var bodyCourseOpenEnrollment bool
	var bodyCourseSelfEnrollment bool
	var bodyCourseRestrictEnrollmentsToCourseDates bool
	var bodyCourseTermId string
	var bodyCourseSisCourseId string
	var bodyCourseIntegrationId string
	var bodyCourseHideFinalGrades bool
	var bodyCourseApplyAssignmentGroupWeights bool
	var bodyCourseTimeZone string
	var bodyOffer bool
	var bodyEnrollMe bool
	var bodySkipCourseTemplate bool
	var bodyCourseDefaultView string
	var bodyCourseSyllabusBody string
	var bodyCourseGradingStandardId int
	var bodyCourseGradePassbackSetting string
	var bodyCourseCourseFormat string
	var bodyCoursePostManually bool
	var bodyEnableSisReactivation bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <account_id>",
		Short:       "Create a new course",
		Example:     "  canvas-cli courses create 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "courses.create", "pp:method": "POST", "pp:path": "/api/v1/accounts/{account_id}/courses"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{account_id}/courses"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCourseName != "" {
					body["course[name]"] = bodyCourseName
				}
				if bodyCourseCourseCode != "" {
					body["course[course_code]"] = bodyCourseCourseCode
				}
				if bodyCourseStartAt != "" {
					body["course[start_at]"] = bodyCourseStartAt
				}
				if bodyCourseEndAt != "" {
					body["course[end_at]"] = bodyCourseEndAt
				}
				if bodyCourseLicense != "" {
					body["course[license]"] = bodyCourseLicense
				}
				if cmd.Flags().Changed("course-is-public") {
					body["course[is_public]"] = bodyCourseIsPublic
				}
				if cmd.Flags().Changed("course-is-public-to-auth-users") {
					body["course[is_public_to_auth_users]"] = bodyCourseIsPublicToAuthUsers
				}
				if cmd.Flags().Changed("course-public-syllabus") {
					body["course[public_syllabus]"] = bodyCoursePublicSyllabus
				}
				if cmd.Flags().Changed("course-public-syllabus-to-auth") {
					body["course[public_syllabus_to_auth]"] = bodyCoursePublicSyllabusToAuth
				}
				if bodyCoursePublicDescription != "" {
					body["course[public_description]"] = bodyCoursePublicDescription
				}
				if cmd.Flags().Changed("course-allow-student-wiki-edits") {
					body["course[allow_student_wiki_edits]"] = bodyCourseAllowStudentWikiEdits
				}
				if cmd.Flags().Changed("course-allow-wiki-comments") {
					body["course[allow_wiki_comments]"] = bodyCourseAllowWikiComments
				}
				if cmd.Flags().Changed("course-allow-student-forum-attachments") {
					body["course[allow_student_forum_attachments]"] = bodyCourseAllowStudentForumAttachments
				}
				if cmd.Flags().Changed("course-open-enrollment") {
					body["course[open_enrollment]"] = bodyCourseOpenEnrollment
				}
				if cmd.Flags().Changed("course-self-enrollment") {
					body["course[self_enrollment]"] = bodyCourseSelfEnrollment
				}
				if cmd.Flags().Changed("course-restrict-enrollments-to-course-dates") {
					body["course[restrict_enrollments_to_course_dates]"] = bodyCourseRestrictEnrollmentsToCourseDates
				}
				if bodyCourseTermId != "" {
					body["course[term_id]"] = bodyCourseTermId
				}
				if bodyCourseSisCourseId != "" {
					body["course[sis_course_id]"] = bodyCourseSisCourseId
				}
				if bodyCourseIntegrationId != "" {
					body["course[integration_id]"] = bodyCourseIntegrationId
				}
				if cmd.Flags().Changed("course-hide-final-grades") {
					body["course[hide_final_grades]"] = bodyCourseHideFinalGrades
				}
				if cmd.Flags().Changed("course-apply-assignment-group-weights") {
					body["course[apply_assignment_group_weights]"] = bodyCourseApplyAssignmentGroupWeights
				}
				if bodyCourseTimeZone != "" {
					body["course[time_zone]"] = bodyCourseTimeZone
				}
				if cmd.Flags().Changed("offer") {
					body["offer"] = bodyOffer
				}
				if cmd.Flags().Changed("enroll-me") {
					body["enroll_me"] = bodyEnrollMe
				}
				if cmd.Flags().Changed("skip-course-template") {
					body["skip_course_template"] = bodySkipCourseTemplate
				}
				if bodyCourseDefaultView != "" {
					body["course[default_view]"] = bodyCourseDefaultView
				}
				if bodyCourseSyllabusBody != "" {
					body["course[syllabus_body]"] = bodyCourseSyllabusBody
				}
				if bodyCourseGradingStandardId != 0 {
					body["course[grading_standard_id]"] = bodyCourseGradingStandardId
				}
				if bodyCourseGradePassbackSetting != "" {
					body["course[grade_passback_setting]"] = bodyCourseGradePassbackSetting
				}
				if bodyCourseCourseFormat != "" {
					body["course[course_format]"] = bodyCourseCourseFormat
				}
				if cmd.Flags().Changed("course-post-manually") {
					body["course[post_manually]"] = bodyCoursePostManually
				}
				if cmd.Flags().Changed("enable-sis-reactivation") {
					body["enable_sis_reactivation"] = bodyEnableSisReactivation
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "courses", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "courses", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "courses",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "courses", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyCourseName, "course-name", "", "The name of the course. If omitted, the course will be named 'Unnamed Course.'")
	cmd.Flags().StringVar(&bodyCourseCourseCode, "course-course-code", "", "The course code for the course.")
	cmd.Flags().StringVar(&bodyCourseStartAt, "course-start-at", "", "Course start date in ISO8601 format, e.g.")
	cmd.Flags().StringVar(&bodyCourseEndAt, "course-end-at", "", "Course end date in ISO8601 format. e.g.")
	cmd.Flags().StringVar(&bodyCourseLicense, "course-license", "", "The name of the licensing.")
	cmd.Flags().BoolVar(&bodyCourseIsPublic, "course-is-public", false, "Set to true if course is public to both authenticated and unauthenticated users.")
	cmd.Flags().BoolVar(&bodyCourseIsPublicToAuthUsers, "course-is-public-to-auth-users", false, "Set to true if course is public only to authenticated users.")
	cmd.Flags().BoolVar(&bodyCoursePublicSyllabus, "course-public-syllabus", false, "Set to true to make the course syllabus public.")
	cmd.Flags().BoolVar(&bodyCoursePublicSyllabusToAuth, "course-public-syllabus-to-auth", false, "Set to true to make the course syllabus public for authenticated users.")
	cmd.Flags().StringVar(&bodyCoursePublicDescription, "course-public-description", "", "A publicly visible description of the course.")
	cmd.Flags().BoolVar(&bodyCourseAllowStudentWikiEdits, "course-allow-student-wiki-edits", false, "If true, students will be able to modify the course wiki.")
	cmd.Flags().BoolVar(&bodyCourseAllowWikiComments, "course-allow-wiki-comments", false, "If true, course members will be able to comment on wiki pages.")
	cmd.Flags().BoolVar(&bodyCourseAllowStudentForumAttachments, "course-allow-student-forum-attachments", false, "If true, students can attach files to forum posts.")
	cmd.Flags().BoolVar(&bodyCourseOpenEnrollment, "course-open-enrollment", false, "Set to true if the course is open enrollment.")
	cmd.Flags().BoolVar(&bodyCourseSelfEnrollment, "course-self-enrollment", false, "Set to true if the course is self enrollment.")
	cmd.Flags().BoolVar(&bodyCourseRestrictEnrollmentsToCourseDates, "course-restrict-enrollments-to-course-dates", false, "Set to true to restrict user enrollments to the start and end dates of the course.")
	cmd.Flags().StringVar(&bodyCourseTermId, "course-term-id", "", "The unique ID of the term to create to course in.")
	cmd.Flags().StringVar(&bodyCourseSisCourseId, "course-sis-course-id", "", "The unique SIS identifier.")
	cmd.Flags().StringVar(&bodyCourseIntegrationId, "course-integration-id", "", "The unique Integration identifier.")
	cmd.Flags().BoolVar(&bodyCourseHideFinalGrades, "course-hide-final-grades", false, "If this option is set to true, the totals in student grades summary will be hidden.")
	cmd.Flags().BoolVar(&bodyCourseApplyAssignmentGroupWeights, "course-apply-assignment-group-weights", false, "Set to true to weight final grade based on assignment groups percentages.")
	cmd.Flags().StringVar(&bodyCourseTimeZone, "course-time-zone", "", "The time zone for the course. Allowed time zones are IANA time zones or friendlier Ruby on Rails time zones.")
	cmd.Flags().BoolVar(&bodyOffer, "offer", false, "If this option is set to true, the course will be available to students immediately.")
	cmd.Flags().BoolVar(&bodyEnrollMe, "enroll-me", false, "Set to true to enroll the current user as the teacher.")
	cmd.Flags().BoolVar(&bodySkipCourseTemplate, "skip-course-template", false, "If this option is set to true")
	cmd.Flags().StringVar(&bodyCourseDefaultView, "course-default-view", "", "The type of page that users will see when they first visit the course * 'feed' Recent Activity Dashboard * 'modules'")
	cmd.Flags().StringVar(&bodyCourseSyllabusBody, "course-syllabus-body", "", "The syllabus body for the course")
	cmd.Flags().IntVar(&bodyCourseGradingStandardId, "course-grading-standard-id", 0, "The grading standard id to set for the course.")
	cmd.Flags().StringVar(&bodyCourseGradePassbackSetting, "course-grade-passback-setting", "", "Optional. The grade_passback_setting for the course. Only 'nightly_sync', 'disabled', and '' are allowed")
	cmd.Flags().StringVar(&bodyCourseCourseFormat, "course-course-format", "", "Optional. Specifies the format of the course. (Should be 'on_campus', 'online', or 'blended')")
	cmd.Flags().BoolVar(&bodyCoursePostManually, "course-post-manually", false, "Default is false. When true, all grades in the course must be posted manually, and will not be automatically posted.")
	cmd.Flags().BoolVar(&bodyEnableSisReactivation, "enable-sis-reactivation", false, "When true, will first try to re-activate a deleted course with matching sis_course_id if possible.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
