// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCustomGradebookColumnsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "custom-gradebook-columns",
		Short:       "API for adding additional columns to the gradebook.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCustomGradebookColumnsBulkUpdateCmd(flags))
	cmd.AddCommand(newCustomGradebookColumnsCreateCmd(flags))
	cmd.AddCommand(newCustomGradebookColumnsDestroyCmd(flags))
	cmd.AddCommand(newCustomGradebookColumnsIndexCmd(flags))
	cmd.AddCommand(newCustomGradebookColumnsIndex2Cmd(flags))
	cmd.AddCommand(newCustomGradebookColumnsReorderCmd(flags))
	cmd.AddCommand(newCustomGradebookColumnsUpdateCmd(flags))
	cmd.AddCommand(newCustomGradebookColumnsUpdate2Cmd(flags))
	return cmd
}
