// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDeveloperKeysCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "developer-keys",
		Short:       "Manage Canvas API Keys, used for OAuth access to this API. See [the OAuth access docs](/services/canvas/oauth2/file.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDeveloperKeysCreateCmd(flags))
	cmd.AddCommand(newDeveloperKeysDestroyCmd(flags))
	cmd.AddCommand(newDeveloperKeysIndexCmd(flags))
	cmd.AddCommand(newDeveloperKeysRegenerateSecretCmd(flags))
	cmd.AddCommand(newDeveloperKeysUpdateCmd(flags))
	return cmd
}
