// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newDiscussionTopicsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyTitle string
	var bodyMessage string
	var bodyDiscussionType string
	var bodyPublished bool
	var bodyDelayedPostAt string
	var bodyLockAt string
	var bodyPodcastEnabled bool
	var bodyPodcastHasStudentPosts bool
	var bodyRequireInitialPost bool
	var bodyAssignment string
	var bodyIsAnnouncement bool
	var bodyPinned bool
	var bodyPositionAfter string
	var bodyGroupCategoryId string
	var bodyAllowRating bool
	var bodyOnlyGradersCanRate bool
	var bodySortOrder string
	var bodySortOrderLocked bool
	var bodyExpanded bool
	var bodyExpandedLocked bool
	var bodySortByRating bool
	var bodySpecificSections string
	var bodyLockComment bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update <course_id> <topic_id>",
		Short:       "Update a topic",
		Example:     "  canvas-pp-cli discussion_topics update 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "discussion_topics.update", "pp:method": "PUT", "pp:path": "/api/v1/courses/{course_id}/discussion_topics/{topic_id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/courses/{course_id}/discussion_topics/{topic_id}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("topic_id is required\nUsage: %s <%s>", cmd.CommandPath(), "topic_id"))
			}
			path = replacePathParam(path, "topic_id", args[1])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyTitle != "" {
					body["title"] = bodyTitle
				}
				if bodyMessage != "" {
					body["message"] = bodyMessage
				}
				if bodyDiscussionType != "" {
					body["discussion_type"] = bodyDiscussionType
				}
				if cmd.Flags().Changed("published") {
					body["published"] = bodyPublished
				}
				if bodyDelayedPostAt != "" {
					body["delayed_post_at"] = bodyDelayedPostAt
				}
				if bodyLockAt != "" {
					body["lock_at"] = bodyLockAt
				}
				if cmd.Flags().Changed("podcast-enabled") {
					body["podcast_enabled"] = bodyPodcastEnabled
				}
				if cmd.Flags().Changed("podcast-has-student-posts") {
					body["podcast_has_student_posts"] = bodyPodcastHasStudentPosts
				}
				if cmd.Flags().Changed("require-initial-post") {
					body["require_initial_post"] = bodyRequireInitialPost
				}
				if bodyAssignment != "" {
					body["assignment"] = bodyAssignment
				}
				if cmd.Flags().Changed("is-announcement") {
					body["is_announcement"] = bodyIsAnnouncement
				}
				if cmd.Flags().Changed("pinned") {
					body["pinned"] = bodyPinned
				}
				if bodyPositionAfter != "" {
					body["position_after"] = bodyPositionAfter
				}
				if bodyGroupCategoryId != "" {
					body["group_category_id"] = bodyGroupCategoryId
				}
				if cmd.Flags().Changed("allow-rating") {
					body["allow_rating"] = bodyAllowRating
				}
				if cmd.Flags().Changed("only-graders-can-rate") {
					body["only_graders_can_rate"] = bodyOnlyGradersCanRate
				}
				if bodySortOrder != "" {
					body["sort_order"] = bodySortOrder
				}
				if cmd.Flags().Changed("sort-order-locked") {
					body["sort_order_locked"] = bodySortOrderLocked
				}
				if cmd.Flags().Changed("expanded") {
					body["expanded"] = bodyExpanded
				}
				if cmd.Flags().Changed("expanded-locked") {
					body["expanded_locked"] = bodyExpandedLocked
				}
				if cmd.Flags().Changed("sort-by-rating") {
					body["sort_by_rating"] = bodySortByRating
				}
				if bodySpecificSections != "" {
					body["specific_sections"] = bodySpecificSections
				}
				if cmd.Flags().Changed("lock-comment") {
					body["lock_comment"] = bodyLockComment
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "discussion_topics", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "discussion_topics", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discussion_topics", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discussion_topics", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discussion_topics", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "discussion_topics",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discussion_topics", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discussion_topics", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyTitle, "title", "", "no description")
	cmd.Flags().StringVar(&bodyMessage, "message", "", "no description")
	cmd.Flags().StringVar(&bodyDiscussionType, "discussion-type", "", "The type of discussion. Defaults to side_comment or not_threaded if not value is given.")
	cmd.Flags().BoolVar(&bodyPublished, "published", false, "Whether this topic is published (true) or draft state (false).")
	cmd.Flags().StringVar(&bodyDelayedPostAt, "delayed-post-at", "", "If a timestamp is given, the topic will not be published until that time.")
	cmd.Flags().StringVar(&bodyLockAt, "lock-at", "", "If a timestamp is given, the topic will be scheduled to lock at the provided timestamp.")
	cmd.Flags().BoolVar(&bodyPodcastEnabled, "podcast-enabled", false, "If true, the topic will have an associated podcast feed.")
	cmd.Flags().BoolVar(&bodyPodcastHasStudentPosts, "podcast-has-student-posts", false, "If true, the podcast will include posts from students as well. Implies podcast_enabled.")
	cmd.Flags().BoolVar(&bodyRequireInitialPost, "require-initial-post", false, "If true then a user may not respond to other replies until that user has made an initial reply. Defaults to false.")
	cmd.Flags().StringVar(&bodyAssignment, "assignment", "", "To create an assignment discussion, pass the assignment parameters as a sub-object.")
	cmd.Flags().BoolVar(&bodyIsAnnouncement, "is-announcement", false, "If true, this topic is an announcement.")
	cmd.Flags().BoolVar(&bodyPinned, "pinned", false, "If true, this topic will be listed in the 'Pinned Discussion' section")
	cmd.Flags().StringVar(&bodyPositionAfter, "position-after", "", "By default, discussions are sorted chronologically by creation date")
	cmd.Flags().StringVar(&bodyGroupCategoryId, "group-category-id", "", "If present, the topic will become a group discussion assigned to the group.")
	cmd.Flags().BoolVar(&bodyAllowRating, "allow-rating", false, "If true, users will be allowed to rate entries.")
	cmd.Flags().BoolVar(&bodyOnlyGradersCanRate, "only-graders-can-rate", false, "If true, only graders will be allowed to rate entries.")
	cmd.Flags().StringVar(&bodySortOrder, "sort-order", "", "Default sort order of the discussion. Accepted values are 'asc', 'desc'. Allowed values: asc, desc")
	cmd.Flags().BoolVar(&bodySortOrderLocked, "sort-order-locked", false, "If true, users cannot choose their prefered sort order")
	cmd.Flags().BoolVar(&bodyExpanded, "expanded", false, "If true, thread will be expanded by default")
	cmd.Flags().BoolVar(&bodyExpandedLocked, "expanded-locked", false, "If true, users cannot choose their prefered thread expansion setting")
	cmd.Flags().BoolVar(&bodySortByRating, "sort-by-rating", false, "(DEPRECATED) If true, entries will be sorted by rating.")
	cmd.Flags().StringVar(&bodySpecificSections, "specific-sections", "", "A comma-separated list of sections ids to which the discussion topic should be made specific too.")
	cmd.Flags().BoolVar(&bodyLockComment, "lock-comment", false, "If is_announcement and lock_comment are true, ‘Allow Participants to Comment’ setting is disabled.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
