// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDiscoveryPagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "discovery-pages",
		Short:       "// Configuration for the login discovery page",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDiscoveryPagesShowCmd(flags))
	cmd.AddCommand(newDiscoveryPagesTokenCmd(flags))
	cmd.AddCommand(newDiscoveryPagesUpsertCmd(flags))
	return cmd
}
