// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDiscussionTopicsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "discussion-topics",
		Short:       "API for accessing and participating in discussion topics in groups and courses.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDiscussionTopicsAddEntryCmd(flags))
	cmd.AddCommand(newDiscussionTopicsAddEntry2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsAddReplyCmd(flags))
	cmd.AddCommand(newDiscussionTopicsAddReply2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsCreateCmd(flags))
	cmd.AddCommand(newDiscussionTopicsCreate2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsDestroyCmd(flags))
	cmd.AddCommand(newDiscussionTopicsDestroy2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsDestroy3Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsDestroy4Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsDisableSummaryCmd(flags))
	cmd.AddCommand(newDiscussionTopicsDisableSummary2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsDuplicateCmd(flags))
	cmd.AddCommand(newDiscussionTopicsDuplicate2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsEntriesCmd(flags))
	cmd.AddCommand(newDiscussionTopicsEntries2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsEntryListCmd(flags))
	cmd.AddCommand(newDiscussionTopicsEntryList2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsFindOrCreateSummaryCmd(flags))
	cmd.AddCommand(newDiscussionTopicsFindOrCreateSummary2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsFindSummaryCmd(flags))
	cmd.AddCommand(newDiscussionTopicsFindSummary2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsIndexCmd(flags))
	cmd.AddCommand(newDiscussionTopicsIndex2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkAllReadCmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkAllRead2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkAllTopicReadCmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkAllTopicRead2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkAllUnreadCmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkAllUnread2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkEntryReadCmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkEntryRead2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkEntryUnreadCmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkEntryUnread2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkTopicReadCmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkTopicRead2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkTopicUnreadCmd(flags))
	cmd.AddCommand(newDiscussionTopicsMarkTopicUnread2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsRateEntryCmd(flags))
	cmd.AddCommand(newDiscussionTopicsRateEntry2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsReorderCmd(flags))
	cmd.AddCommand(newDiscussionTopicsReorder2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsRepliesCmd(flags))
	cmd.AddCommand(newDiscussionTopicsReplies2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsShowCmd(flags))
	cmd.AddCommand(newDiscussionTopicsShow2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsSubscribeTopicCmd(flags))
	cmd.AddCommand(newDiscussionTopicsSubscribeTopic2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsSummaryFeedbackCmd(flags))
	cmd.AddCommand(newDiscussionTopicsSummaryFeedback2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsUnsubscribeTopicCmd(flags))
	cmd.AddCommand(newDiscussionTopicsUnsubscribeTopic2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsUpdateCmd(flags))
	cmd.AddCommand(newDiscussionTopicsUpdate2Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsUpdate3Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsUpdate4Cmd(flags))
	cmd.AddCommand(newDiscussionTopicsViewCmd(flags))
	cmd.AddCommand(newDiscussionTopicsView2Cmd(flags))
	return cmd
}
