// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newDiscoveryPagesUpsertCmd(flags *rootFlags) *cobra.Command {
	var bodyDiscoveryPagePrimaryAuthenticationProviderId int
	var bodyDiscoveryPagePrimaryLabel string
	var bodyDiscoveryPagePrimaryIcon string
	var bodyDiscoveryPageSecondaryAuthenticationProviderId int
	var bodyDiscoveryPageSecondaryLabel string
	var bodyDiscoveryPageSecondaryIcon string
	var bodyDiscoveryPageActive bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "upsert",
		Short: "Update Discovery Page",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  canvas-pp-cli discovery_pages upsert --discovery-page-primary-label example-value",
		Annotations: map[string]string{"pp:endpoint": "discovery_pages.upsert", "pp:method": "PUT", "pp:path": "/api/v1/discovery_pages"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("discovery-page-primary-authentication-provider-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "discovery-page-primary-authentication-provider-id")
				}
				if !cmd.Flags().Changed("discovery-page-primary-label") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "discovery-page-primary-label")
				}
				if !cmd.Flags().Changed("discovery-page-secondary-authentication-provider-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "discovery-page-secondary-authentication-provider-id")
				}
				if !cmd.Flags().Changed("discovery-page-secondary-label") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "discovery-page-secondary-label")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/discovery_pages"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyDiscoveryPagePrimaryAuthenticationProviderId != 0 {
					body["discovery_page[primary][][authentication_provider_id]"] = bodyDiscoveryPagePrimaryAuthenticationProviderId
				}
				if bodyDiscoveryPagePrimaryLabel != "" {
					body["discovery_page[primary][][label]"] = bodyDiscoveryPagePrimaryLabel
				}
				if bodyDiscoveryPagePrimaryIcon != "" {
					body["discovery_page[primary][][icon]"] = bodyDiscoveryPagePrimaryIcon
				}
				if bodyDiscoveryPageSecondaryAuthenticationProviderId != 0 {
					body["discovery_page[secondary][][authentication_provider_id]"] = bodyDiscoveryPageSecondaryAuthenticationProviderId
				}
				if bodyDiscoveryPageSecondaryLabel != "" {
					body["discovery_page[secondary][][label]"] = bodyDiscoveryPageSecondaryLabel
				}
				if bodyDiscoveryPageSecondaryIcon != "" {
					body["discovery_page[secondary][][icon]"] = bodyDiscoveryPageSecondaryIcon
				}
				if cmd.Flags().Changed("discovery-page-active") {
					body["discovery_page[active]"] = bodyDiscoveryPageActive
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "discovery_pages", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "discovery_pages", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discovery_pages", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discovery_pages", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discovery_pages", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "discovery_pages",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discovery_pages", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "discovery_pages", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().IntVar(&bodyDiscoveryPagePrimaryAuthenticationProviderId, "discovery-page-primary-authentication-provider-id", 0, "The ID of an active authentication provider for this account.")
	cmd.Flags().StringVar(&bodyDiscoveryPagePrimaryLabel, "discovery-page-primary-label", "", "The display label for this authentication provider button.")
	cmd.Flags().StringVar(&bodyDiscoveryPagePrimaryIcon, "discovery-page-primary-icon", "", "Icon key for this authentication provider button.")
	cmd.Flags().IntVar(&bodyDiscoveryPageSecondaryAuthenticationProviderId, "discovery-page-secondary-authentication-provider-id", 0, "The ID of an active authentication provider for this account.")
	cmd.Flags().StringVar(&bodyDiscoveryPageSecondaryLabel, "discovery-page-secondary-label", "", "The display label for this authentication provider button.")
	cmd.Flags().StringVar(&bodyDiscoveryPageSecondaryIcon, "discovery-page-secondary-icon", "", "Icon key for this authentication provider button.")
	cmd.Flags().BoolVar(&bodyDiscoveryPageActive, "discovery-page-active", false, "Whether the discovery page is enabled. Defaults to false if not provided.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
