// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEnrollmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "enrollments",
		Short:       "API for creating and viewing course enrollments",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEnrollmentsAcceptCmd(flags))
	cmd.AddCommand(newEnrollmentsBulkEnrollmentCmd(flags))
	cmd.AddCommand(newEnrollmentsBulkTemporaryEnrollmentStatusCmd(flags))
	cmd.AddCommand(newEnrollmentsCreateCmd(flags))
	cmd.AddCommand(newEnrollmentsCreate2Cmd(flags))
	cmd.AddCommand(newEnrollmentsDestroyCmd(flags))
	cmd.AddCommand(newEnrollmentsIndexCmd(flags))
	cmd.AddCommand(newEnrollmentsIndex2Cmd(flags))
	cmd.AddCommand(newEnrollmentsIndex3Cmd(flags))
	cmd.AddCommand(newEnrollmentsLastAttendedCmd(flags))
	cmd.AddCommand(newEnrollmentsReactivateCmd(flags))
	cmd.AddCommand(newEnrollmentsRejectCmd(flags))
	cmd.AddCommand(newEnrollmentsShowCmd(flags))
	cmd.AddCommand(newEnrollmentsShowTemporaryEnrollmentStatusCmd(flags))
	return cmd
}
