// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newEnrollmentsCreate2Cmd(flags *rootFlags) *cobra.Command {
	var bodyEnrollmentStartAt string
	var bodyEnrollmentEndAt string
	var bodyEnrollmentUserId string
	var bodyEnrollmentType string
	var bodyEnrollmentRole string
	var bodyEnrollmentRoleId int
	var bodyEnrollmentEnrollmentState string
	var bodyEnrollmentCourseSectionId int
	var bodyEnrollmentLimitPrivilegesToCourseSection bool
	var bodyEnrollmentNotify bool
	var bodyEnrollmentSelfEnrollmentCode string
	var bodyEnrollmentSelfEnrolled bool
	var bodyEnrollmentAssociatedUserId int
	var bodyEnrollmentSisUserId string
	var bodyEnrollmentIntegrationId string
	var bodyRootAccount string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create-2 <section_id>",
		Short: "Enroll a user",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  canvas-pp-cli enrollments create-2 550e8400-e29b-41d4-a716-446655440000 --enrollment-user-id example-value",
		Annotations: map[string]string{"pp:endpoint": "enrollments.create_2", "pp:method": "POST", "pp:path": "/api/v1/sections/{section_id}/enrollments"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("enrollment-user-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "enrollment-user-id")
				}
				if !cmd.Flags().Changed("enrollment-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "enrollment-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/sections/{section_id}/enrollments"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("section_id is required\nUsage: %s <%s>", cmd.CommandPath(), "section_id"))
			}
			path = replacePathParam(path, "section_id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyEnrollmentStartAt != "" {
					body["enrollment[start_at]"] = bodyEnrollmentStartAt
				}
				if bodyEnrollmentEndAt != "" {
					body["enrollment[end_at]"] = bodyEnrollmentEndAt
				}
				if bodyEnrollmentUserId != "" {
					body["enrollment[user_id]"] = bodyEnrollmentUserId
				}
				if bodyEnrollmentType != "" {
					body["enrollment[type]"] = bodyEnrollmentType
				}
				if bodyEnrollmentRole != "" {
					body["enrollment[role]"] = bodyEnrollmentRole
				}
				if bodyEnrollmentRoleId != 0 {
					body["enrollment[role_id]"] = bodyEnrollmentRoleId
				}
				if bodyEnrollmentEnrollmentState != "" {
					body["enrollment[enrollment_state]"] = bodyEnrollmentEnrollmentState
				}
				if bodyEnrollmentCourseSectionId != 0 {
					body["enrollment[course_section_id]"] = bodyEnrollmentCourseSectionId
				}
				if cmd.Flags().Changed("enrollment-limit-privileges-to-course-section") {
					body["enrollment[limit_privileges_to_course_section]"] = bodyEnrollmentLimitPrivilegesToCourseSection
				}
				if cmd.Flags().Changed("enrollment-notify") {
					body["enrollment[notify]"] = bodyEnrollmentNotify
				}
				if bodyEnrollmentSelfEnrollmentCode != "" {
					body["enrollment[self_enrollment_code]"] = bodyEnrollmentSelfEnrollmentCode
				}
				if cmd.Flags().Changed("enrollment-self-enrolled") {
					body["enrollment[self_enrolled]"] = bodyEnrollmentSelfEnrolled
				}
				if bodyEnrollmentAssociatedUserId != 0 {
					body["enrollment[associated_user_id]"] = bodyEnrollmentAssociatedUserId
				}
				if bodyEnrollmentSisUserId != "" {
					body["enrollment[sis_user_id]"] = bodyEnrollmentSisUserId
				}
				if bodyEnrollmentIntegrationId != "" {
					body["enrollment[integration_id]"] = bodyEnrollmentIntegrationId
				}
				if bodyRootAccount != "" {
					body["root_account"] = bodyRootAccount
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "enrollments", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "enrollments", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "enrollments", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "enrollments", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "enrollments", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "enrollments",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "enrollments", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "enrollments", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyEnrollmentStartAt, "enrollment-start-at", "", "The start time of the enrollment, in ISO8601 format. e.g. 2012-04-18T23:08:51Z")
	cmd.Flags().StringVar(&bodyEnrollmentEndAt, "enrollment-end-at", "", "The end time of the enrollment, in ISO8601 format. e.g. 2012-04-18T23:08:51Z")
	cmd.Flags().StringVar(&bodyEnrollmentUserId, "enrollment-user-id", "", "The ID of the user to be enrolled in the course.")
	cmd.Flags().StringVar(&bodyEnrollmentType, "enrollment-type", "", "Enroll the user as a student, teacher, TA, observer, or designer.")
	cmd.Flags().StringVar(&bodyEnrollmentRole, "enrollment-role", "", "Assigns a custom course-level role to the user.")
	cmd.Flags().IntVar(&bodyEnrollmentRoleId, "enrollment-role-id", 0, "Assigns a custom course-level role to the user.")
	cmd.Flags().StringVar(&bodyEnrollmentEnrollmentState, "enrollment-enrollment-state", "", "If set to 'active,' student will be immediately enrolled in the course.")
	cmd.Flags().IntVar(&bodyEnrollmentCourseSectionId, "enrollment-course-section-id", 0, "The ID of the course section to enroll the student in.")
	cmd.Flags().BoolVar(&bodyEnrollmentLimitPrivilegesToCourseSection, "enrollment-limit-privileges-to-course-section", false, "If set")
	cmd.Flags().BoolVar(&bodyEnrollmentNotify, "enrollment-notify", false, "If true, a notification will be sent to the enrolled user. Notifications are not sent by default.")
	cmd.Flags().StringVar(&bodyEnrollmentSelfEnrollmentCode, "enrollment-self-enrollment-code", "", "If the current user is not allowed to manage enrollments in this course, but the course allows self-enrollment")
	cmd.Flags().BoolVar(&bodyEnrollmentSelfEnrolled, "enrollment-self-enrolled", false, "If true, marks the enrollment as a self-enrollment, which gives students the ability to drop the course if desired.")
	cmd.Flags().IntVar(&bodyEnrollmentAssociatedUserId, "enrollment-associated-user-id", 0, "For an observer enrollment, the ID of a student to observe.")
	cmd.Flags().StringVar(&bodyEnrollmentSisUserId, "enrollment-sis-user-id", "", "Required if the user is being enrolled from another trusted account.")
	cmd.Flags().StringVar(&bodyEnrollmentIntegrationId, "enrollment-integration-id", "", "Required if the user is being enrolled from another trusted account.")
	cmd.Flags().StringVar(&bodyRootAccount, "root-account", "", "The domain of the account to search for the user.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
