// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEportfoliosCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "eportfolios",
		Short:       "Get, update, and delete eportfolios",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEportfoliosDeleteCmd(flags))
	cmd.AddCommand(newEportfoliosIndexCmd(flags))
	cmd.AddCommand(newEportfoliosModerateCmd(flags))
	cmd.AddCommand(newEportfoliosModerateAllCmd(flags))
	cmd.AddCommand(newEportfoliosPagesCmd(flags))
	cmd.AddCommand(newEportfoliosRestoreCmd(flags))
	cmd.AddCommand(newEportfoliosShowCmd(flags))
	return cmd
}
