// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newExternalToolsIndex2Cmd(flags *rootFlags) *cobra.Command {
	var flagSearchTerm string
	var flagSelectable bool
	var flagIncludeParents bool
	var flagPlacement string

	cmd := &cobra.Command{
		Use:         "index-2 <account_id>",
		Short:       "List external tools",
		Example:     "  canvas-cli external_tools index-2 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "external_tools.index_2", "pp:method": "GET", "pp:path": "/api/v1/accounts/{account_id}/external_tools", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{account_id}/external_tools"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			params := map[string]string{}
			if flagSearchTerm != "" {
				params["search_term"] = formatCLIParamValue(flagSearchTerm)
			}
			if flagSelectable != false {
				params["selectable"] = formatCLIParamValue(flagSelectable)
			}
			if flagIncludeParents != false {
				params["include_parents"] = formatCLIParamValue(flagIncludeParents)
			}
			if flagPlacement != "" {
				params["placement"] = formatCLIParamValue(flagPlacement)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "external_tools", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "The partial name of the tools to match and return.")
	cmd.Flags().BoolVar(&flagSelectable, "selectable", false, "If true, then only tools that are meant to be selectable are returned.")
	cmd.Flags().BoolVar(&flagIncludeParents, "include-parents", false, "If true, then include tools installed in all accounts above the current context")
	cmd.Flags().StringVar(&flagPlacement, "placement", "", "The placement type to filter by.")

	return cmd
}
