// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newExternalToolsCreate2Cmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyName string
	var bodyPrivacyLevel string
	var bodyConsumerKey string
	var bodySharedSecret string
	var bodyDescription string
	var bodyUrl string
	var bodyDomain string
	var bodyIconUrl string
	var bodyText string
	var bodyCustomFieldsFieldName string
	var bodyIsRceFavorite bool
	var bodyPlacementNamePlacementConfigurationKey string
	var bodyConfigType string
	var bodyConfigXml string
	var bodyConfigUrl string
	var bodyNotSelectable bool
	var bodyOauthCompliant bool
	var bodyUnifiedToolId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-2 <account_id>",
		Short:       "Create an external tool",
		Example:     "  canvas-cli external_tools create-2 550e8400-e29b-41d4-a716-446655440000 --client-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "external_tools.create_2", "pp:method": "POST", "pp:path": "/api/v1/accounts/{account_id}/external_tools"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("client-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "client-id")
				}
				if !cmd.Flags().Changed("name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("privacy-level") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "privacy-level")
				}
				if !cmd.Flags().Changed("consumer-key") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "consumer-key")
				}
				if !cmd.Flags().Changed("shared-secret") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "shared-secret")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{account_id}/external_tools"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyClientId != "" {
					body["client_id"] = bodyClientId
				}
				if bodyName != "" {
					body["name"] = bodyName
				}
				if bodyPrivacyLevel != "" {
					body["privacy_level"] = bodyPrivacyLevel
				}
				if bodyConsumerKey != "" {
					body["consumer_key"] = bodyConsumerKey
				}
				if bodySharedSecret != "" {
					body["shared_secret"] = bodySharedSecret
				}
				if bodyDescription != "" {
					body["description"] = bodyDescription
				}
				if bodyUrl != "" {
					body["url"] = bodyUrl
				}
				if bodyDomain != "" {
					body["domain"] = bodyDomain
				}
				if bodyIconUrl != "" {
					body["icon_url"] = bodyIconUrl
				}
				if bodyText != "" {
					body["text"] = bodyText
				}
				if bodyCustomFieldsFieldName != "" {
					body["custom_fields[field_name]"] = bodyCustomFieldsFieldName
				}
				if cmd.Flags().Changed("is-rce-favorite") {
					body["is_rce_favorite"] = bodyIsRceFavorite
				}
				if bodyPlacementNamePlacementConfigurationKey != "" {
					body["<placement_name>[<placement_configuration_key>]"] = bodyPlacementNamePlacementConfigurationKey
				}
				if bodyConfigType != "" {
					body["config_type"] = bodyConfigType
				}
				if bodyConfigXml != "" {
					body["config_xml"] = bodyConfigXml
				}
				if bodyConfigUrl != "" {
					body["config_url"] = bodyConfigUrl
				}
				if cmd.Flags().Changed("not-selectable") {
					body["not_selectable"] = bodyNotSelectable
				}
				if cmd.Flags().Changed("oauth-compliant") {
					body["oauth_compliant"] = bodyOauthCompliant
				}
				if bodyUnifiedToolId != "" {
					body["unified_tool_id"] = bodyUnifiedToolId
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "external_tools", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "external_tools", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "external_tools", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "external_tools", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "external_tools", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "external_tools",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "external_tools", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "external_tools", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "The client id is attached to the developer key. If supplied all other parameters are unnecessary and will be ignored")
	cmd.Flags().StringVar(&bodyName, "name", "", "The name of the tool")
	cmd.Flags().StringVar(&bodyPrivacyLevel, "privacy-level", "", "How much user information to send to the external tool. Allowed values: anonymous, name_only, email_only, public")
	cmd.Flags().StringVar(&bodyConsumerKey, "consumer-key", "", "The consumer key for the external tool")
	cmd.Flags().StringVar(&bodySharedSecret, "shared-secret", "", "The shared secret with the external tool")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "A description of the tool")
	cmd.Flags().StringVar(&bodyUrl, "url", "", "The url to match links against. Either 'url' or 'domain' should be set, not both.")
	cmd.Flags().StringVar(&bodyDomain, "domain", "", "The domain to match links against. Either 'url' or 'domain' should be set, not both.")
	cmd.Flags().StringVar(&bodyIconUrl, "icon-url", "", "The url of the icon to show for this tool")
	cmd.Flags().StringVar(&bodyText, "text", "", "The default text to show for this tool")
	cmd.Flags().StringVar(&bodyCustomFieldsFieldName, "custom-fields-field-name", "", "Custom fields that will be sent to the tool consumer; can be used multiple times")
	cmd.Flags().BoolVar(&bodyIsRceFavorite, "is-rce-favorite", false, "(Deprecated in favor of Mark tool to RCE Favorites and Unmark tool from RCE Favorites)")
	cmd.Flags().StringVar(&bodyPlacementNamePlacementConfigurationKey, "placement-name-placement-configuration-key", "", "Set the value for a specific placement.")
	cmd.Flags().StringVar(&bodyConfigType, "config-type", "", "Configuration can be passed in as Common Cartridge XML instead of using query parameters.")
	cmd.Flags().StringVar(&bodyConfigXml, "config-xml", "", "XML tool configuration, as specified in the Common Cartridge XML specification.")
	cmd.Flags().StringVar(&bodyConfigUrl, "config-url", "", "URL where the server can retrieve an XML tool configuration, as specified in the Common Cartridge XML specification.")
	cmd.Flags().BoolVar(&bodyNotSelectable, "not-selectable", false, "Default: false.")
	cmd.Flags().BoolVar(&bodyOauthCompliant, "oauth-compliant", false, "Default: false, if set to true LTI query params will not be copied to the post body.")
	cmd.Flags().StringVar(&bodyUnifiedToolId, "unified-tool-id", "", "The unique identifier for the tool in LearnPlatform")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
