// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newExternalToolsGenerateSessionlessLaunch2Cmd(flags *rootFlags) *cobra.Command {
	var flagId string
	var flagUrl string
	var flagAssignmentId string
	var flagModuleItemId string
	var flagLaunchType string
	var flagResourceLinkLookupUuid string

	cmd := &cobra.Command{
		Use:         "generate-sessionless-launch-2 <account_id>",
		Short:       "Get a sessionless launch url for an external tool.",
		Example:     "  canvas-pp-cli external_tools generate-sessionless-launch-2 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "external_tools.generate_sessionless_launch_2", "pp:method": "GET", "pp:path": "/api/v1/accounts/{account_id}/external_tools/sessionless_launch", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{account_id}/external_tools/sessionless_launch"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			params := map[string]string{}
			if flagId != "" {
				params["id"] = formatCLIParamValue(flagId)
			}
			if flagUrl != "" {
				params["url"] = formatCLIParamValue(flagUrl)
			}
			if flagAssignmentId != "" {
				params["assignment_id"] = formatCLIParamValue(flagAssignmentId)
			}
			if flagModuleItemId != "" {
				params["module_item_id"] = formatCLIParamValue(flagModuleItemId)
			}
			if flagLaunchType != "" {
				params["launch_type"] = formatCLIParamValue(flagLaunchType)
			}
			if flagResourceLinkLookupUuid != "" {
				params["resource_link_lookup_uuid"] = formatCLIParamValue(flagResourceLinkLookupUuid)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "external_tools", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagId, "id", "", "The external id of the tool to launch.")
	cmd.Flags().StringVar(&flagUrl, "url", "", "The LTI launch url for the external tool.")
	cmd.Flags().StringVar(&flagAssignmentId, "assignment-id", "", "The assignment id for an assignment launch. Required if launch_type is set to 'assessment'.")
	cmd.Flags().StringVar(&flagModuleItemId, "module-item-id", "", "The assignment id for a module item launch. Required if launch_type is set to 'module_item'.")
	cmd.Flags().StringVar(&flagLaunchType, "launch-type", "", "The type of launch to perform on the external tool. Placement names (eg.")
	cmd.Flags().StringVar(&flagResourceLinkLookupUuid, "resource-link-lookup-uuid", "", "The identifier to lookup a resource link.")

	return cmd
}
