// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFavoritesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "favorites",
		Short:       "List, add, delete, and remove favorites",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFavoritesAddFavoriteCourseCmd(flags))
	cmd.AddCommand(newFavoritesAddFavoriteGroupsCmd(flags))
	cmd.AddCommand(newFavoritesListFavoriteCoursesCmd(flags))
	cmd.AddCommand(newFavoritesListFavoriteGroupsCmd(flags))
	cmd.AddCommand(newFavoritesRemoveFavoriteCourseCmd(flags))
	cmd.AddCommand(newFavoritesRemoveFavoriteGroupsCmd(flags))
	cmd.AddCommand(newFavoritesResetCourseFavoritesCmd(flags))
	cmd.AddCommand(newFavoritesResetGroupsFavoritesCmd(flags))
	return cmd
}
