// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFeatureFlagsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "feature-flags",
		Short:       "Manage optional features in Canvas.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFeatureFlagsDeleteCmd(flags))
	cmd.AddCommand(newFeatureFlagsDelete2Cmd(flags))
	cmd.AddCommand(newFeatureFlagsDelete3Cmd(flags))
	cmd.AddCommand(newFeatureFlagsEnabledFeaturesCmd(flags))
	cmd.AddCommand(newFeatureFlagsEnabledFeatures2Cmd(flags))
	cmd.AddCommand(newFeatureFlagsEnabledFeatures3Cmd(flags))
	cmd.AddCommand(newFeatureFlagsEnvironmentCmd(flags))
	cmd.AddCommand(newFeatureFlagsIndexCmd(flags))
	cmd.AddCommand(newFeatureFlagsIndex2Cmd(flags))
	cmd.AddCommand(newFeatureFlagsIndex3Cmd(flags))
	cmd.AddCommand(newFeatureFlagsShowCmd(flags))
	cmd.AddCommand(newFeatureFlagsShow2Cmd(flags))
	cmd.AddCommand(newFeatureFlagsShow3Cmd(flags))
	cmd.AddCommand(newFeatureFlagsUpdateCmd(flags))
	cmd.AddCommand(newFeatureFlagsUpdate2Cmd(flags))
	cmd.AddCommand(newFeatureFlagsUpdate3Cmd(flags))
	return cmd
}
