// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFilesApiIndex2Cmd(flags *rootFlags) *cobra.Command {
	var flagContentTypes string
	var flagExcludeContentTypes string
	var flagSearchTerm string
	var flagInclude string
	var flagOnly string
	var flagSort string
	var flagOrder string

	cmd := &cobra.Command{
		Use:         "api-index-2 <user_id>",
		Short:       "List files",
		Example:     "  canvas-pp-cli files api-index-2 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "files.api_index_2", "pp:method": "GET", "pp:path": "/api/v1/users/{user_id}/files", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/users/{user_id}/files"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("user_id is required\nUsage: %s <%s>", cmd.CommandPath(), "user_id"))
			}
			path = replacePathParam(path, "user_id", args[0])
			params := map[string]string{}
			if flagContentTypes != "" {
				params["content_types[]"] = formatCLIParamValue(flagContentTypes)
			}
			if flagExcludeContentTypes != "" {
				params["exclude_content_types[]"] = formatCLIParamValue(flagExcludeContentTypes)
			}
			if flagSearchTerm != "" {
				params["search_term"] = formatCLIParamValue(flagSearchTerm)
			}
			if flagInclude != "" {
				params["include[]"] = formatCLIParamValue(flagInclude)
			}
			if flagOnly != "" {
				params["only[]"] = formatCLIParamValue(flagOnly)
			}
			if flagSort != "" {
				params["sort"] = formatCLIParamValue(flagSort)
			}
			if flagOrder != "" {
				params["order"] = formatCLIParamValue(flagOrder)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "files", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagContentTypes, "content-types", "", "Filter results by content-type. You can specify type/subtype pairs (e.g., 'image/jpeg'), or simply types (e.g.")
	cmd.Flags().StringVar(&flagExcludeContentTypes, "exclude-content-types", "", "Exclude given content-types from your results. You can specify type/subtype pairs (e.g.")
	cmd.Flags().StringVar(&flagSearchTerm, "search-term", "", "The partial name of the files to match and return.")
	cmd.Flags().StringVar(&flagInclude, "include", "", "Array of additional information to include.")
	cmd.Flags().StringVar(&flagOnly, "only", "", "Array of information to restrict to. Overrides include[] 'names':: only returns file name information")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort results by this field. Defaults to 'name'. Note that sort=user implies include[]=user.")
	cmd.Flags().StringVar(&flagOrder, "order", "", "The sorting order. Defaults to 'asc'. Allowed values: asc, desc")

	return cmd
}
