// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGradingStandardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "grading-standards",
		Short:       "Get, create, update, and delete grading standards",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGradingStandardsContextIndexCmd(flags))
	cmd.AddCommand(newGradingStandardsContextIndex2Cmd(flags))
	cmd.AddCommand(newGradingStandardsContextShowCmd(flags))
	cmd.AddCommand(newGradingStandardsContextShow2Cmd(flags))
	cmd.AddCommand(newGradingStandardsCreateCmd(flags))
	cmd.AddCommand(newGradingStandardsCreate2Cmd(flags))
	cmd.AddCommand(newGradingStandardsDestroyCmd(flags))
	cmd.AddCommand(newGradingStandardsDestroy2Cmd(flags))
	cmd.AddCommand(newGradingStandardsUpdateCmd(flags))
	cmd.AddCommand(newGradingStandardsUpdate2Cmd(flags))
	return cmd
}
