// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGradebookHistoryCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "gradebook-history",
		Short:       "API for accessing the versioned history of student submissions along with their grade changes",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGradebookHistoryDayDetailsCmd(flags))
	cmd.AddCommand(newGradebookHistoryDaysCmd(flags))
	cmd.AddCommand(newGradebookHistoryFeedCmd(flags))
	cmd.AddCommand(newGradebookHistorySubmissionsCmd(flags))
	return cmd
}
