// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGradeChangeLogCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "grade-change-log",
		Short:       "Query audit log of grade change events.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGradeChangeLogForAssignmentCmd(flags))
	cmd.AddCommand(newGradeChangeLogForCourseCmd(flags))
	cmd.AddCommand(newGradeChangeLogForGraderCmd(flags))
	cmd.AddCommand(newGradeChangeLogForStudentCmd(flags))
	cmd.AddCommand(newGradeChangeLogQueryCmd(flags))
	return cmd
}
