// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGradingPeriodsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "grading-periods",
		Short:       "Get, batch, update, and delete grading periods",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGradingPeriodsBatchUpdateCmd(flags))
	cmd.AddCommand(newGradingPeriodsBatchUpdate2Cmd(flags))
	cmd.AddCommand(newGradingPeriodsDestroyCmd(flags))
	cmd.AddCommand(newGradingPeriodsDestroy2Cmd(flags))
	cmd.AddCommand(newGradingPeriodsIndexCmd(flags))
	cmd.AddCommand(newGradingPeriodsIndex2Cmd(flags))
	cmd.AddCommand(newGradingPeriodsShowCmd(flags))
	cmd.AddCommand(newGradingPeriodsUpdateCmd(flags))
	return cmd
}
