// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLiveassessmentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "liveassessments",
		Short:       "Manage live assessment results",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLiveassessmentsGetLiveAssessmentsCmd(flags))
	cmd.AddCommand(newLiveassessmentsGetResultsCmd(flags))
	cmd.AddCommand(newLiveassessmentsPostLiveAssessmentsCmd(flags))
	cmd.AddCommand(newLiveassessmentsPostResultsCmd(flags))
	return cmd
}
