// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLtiContextcontrolsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "lti-contextcontrols",
		Short:       "Configure the availability of an LTI Registration in a specific context. Used by the Canvas Apps page UI.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLtiContextcontrolsDeleteControlsCmd(flags))
	cmd.AddCommand(newLtiContextcontrolsGetControlsCmd(flags))
	cmd.AddCommand(newLtiContextcontrolsGetControls2Cmd(flags))
	cmd.AddCommand(newLtiContextcontrolsPostBulkCmd(flags))
	cmd.AddCommand(newLtiContextcontrolsPostControlsCmd(flags))
	cmd.AddCommand(newLtiContextcontrolsPutControlsCmd(flags))
	return cmd
}
