// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLtiRegistrationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "lti-registrations",
		Short:       "{% hint style='warning' %}",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLtiRegistrationsDeleteBindCmd(flags))
	cmd.AddCommand(newLtiRegistrationsDeleteLtiRegistrationsCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetByUtidCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetContextSearchCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetHistoryCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetInstallStatusCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetLatestUpdateRequestCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetLtiRegistrationByClientIdCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetLtiRegistrationsCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetLtiRegistrations2Cmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetOverlayHistoryCmd(flags))
	cmd.AddCommand(newLtiRegistrationsGetUpdateRequestsCmd(flags))
	cmd.AddCommand(newLtiRegistrationsPostBindCmd(flags))
	cmd.AddCommand(newLtiRegistrationsPostInstallFromTemplateCmd(flags))
	cmd.AddCommand(newLtiRegistrationsPostLtiRegistrationsCmd(flags))
	cmd.AddCommand(newLtiRegistrationsPutApplyCmd(flags))
	cmd.AddCommand(newLtiRegistrationsPutLtiRegistrationsCmd(flags))
	cmd.AddCommand(newLtiRegistrationsPutResetCmd(flags))
	return cmd
}
