// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLtiRegistrationsGetLtiRegistrationsCmd(flags *rootFlags) *cobra.Command {
	var flagPerPage int
	var flagPage string
	var flagSort string
	var flagDir string
	var flagInclude string

	cmd := &cobra.Command{
		Use:         "get-lti-registrations <account_id>",
		Short:       "Returns all LTI registrations in the specified account. Includes registrations created in this account, those set to 'al",
		Example:     "  canvas-cli lti_registrations get-lti-registrations 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "lti_registrations.get_lti_registrations", "pp:method": "GET", "pp:path": "/api/v1/accounts/{account_id}/lti_registrations", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{account_id}/lti_registrations"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			params := map[string]string{}
			if flagPerPage != 0 {
				params["per_page"] = formatCLIParamValue(flagPerPage)
			}
			if flagPage != "" {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagSort != "" {
				params["sort"] = formatCLIParamValue(flagSort)
			}
			if flagDir != "" {
				params["dir"] = formatCLIParamValue(flagDir)
			}
			if flagInclude != "" {
				params["include[]"] = formatCLIParamValue(flagInclude)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "lti_registrations", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagPerPage, "per-page", 0, "The number of registrations to return per page. Defaults to 15.")
	cmd.Flags().StringVar(&flagPage, "page", "", "The page number to return. Defaults to 1.")
	cmd.Flags().StringVar(&flagSort, "sort", "", "The field to sort by. Choices are: name, nickname, lti_version, installed, installed_by, updated_by, updated, and on.")
	cmd.Flags().StringVar(&flagDir, "dir", "", "The order to sort the given column by. Defaults to desc. Allowed values: asc, desc")
	cmd.Flags().StringVar(&flagInclude, "include", "", "Array of additional data to include. Always includes [account_binding].")

	return cmd
}
