// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLtiLaunchDefinitionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "lti-launch-definitions",
		Short:       "// A bare-bones representation of an LTI tool used by Canvas to launch the tool",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLtiLaunchDefinitionsGetLaunchDefinitionsCmd(flags))
	cmd.AddCommand(newLtiLaunchDefinitionsGetLaunchDefinitions2Cmd(flags))
	return cmd
}
