// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newModeratedGradingCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "moderated-grading",
		Short:       "API for viewing and adding students to the list of people in moderation for an assignment",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newModeratedGradingBulkSelectCmd(flags))
	cmd.AddCommand(newModeratedGradingCreateCmd(flags))
	cmd.AddCommand(newModeratedGradingIndexCmd(flags))
	cmd.AddCommand(newModeratedGradingPublishCmd(flags))
	cmd.AddCommand(newModeratedGradingSelectCmd(flags))
	cmd.AddCommand(newModeratedGradingStatusCmd(flags))
	cmd.AddCommand(newModeratedGradingStatus2Cmd(flags))
	return cmd
}
