// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newModulesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "modules",
		Short:       "Modules are collections of learning materials useful for organizing courses and optionally providing a linear flow",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newModulesBulkUpdateCmd(flags))
	cmd.AddCommand(newModulesCreateCmd(flags))
	cmd.AddCommand(newModulesCreate2Cmd(flags))
	cmd.AddCommand(newModulesDestroyCmd(flags))
	cmd.AddCommand(newModulesDestroy2Cmd(flags))
	cmd.AddCommand(newModulesIndexCmd(flags))
	cmd.AddCommand(newModulesIndex2Cmd(flags))
	cmd.AddCommand(newModulesIndex3Cmd(flags))
	cmd.AddCommand(newModulesItemSequenceCmd(flags))
	cmd.AddCommand(newModulesMarkAsDoneCmd(flags))
	cmd.AddCommand(newModulesMarkItemReadCmd(flags))
	cmd.AddCommand(newModulesRelockCmd(flags))
	cmd.AddCommand(newModulesSelectMasteryPathCmd(flags))
	cmd.AddCommand(newModulesShowCmd(flags))
	cmd.AddCommand(newModulesShow2Cmd(flags))
	cmd.AddCommand(newModulesUpdateCmd(flags))
	cmd.AddCommand(newModulesUpdate2Cmd(flags))
	return cmd
}
