// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNotificationPreferencesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "notification-preferences",
		Short:       "API for managing notification preferences",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newNotificationPreferencesCategoryIndexCmd(flags))
	cmd.AddCommand(newNotificationPreferencesIndexCmd(flags))
	cmd.AddCommand(newNotificationPreferencesIndex2Cmd(flags))
	cmd.AddCommand(newNotificationPreferencesShowCmd(flags))
	cmd.AddCommand(newNotificationPreferencesShow2Cmd(flags))
	cmd.AddCommand(newNotificationPreferencesUpdateCmd(flags))
	cmd.AddCommand(newNotificationPreferencesUpdate2Cmd(flags))
	cmd.AddCommand(newNotificationPreferencesUpdateAllCmd(flags))
	cmd.AddCommand(newNotificationPreferencesUpdateAll2Cmd(flags))
	cmd.AddCommand(newNotificationPreferencesUpdatePreferencesByCategoryCmd(flags))
	return cmd
}
