// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOutcomeImportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "outcome-imports",
		Short:       "API for importing outcome data",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOutcomeImportsCreateCmd(flags))
	cmd.AddCommand(newOutcomeImportsCreate2Cmd(flags))
	cmd.AddCommand(newOutcomeImportsCreatedGroupIdsCmd(flags))
	cmd.AddCommand(newOutcomeImportsCreatedGroupIds2Cmd(flags))
	cmd.AddCommand(newOutcomeImportsShowCmd(flags))
	cmd.AddCommand(newOutcomeImportsShow2Cmd(flags))
	return cmd
}
