// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOutcomesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "outcomes",
		Short:       "API for accessing learning outcome information.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOutcomesOutcomeAlignmentsCmd(flags))
	cmd.AddCommand(newOutcomesShowCmd(flags))
	cmd.AddCommand(newOutcomesUpdateCmd(flags))
	return cmd
}
