// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOutcomeGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "outcome-groups",
		Short:       "API for accessing learning outcome group information.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOutcomeGroupsCreateCmd(flags))
	cmd.AddCommand(newOutcomeGroupsCreate2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsCreate3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsDestroyCmd(flags))
	cmd.AddCommand(newOutcomeGroupsDestroy2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsDestroy3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsImportCmd(flags))
	cmd.AddCommand(newOutcomeGroupsImport2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsImport3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsIndexCmd(flags))
	cmd.AddCommand(newOutcomeGroupsIndex2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsLinkCmd(flags))
	cmd.AddCommand(newOutcomeGroupsLink2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsLink3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsLink4Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsLink5Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsLink6Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsLinkIndexCmd(flags))
	cmd.AddCommand(newOutcomeGroupsLinkIndex2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsOutcomesCmd(flags))
	cmd.AddCommand(newOutcomeGroupsOutcomes2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsOutcomes3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsRedirectCmd(flags))
	cmd.AddCommand(newOutcomeGroupsRedirect2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsRedirect3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsShowCmd(flags))
	cmd.AddCommand(newOutcomeGroupsShow2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsShow3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsSubgroupsCmd(flags))
	cmd.AddCommand(newOutcomeGroupsSubgroups2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsSubgroups3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsUnlinkCmd(flags))
	cmd.AddCommand(newOutcomeGroupsUnlink2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsUnlink3Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsUpdateCmd(flags))
	cmd.AddCommand(newOutcomeGroupsUpdate2Cmd(flags))
	cmd.AddCommand(newOutcomeGroupsUpdate3Cmd(flags))
	return cmd
}
