// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "pages",
		Short:       "Pages are rich content associated with Courses and Groups in Canvas.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPagesCreateCmd(flags))
	cmd.AddCommand(newPagesCreate2Cmd(flags))
	cmd.AddCommand(newPagesDestroyCmd(flags))
	cmd.AddCommand(newPagesDestroy2Cmd(flags))
	cmd.AddCommand(newPagesDuplicateCmd(flags))
	cmd.AddCommand(newPagesIndexCmd(flags))
	cmd.AddCommand(newPagesIndex2Cmd(flags))
	cmd.AddCommand(newPagesRevertCmd(flags))
	cmd.AddCommand(newPagesRevert2Cmd(flags))
	cmd.AddCommand(newPagesRevisionsCmd(flags))
	cmd.AddCommand(newPagesRevisions2Cmd(flags))
	cmd.AddCommand(newPagesShowCmd(flags))
	cmd.AddCommand(newPagesShow2Cmd(flags))
	cmd.AddCommand(newPagesShowFrontPageCmd(flags))
	cmd.AddCommand(newPagesShowFrontPage2Cmd(flags))
	cmd.AddCommand(newPagesShowRevisionCmd(flags))
	cmd.AddCommand(newPagesShowRevision2Cmd(flags))
	cmd.AddCommand(newPagesShowRevision3Cmd(flags))
	cmd.AddCommand(newPagesShowRevision4Cmd(flags))
	cmd.AddCommand(newPagesUpdateCmd(flags))
	cmd.AddCommand(newPagesUpdate2Cmd(flags))
	cmd.AddCommand(newPagesUpdateFrontPageCmd(flags))
	cmd.AddCommand(newPagesUpdateFrontPage2Cmd(flags))
	return cmd
}
