// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPeerReviewsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "peer-reviews",
		Short:       "Get, create, and delete peer reviews",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPeerReviewsAllocateCmd(flags))
	cmd.AddCommand(newPeerReviewsCreateCmd(flags))
	cmd.AddCommand(newPeerReviewsCreate2Cmd(flags))
	cmd.AddCommand(newPeerReviewsDestroyCmd(flags))
	cmd.AddCommand(newPeerReviewsDestroy2Cmd(flags))
	cmd.AddCommand(newPeerReviewsIndexCmd(flags))
	cmd.AddCommand(newPeerReviewsIndex2Cmd(flags))
	cmd.AddCommand(newPeerReviewsIndex3Cmd(flags))
	cmd.AddCommand(newPeerReviewsIndex4Cmd(flags))
	return cmd
}
