// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPlannerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "planner",
		Short:       "API for listing learning objects to display on the student planner and calendar",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPlannerCreateCmd(flags))
	cmd.AddCommand(newPlannerCreate2Cmd(flags))
	cmd.AddCommand(newPlannerDestroyCmd(flags))
	cmd.AddCommand(newPlannerDestroy2Cmd(flags))
	cmd.AddCommand(newPlannerIndexCmd(flags))
	cmd.AddCommand(newPlannerIndex2Cmd(flags))
	cmd.AddCommand(newPlannerIndex3Cmd(flags))
	cmd.AddCommand(newPlannerIndex4Cmd(flags))
	cmd.AddCommand(newPlannerShowCmd(flags))
	cmd.AddCommand(newPlannerShow2Cmd(flags))
	cmd.AddCommand(newPlannerUpdateCmd(flags))
	cmd.AddCommand(newPlannerUpdate2Cmd(flags))
	return cmd
}
