// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPollSessionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "poll-sessions",
		Short:       "Get, create, update, and delete poll sessions",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPollSessionsDeletePollSessionsCmd(flags))
	cmd.AddCommand(newPollSessionsGetCloseCmd(flags))
	cmd.AddCommand(newPollSessionsGetClosedCmd(flags))
	cmd.AddCommand(newPollSessionsGetOpenCmd(flags))
	cmd.AddCommand(newPollSessionsGetOpenedCmd(flags))
	cmd.AddCommand(newPollSessionsGetPollSessionsCmd(flags))
	cmd.AddCommand(newPollSessionsGetPollSessions2Cmd(flags))
	cmd.AddCommand(newPollSessionsPostPollSessionsCmd(flags))
	cmd.AddCommand(newPollSessionsPutPollSessionsCmd(flags))
	return cmd
}
