// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPollsubmissionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "pollsubmissions",
		Short:       "Manage submissions for polls",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPollsubmissionsGetPollSubmissionsCmd(flags))
	cmd.AddCommand(newPollsubmissionsPostPollSubmissionsCmd(flags))
	return cmd
}
