// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPollchoicesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "pollchoices",
		Short:       "Manage choices for polls",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPollchoicesDeletePollChoicesCmd(flags))
	cmd.AddCommand(newPollchoicesGetPollChoicesCmd(flags))
	cmd.AddCommand(newPollchoicesGetPollChoices2Cmd(flags))
	cmd.AddCommand(newPollchoicesPostPollChoicesCmd(flags))
	cmd.AddCommand(newPollchoicesPutPollChoicesCmd(flags))
	return cmd
}
