// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProficiencyRatingsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "proficiency-ratings",
		Short:       "API for customizing proficiency ratings",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProficiencyRatingsCreateCmd(flags))
	cmd.AddCommand(newProficiencyRatingsCreate2Cmd(flags))
	cmd.AddCommand(newProficiencyRatingsShowCmd(flags))
	cmd.AddCommand(newProficiencyRatingsShow2Cmd(flags))
	return cmd
}
