// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProgressCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "progress",
		Short:       "API for querying the progress of asynchronous API operations.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProgressCancelCmd(flags))
	cmd.AddCommand(newProgressShowCmd(flags))
	return cmd
}
