// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAnnouncementsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagContextCodes string
	var flagStartDate string
	var flagEndDate string
	var flagAvailableAfter string
	var flagActiveOnly bool
	var flagLatestOnly bool
	var flagInclude string

	cmd := &cobra.Command{
		Use:   "announcements",
		Short: "List announcements",
		Long:  "List announcements",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  canvas-pp-cli announcements --context-codes example-value",
		Annotations: map[string]string{"pp:endpoint": "announcements.index", "pp:method": "GET", "pp:path": "/api/v1/announcements", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("context-codes") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "context-codes")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/announcements"
			params := map[string]string{}
			if flagContextCodes != "" {
				params["context_codes[]"] = formatCLIParamValue(flagContextCodes)
			}
			if flagStartDate != "" {
				params["start_date"] = formatCLIParamValue(flagStartDate)
			}
			if flagEndDate != "" {
				params["end_date"] = formatCLIParamValue(flagEndDate)
			}
			if flagAvailableAfter != "" {
				params["available_after"] = formatCLIParamValue(flagAvailableAfter)
			}
			if flagActiveOnly != false {
				params["active_only"] = formatCLIParamValue(flagActiveOnly)
			}
			if flagLatestOnly != false {
				params["latest_only"] = formatCLIParamValue(flagLatestOnly)
			}
			if flagInclude != "" {
				params["include"] = formatCLIParamValue(flagInclude)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "announcements", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagContextCodes, "context-codes", "", "List of context_codes to retrieve announcements for (for example, +course_123+). Only courses are presently supported.")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Only return announcements posted since the start_date (inclusive). Defaults to 14 days ago.")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Only return announcements posted before the end_date (inclusive). Defaults to 28 days from start_date.")
	cmd.Flags().StringVar(&flagAvailableAfter, "available-after", "", "Only return announcements having locked_at nil or after available_after (exclusive).")
	cmd.Flags().BoolVar(&flagActiveOnly, "active-only", false, "Only return active announcements that have been published.")
	cmd.Flags().BoolVar(&flagLatestOnly, "latest-only", false, "Only return the latest announcement for each associated context.")
	cmd.Flags().StringVar(&flagInclude, "include", "", "Optional list of resources to include with the response. May include a string of the name of the resource.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
