// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAssignmentExtensionsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAssignmentExtensionsUserId int
	var bodyAssignmentExtensionsExtraAttempts int

	cmd := &cobra.Command{
		Use:         "assignment-extensions <course_id> <assignment_id>",
		Short:       "Set extensions for student assignment submissions",
		Long:        "Set extensions for student assignment submissions",
		Example:     "  canvas-cli assignment-extensions 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "assignment_extensions.create", "pp:method": "POST", "pp:path": "/api/v1/courses/{course_id}/assignments/{assignment_id}/extensions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("assignment-extensions-user-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "assignment-extensions-user-id")
			}
			if !cmd.Flags().Changed("assignment-extensions-extra-attempts") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "assignment-extensions-extra-attempts")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/courses/{course_id}/assignments/{assignment_id}/extensions"
			if len(args) < 1 || args[0] == "" {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "course_id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "course_id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[0])
			if len(args) < 2 || args[1] == "" {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "assignment_id is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "assignment_id"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("assignment_id is required\nUsage: %s <%s>", cmd.CommandPath(), "assignment_id"))
			}
			path = replacePathParam(path, "assignment_id", args[1])
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAssignmentExtensionsUserId != 0 {
				body["assignment_extensions[][user_id]"] = bodyAssignmentExtensionsUserId
			}
			if bodyAssignmentExtensionsExtraAttempts != 0 {
				body["assignment_extensions[][extra_attempts]"] = bodyAssignmentExtensionsExtraAttempts
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "assignment_extensions", data, "")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&bodyAssignmentExtensionsUserId, "assignment-extensions-user-id", 0, "The ID of the user we want to add assignment extensions for.")
	cmd.Flags().IntVar(&bodyAssignmentExtensionsExtraAttempts, "assignment-extensions-extra-attempts", 0, "Number of times the student is allowed to re-take the assignment over the limit.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
