// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCommmessagesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagUserId string
	var flagStartTime string
	var flagEndTime string

	cmd := &cobra.Command{
		Use:         "commmessages",
		Short:       "List of CommMessages for a user",
		Long:        "List of CommMessages for a user",
		Example:     "  canvas-pp-cli commmessages --user-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "commmessages.index", "pp:method": "GET", "pp:path": "/api/v1/comm_messages", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("user-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "user-id")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/comm_messages"
			params := map[string]string{}
			if flagUserId != "" {
				params["user_id"] = formatCLIParamValue(flagUserId)
			}
			if flagStartTime != "" {
				params["start_time"] = formatCLIParamValue(flagStartTime)
			}
			if flagEndTime != "" {
				params["end_time"] = formatCLIParamValue(flagEndTime)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "commmessages", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagUserId, "user-id", "", "The user id for whom you want to retrieve CommMessages")
	cmd.Flags().StringVar(&flagStartTime, "start-time", "", "The beginning of the time range you want to retrieve message from. Up to a year prior to the current date is available.")
	cmd.Flags().StringVar(&flagEndTime, "end-time", "", "The end of the time range you want to retrieve messages for. Up to a year prior to the current date is available.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
