// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newErrorReportsPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyErrorSubject string
	var bodyErrorUrl string
	var bodyErrorEmail string
	var bodyErrorComments string
	var bodyErrorHttpEnv string

	cmd := &cobra.Command{
		Use:   "error-reports",
		Short: "Create Error Report",
		Long:  "Create Error Report",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  canvas-cli error-reports --error-subject example-value",
		Annotations: map[string]string{"pp:endpoint": "error_reports.create", "pp:method": "POST", "pp:path": "/api/v1/error_reports"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with a required flag/body prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only reads fall through so a bare call still executes; positional
			// commands keep their existing usageErr (exit 2 + JSON envelope).
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("error-subject") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "error-subject")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/error_reports"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyErrorSubject != "" {
				body["error[subject]"] = bodyErrorSubject
			}
			if bodyErrorUrl != "" {
				body["error[url]"] = bodyErrorUrl
			}
			if bodyErrorEmail != "" {
				body["error[email]"] = bodyErrorEmail
			}
			if bodyErrorComments != "" {
				body["error[comments]"] = bodyErrorComments
			}
			if bodyErrorHttpEnv != "" {
				var parsedErrorHttpEnv any
				if err := json.Unmarshal([]byte(bodyErrorHttpEnv), &parsedErrorHttpEnv); err != nil {
					return fmt.Errorf("parsing --error-http-env JSON: %w", err)
				}
				body["error[http_env]"] = bodyErrorHttpEnv
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			if err != nil {
				return classifyAPIError(err, flags)
			}
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "error_reports", data, "")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyErrorSubject, "error-subject", "", "The summary of the problem")
	cmd.Flags().StringVar(&bodyErrorUrl, "error-url", "", "URL from which the report was issued")
	cmd.Flags().StringVar(&bodyErrorEmail, "error-email", "", "Email address for the reporting user")
	cmd.Flags().StringVar(&bodyErrorComments, "error-comments", "", "The long version of the story from the user one what they experienced")
	cmd.Flags().StringVar(&bodyErrorHttpEnv, "error-http-env", "", "A collection of metadata about the users' environment.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
