// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAccountDomainLookupsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagName string
	var flagDomain string
	var flagLatitude float64
	var flagLongitude float64

	cmd := &cobra.Command{
		Use:         "account-domain-lookups",
		Short:       "Search account domains",
		Long:        "Search account domains",
		Example:     "  canvas-pp-cli account-domain-lookups",
		Annotations: map[string]string{"pp:endpoint": "account_domain_lookups.search", "pp:method": "GET", "pp:path": "/api/v1/accounts/search", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/search"
			params := map[string]string{}
			if flagName != "" {
				params["name"] = formatCLIParamValue(flagName)
			}
			if flagDomain != "" {
				params["domain"] = formatCLIParamValue(flagDomain)
			}
			if flagLatitude != 0.0 {
				params["latitude"] = formatCLIParamValue(flagLatitude)
			}
			if flagLongitude != 0.0 {
				params["longitude"] = formatCLIParamValue(flagLongitude)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "account_domain_lookups", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagName, "name", "", "campus name")
	cmd.Flags().StringVar(&flagDomain, "domain", "", "no description")
	cmd.Flags().Float64Var(&flagLatitude, "latitude", 0.0, "no description")
	cmd.Flags().Float64Var(&flagLongitude, "longitude", 0.0, "no description")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
