// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newQuizSubmissionEventsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "quiz-submission-events",
		Short:       "// An event passed from the Quiz Submission take page",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newQuizSubmissionEventsGetEventsCmd(flags))
	cmd.AddCommand(newQuizSubmissionEventsPostEventsCmd(flags))
	return cmd
}
