// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newQuizSubmissionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "quiz-submissions",
		Short:       "API for accessing quiz submissions",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newQuizSubmissionsGetSubmissionCmd(flags))
	cmd.AddCommand(newQuizSubmissionsGetSubmissionsCmd(flags))
	cmd.AddCommand(newQuizSubmissionsGetSubmissions2Cmd(flags))
	cmd.AddCommand(newQuizSubmissionsGetTimeCmd(flags))
	cmd.AddCommand(newQuizSubmissionsPostCompleteCmd(flags))
	cmd.AddCommand(newQuizSubmissionsPostSubmissionsCmd(flags))
	cmd.AddCommand(newQuizSubmissionsPutSubmissionsCmd(flags))
	return cmd
}
