// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newQuizzesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "quizzes",
		Short:       "Get, create, update, and delete quizzes",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newQuizzesDeleteQuizzesCmd(flags))
	cmd.AddCommand(newQuizzesGetQuizzesCmd(flags))
	cmd.AddCommand(newQuizzesGetQuizzes2Cmd(flags))
	cmd.AddCommand(newQuizzesPostQuizzesCmd(flags))
	cmd.AddCommand(newQuizzesPostReorderCmd(flags))
	cmd.AddCommand(newQuizzesPostValidateAccessCodeCmd(flags))
	cmd.AddCommand(newQuizzesPutQuizzesCmd(flags))
	return cmd
}
