// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newQuizReportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "quiz-reports",
		Short:       "API for accessing and generating statistical reports for a quiz",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newQuizReportsDeleteReportsCmd(flags))
	cmd.AddCommand(newQuizReportsGetReportsCmd(flags))
	cmd.AddCommand(newQuizReportsGetReports2Cmd(flags))
	cmd.AddCommand(newQuizReportsPostReportsCmd(flags))
	return cmd
}
