// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRolesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "roles",
		Short:       "API for managing account- and course-level roles, and their associated permissions.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRolesActivateRoleCmd(flags))
	cmd.AddCommand(newRolesAddRoleCmd(flags))
	cmd.AddCommand(newRolesApiIndexCmd(flags))
	cmd.AddCommand(newRolesGroupsCmd(flags))
	cmd.AddCommand(newRolesHelpCmd(flags))
	cmd.AddCommand(newRolesManageablePermissionsCmd(flags))
	cmd.AddCommand(newRolesRemoveRoleCmd(flags))
	cmd.AddCommand(newRolesShowCmd(flags))
	cmd.AddCommand(newRolesUpdateCmd(flags))
	return cmd
}
