// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"io"
	"testing"
)

// TestNovelRosterHelpWires smoke-tests that the roster command
// resolves at runtime and renders --help without error. Catches wiring
// regressions (missing AddCommand, panicking RunE on --help, etc.) before
// review. Always runs — do not delete this test when filling in real cases.
func TestNovelRosterHelpWires(t *testing.T) {
	cmd := RootCmd()
	cmd.SetArgs([]string{"roster", "--help"})
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	if err := cmd.Execute(); err != nil {
		t.Fatalf("roster --help error = %v (novel command not wired correctly?)", err)
	}
}

// TestNovelRosterBehavior verifies the command resolves and its --dry-run path
// succeeds without dialing the API.
func TestNovelRosterBehavior(t *testing.T) {
	cmd := RootCmd()
	cmd.SetArgs([]string{"roster", "12345", "--dry-run"})
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	if err := cmd.Execute(); err != nil {
		t.Fatalf("roster dry-run should succeed, got %v", err)
	}
}
