// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRubricsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "rubrics",
		Short:       "API for accessing rubric information.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRubricsCreateCmd(flags))
	cmd.AddCommand(newRubricsCreate2Cmd(flags))
	cmd.AddCommand(newRubricsCreate3Cmd(flags))
	cmd.AddCommand(newRubricsDestroyCmd(flags))
	cmd.AddCommand(newRubricsDestroy2Cmd(flags))
	cmd.AddCommand(newRubricsDestroy3Cmd(flags))
	cmd.AddCommand(newRubricsIndexCmd(flags))
	cmd.AddCommand(newRubricsIndex2Cmd(flags))
	cmd.AddCommand(newRubricsShowCmd(flags))
	cmd.AddCommand(newRubricsShow2Cmd(flags))
	cmd.AddCommand(newRubricsUpdateCmd(flags))
	cmd.AddCommand(newRubricsUpdate2Cmd(flags))
	cmd.AddCommand(newRubricsUpdate3Cmd(flags))
	cmd.AddCommand(newRubricsUploadCmd(flags))
	cmd.AddCommand(newRubricsUpload2Cmd(flags))
	cmd.AddCommand(newRubricsUploadStatusCmd(flags))
	cmd.AddCommand(newRubricsUploadStatus2Cmd(flags))
	cmd.AddCommand(newRubricsUploadTemplateCmd(flags))
	cmd.AddCommand(newRubricsUsedLocationsCmd(flags))
	cmd.AddCommand(newRubricsUsedLocations2Cmd(flags))
	return cmd
}
