// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSearchResourceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "search-resource",
		Short:       "[SearchController#recipients](https://github.com/instructure/canvas-lms/blob/master/app/controllers/search_controller.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSearchResourceAllCoursesCmd(flags))
	cmd.AddCommand(newSearchResourceRecipientsCmd(flags))
	cmd.AddCommand(newSearchResourceRecipients2Cmd(flags))
	return cmd
}
