// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSearchResourceRecipientsCmd(flags *rootFlags) *cobra.Command {
	var flagSearch string
	var flagContext string
	var flagExclude string
	var flagType string
	var flagUserId string
	var flagFromConversationId string
	var flagPermissions string

	cmd := &cobra.Command{
		Use:         "recipients",
		Short:       "Find recipients",
		Example:     "  canvas-pp-cli search_resource recipients",
		Annotations: map[string]string{"pp:endpoint": "search_resource.recipients", "pp:method": "GET", "pp:path": "/api/v1/conversations/find_recipients", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/conversations/find_recipients"
			params := map[string]string{}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagContext != "" {
				params["context"] = formatCLIParamValue(flagContext)
			}
			if flagExclude != "" {
				params["exclude[]"] = formatCLIParamValue(flagExclude)
			}
			if flagType != "" {
				params["type"] = formatCLIParamValue(flagType)
			}
			if flagUserId != "" {
				params["user_id"] = formatCLIParamValue(flagUserId)
			}
			if flagFromConversationId != "" {
				params["from_conversation_id"] = formatCLIParamValue(flagFromConversationId)
			}
			if flagPermissions != "" {
				params["permissions[]"] = formatCLIParamValue(flagPermissions)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "search_resource", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearch, "search", "", "Search terms used for matching users/courses/groups (e.g. 'bob smith').")
	cmd.Flags().StringVar(&flagContext, "context", "", "Limit the search to a particular course/group (e.g. 'course_3' or 'group_4').")
	cmd.Flags().StringVar(&flagExclude, "exclude", "", "Array of ids to exclude from the search.")
	cmd.Flags().StringVar(&flagType, "type", "", "Limit the search just to users or contexts (groups/courses). Allowed values: user, context")
	cmd.Flags().StringVar(&flagUserId, "user-id", "", "Search for a specific user id. This ignores the other above parameters, and will never return more than one result.")
	cmd.Flags().StringVar(&flagFromConversationId, "from-conversation-id", "", "When searching by user_id, only users that could be normally messaged by this user will be returned.")
	cmd.Flags().StringVar(&flagPermissions, "permissions", "", "Array of permission strings to be checked for each matched context (e.g. 'send_messages').")

	return cmd
}
