// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newServicesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "services",
		Short:       "[ServicesApiController#show_kaltura_config](https://github.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newServicesShowKalturaConfigCmd(flags))
	cmd.AddCommand(newServicesStartKalturaSessionCmd(flags))
	return cmd
}
