// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSharedBrandConfigsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "shared-brand-configs",
		Short:       "This is how you can share Themes with other people in your account or so you can come back to them later without having",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSharedBrandConfigsCreateCmd(flags))
	cmd.AddCommand(newSharedBrandConfigsDestroyCmd(flags))
	cmd.AddCommand(newSharedBrandConfigsUpdateCmd(flags))
	return cmd
}
