// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"io"
	"testing"
)

// TestNovelSinceHelpWires smoke-tests that the since command
// resolves at runtime and renders --help without error. Catches wiring
// regressions (missing AddCommand, panicking RunE on --help, etc.) before
// review. Always runs — do not delete this test when filling in real cases.
func TestNovelSinceHelpWires(t *testing.T) {
	cmd := RootCmd()
	cmd.SetArgs([]string{"since", "--help"})
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	if err := cmd.Execute(); err != nil {
		t.Fatalf("since --help error = %v (novel command not wired correctly?)", err)
	}
}

// TestNovelSinceBehavior verifies the command resolves and its --dry-run path
// succeeds without dialing the API.
func TestNovelSinceBehavior(t *testing.T) {
	cmd := RootCmd()
	cmd.SetArgs([]string{"since", "24h", "--course", "12345", "--dry-run"})
	cmd.SetOut(io.Discard)
	cmd.SetErr(io.Discard)
	if err := cmd.Execute(); err != nil {
		t.Fatalf("since dry-run should succeed, got %v", err)
	}
}
