// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSisImportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sis-imports",
		Short:       "API for importing data from Student Information Systems",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSisImportsAbortCmd(flags))
	cmd.AddCommand(newSisImportsAbortAllPendingCmd(flags))
	cmd.AddCommand(newSisImportsCreateCmd(flags))
	cmd.AddCommand(newSisImportsImportingCmd(flags))
	cmd.AddCommand(newSisImportsIndexCmd(flags))
	cmd.AddCommand(newSisImportsRestoreStatesCmd(flags))
	cmd.AddCommand(newSisImportsShowCmd(flags))
	return cmd
}
