// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSisImportErrorsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sis-import-errors",
		Short:       "Get sis import errors",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSisImportErrorsIndexCmd(flags))
	cmd.AddCommand(newSisImportErrorsIndex2Cmd(flags))
	return cmd
}
