// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newSisImportsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyImportType string
	var bodyAttachment string
	var bodyPreAttachmentName string
	var bodyPreAttachment string
	var bodyExtension string
	var bodyBatchMode bool
	var bodyBatchModeTermId string
	var bodyMultiTermBatchMode bool
	var bodySkipDeletes bool
	var bodyOverrideSisStickiness bool
	var bodyAddSisStickiness bool
	var bodyClearSisStickiness bool
	var bodyUpdateSisIdIfLoginClaimed bool
	var bodyDiffingDataSetIdentifier string
	var bodyDiffingRemasterDataSet bool
	var bodyDiffingDropStatus string
	var bodyDiffingUserRemoveStatus string
	var bodyBatchModeEnrollmentDropStatus string
	var bodyChangeThreshold int
	var bodyDiffRowCountThreshold int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create <account_id>",
		Short:       "Import SIS data",
		Example:     "  canvas-cli sis_imports create 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "sis_imports.create", "pp:method": "POST", "pp:path": "/api/v1/accounts/{account_id}/sis_imports"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{account_id}/sis_imports"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyImportType != "" {
					body["import_type"] = bodyImportType
				}
				if bodyAttachment != "" {
					body["attachment"] = bodyAttachment
				}
				if bodyPreAttachmentName != "" {
					body["pre_attachment[name]"] = bodyPreAttachmentName
				}
				if bodyPreAttachment != "" {
					body["pre_attachment[*]"] = bodyPreAttachment
				}
				if bodyExtension != "" {
					body["extension"] = bodyExtension
				}
				if cmd.Flags().Changed("batch-mode") {
					body["batch_mode"] = bodyBatchMode
				}
				if bodyBatchModeTermId != "" {
					body["batch_mode_term_id"] = bodyBatchModeTermId
				}
				if cmd.Flags().Changed("multi-term-batch-mode") {
					body["multi_term_batch_mode"] = bodyMultiTermBatchMode
				}
				if cmd.Flags().Changed("skip-deletes") {
					body["skip_deletes"] = bodySkipDeletes
				}
				if cmd.Flags().Changed("override-sis-stickiness") {
					body["override_sis_stickiness"] = bodyOverrideSisStickiness
				}
				if cmd.Flags().Changed("add-sis-stickiness") {
					body["add_sis_stickiness"] = bodyAddSisStickiness
				}
				if cmd.Flags().Changed("clear-sis-stickiness") {
					body["clear_sis_stickiness"] = bodyClearSisStickiness
				}
				if cmd.Flags().Changed("update-sis-id-if-login-claimed") {
					body["update_sis_id_if_login_claimed"] = bodyUpdateSisIdIfLoginClaimed
				}
				if bodyDiffingDataSetIdentifier != "" {
					body["diffing_data_set_identifier"] = bodyDiffingDataSetIdentifier
				}
				if cmd.Flags().Changed("diffing-remaster-data-set") {
					body["diffing_remaster_data_set"] = bodyDiffingRemasterDataSet
				}
				if bodyDiffingDropStatus != "" {
					body["diffing_drop_status"] = bodyDiffingDropStatus
				}
				if bodyDiffingUserRemoveStatus != "" {
					body["diffing_user_remove_status"] = bodyDiffingUserRemoveStatus
				}
				if bodyBatchModeEnrollmentDropStatus != "" {
					body["batch_mode_enrollment_drop_status"] = bodyBatchModeEnrollmentDropStatus
				}
				if bodyChangeThreshold != 0 {
					body["change_threshold"] = bodyChangeThreshold
				}
				if bodyDiffRowCountThreshold != 0 {
					body["diff_row_count_threshold"] = bodyDiffRowCountThreshold
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "sis_imports", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "sis_imports", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "sis_imports", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "sis_imports", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "sis_imports", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "sis_imports",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "sis_imports", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "sis_imports", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyImportType, "import-type", "", "Choose the data format for reading SIS data.")
	cmd.Flags().StringVar(&bodyAttachment, "attachment", "", "There are three ways to post SIS import data: 1. As a multipart/form-data form field named +attachment+ 2.")
	cmd.Flags().StringVar(&bodyPreAttachmentName, "pre-attachment-name", "", "The name of the file to be uploaded (in a separate request) via the File Upload workflow.")
	cmd.Flags().StringVar(&bodyPreAttachment, "pre-attachment", "", "Other file upload properties; see [File Upload Documentation](/services/canvas/basics/file.file_uploads)")
	cmd.Flags().StringVar(&bodyExtension, "extension", "", "Recommended for raw post request style imports.")
	cmd.Flags().BoolVar(&bodyBatchMode, "batch-mode", false, "If set, this SIS import will be run in batch mode")
	cmd.Flags().StringVar(&bodyBatchModeTermId, "batch-mode-term-id", "", "Limit deletions to only this term. Required if batch mode is enabled.")
	cmd.Flags().BoolVar(&bodyMultiTermBatchMode, "multi-term-batch-mode", false, "Runs batch mode against all terms in terms file. Requires change_threshold.")
	cmd.Flags().BoolVar(&bodySkipDeletes, "skip-deletes", false, "When set the import will skip any deletes.")
	cmd.Flags().BoolVar(&bodyOverrideSisStickiness, "override-sis-stickiness", false, "Default is false. If true, any fields containing “sticky” or UI changes will be overridden.")
	cmd.Flags().BoolVar(&bodyAddSisStickiness, "add-sis-stickiness", false, "This option, if present, will process all changes as if they were UI changes.")
	cmd.Flags().BoolVar(&bodyClearSisStickiness, "clear-sis-stickiness", false, "This option, if present, will clear 'stickiness' from all fields processed by this import.")
	cmd.Flags().BoolVar(&bodyUpdateSisIdIfLoginClaimed, "update-sis-id-if-login-claimed", false, "This option, if present, will override the old (or non-existent) non-matching SIS ID with the new SIS ID in the upload")
	cmd.Flags().StringVar(&bodyDiffingDataSetIdentifier, "diffing-data-set-identifier", "", "If set on a CSV import")
	cmd.Flags().BoolVar(&bodyDiffingRemasterDataSet, "diffing-remaster-data-set", false, "If true, and diffing_data_set_identifier is sent, this SIS import will be part of the data set")
	cmd.Flags().StringVar(&bodyDiffingDropStatus, "diffing-drop-status", "", "If diffing_drop_status is passed")
	cmd.Flags().StringVar(&bodyDiffingUserRemoveStatus, "diffing-user-remove-status", "", "For users removed from one batch to the next one using the same diffing_data_set_identifier")
	cmd.Flags().StringVar(&bodyBatchModeEnrollmentDropStatus, "batch-mode-enrollment-drop-status", "", "If batch_mode_enrollment_drop_status is passed")
	cmd.Flags().IntVar(&bodyChangeThreshold, "change-threshold", 0, "If set with batch_mode")
	cmd.Flags().IntVar(&bodyDiffRowCountThreshold, "diff-row-count-threshold", 0, "If set with diffing")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
