// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSubmissionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "submissions",
		Short:       "API for accessing and updating submissions for an assignment.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSubmissionsBulkUpdateCmd(flags))
	cmd.AddCommand(newSubmissionsBulkUpdate2Cmd(flags))
	cmd.AddCommand(newSubmissionsBulkUpdate3Cmd(flags))
	cmd.AddCommand(newSubmissionsBulkUpdate4Cmd(flags))
	cmd.AddCommand(newSubmissionsCreateCmd(flags))
	cmd.AddCommand(newSubmissionsCreate2Cmd(flags))
	cmd.AddCommand(newSubmissionsCreateFileCmd(flags))
	cmd.AddCommand(newSubmissionsCreateFile2Cmd(flags))
	cmd.AddCommand(newSubmissionsDocumentAnnotationsReadStateCmd(flags))
	cmd.AddCommand(newSubmissionsDocumentAnnotationsReadState2Cmd(flags))
	cmd.AddCommand(newSubmissionsForStudentsCmd(flags))
	cmd.AddCommand(newSubmissionsForStudents2Cmd(flags))
	cmd.AddCommand(newSubmissionsGradeableStudentsCmd(flags))
	cmd.AddCommand(newSubmissionsIndexCmd(flags))
	cmd.AddCommand(newSubmissionsIndex2Cmd(flags))
	cmd.AddCommand(newSubmissionsMarkBulkSubmissionsAsReadCmd(flags))
	cmd.AddCommand(newSubmissionsMarkBulkSubmissionsAsRead2Cmd(flags))
	cmd.AddCommand(newSubmissionsMarkDocumentAnnotationsReadCmd(flags))
	cmd.AddCommand(newSubmissionsMarkDocumentAnnotationsRead2Cmd(flags))
	cmd.AddCommand(newSubmissionsMarkRubricAssessmentsReadCmd(flags))
	cmd.AddCommand(newSubmissionsMarkRubricAssessmentsRead2Cmd(flags))
	cmd.AddCommand(newSubmissionsMarkRubricAssessmentsRead3Cmd(flags))
	cmd.AddCommand(newSubmissionsMarkRubricAssessmentsRead4Cmd(flags))
	cmd.AddCommand(newSubmissionsMarkSubmissionItemReadCmd(flags))
	cmd.AddCommand(newSubmissionsMarkSubmissionItemRead2Cmd(flags))
	cmd.AddCommand(newSubmissionsMarkSubmissionReadCmd(flags))
	cmd.AddCommand(newSubmissionsMarkSubmissionRead2Cmd(flags))
	cmd.AddCommand(newSubmissionsMarkSubmissionUnreadCmd(flags))
	cmd.AddCommand(newSubmissionsMarkSubmissionUnread2Cmd(flags))
	cmd.AddCommand(newSubmissionsMultipleGradeableStudentsCmd(flags))
	cmd.AddCommand(newSubmissionsRubricAssessmentsReadStateCmd(flags))
	cmd.AddCommand(newSubmissionsRubricAssessmentsReadState2Cmd(flags))
	cmd.AddCommand(newSubmissionsRubricAssessmentsReadState3Cmd(flags))
	cmd.AddCommand(newSubmissionsRubricAssessmentsReadState4Cmd(flags))
	cmd.AddCommand(newSubmissionsShowCmd(flags))
	cmd.AddCommand(newSubmissionsShow2Cmd(flags))
	cmd.AddCommand(newSubmissionsShowAnonymousCmd(flags))
	cmd.AddCommand(newSubmissionsShowAnonymous2Cmd(flags))
	cmd.AddCommand(newSubmissionsSubmissionSummaryCmd(flags))
	cmd.AddCommand(newSubmissionsSubmissionSummary2Cmd(flags))
	cmd.AddCommand(newSubmissionsSubmissionsClearUnreadCmd(flags))
	cmd.AddCommand(newSubmissionsSubmissionsClearUnread2Cmd(flags))
	cmd.AddCommand(newSubmissionsUpdateCmd(flags))
	cmd.AddCommand(newSubmissionsUpdate2Cmd(flags))
	cmd.AddCommand(newSubmissionsUpdateAnonymousCmd(flags))
	cmd.AddCommand(newSubmissionsUpdateAnonymous2Cmd(flags))
	return cmd
}
