// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newSubmissionsBulkUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyGradeDataStudentIdPostedGrade string
	var bodyGradeDataStudentIdExcuse bool
	var bodyGradeDataStudentIdRubricAssessment string
	var bodyGradeDataStudentIdTextComment string
	var bodyGradeDataStudentIdGroupComment bool
	var bodyGradeDataStudentIdMediaCommentId string
	var bodyGradeDataStudentIdMediaCommentType string
	var bodyGradeDataStudentIdFileIds int
	var bodyGradeDataAssignmentIdStudentId int
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "bulk-update <course_id>",
		Short:       "Grade or comment on multiple submissions",
		Example:     "  canvas-cli submissions bulk-update 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "submissions.bulk_update", "pp:method": "POST", "pp:path": "/api/v1/courses/{course_id}/submissions/update_grades"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/courses/{course_id}/submissions/update_grades"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("course_id is required\nUsage: %s <%s>", cmd.CommandPath(), "course_id"))
			}
			path = replacePathParam(path, "course_id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyGradeDataStudentIdPostedGrade != "" {
					body["grade_data[<student_id>][posted_grade]"] = bodyGradeDataStudentIdPostedGrade
				}
				if cmd.Flags().Changed("grade-data-student-id-excuse") {
					body["grade_data[<student_id>][excuse]"] = bodyGradeDataStudentIdExcuse
				}
				if bodyGradeDataStudentIdRubricAssessment != "" {
					body["grade_data[<student_id>][rubric_assessment]"] = bodyGradeDataStudentIdRubricAssessment
				}
				if bodyGradeDataStudentIdTextComment != "" {
					body["grade_data[<student_id>][text_comment]"] = bodyGradeDataStudentIdTextComment
				}
				if cmd.Flags().Changed("grade-data-student-id-group-comment") {
					body["grade_data[<student_id>][group_comment]"] = bodyGradeDataStudentIdGroupComment
				}
				if bodyGradeDataStudentIdMediaCommentId != "" {
					body["grade_data[<student_id>][media_comment_id]"] = bodyGradeDataStudentIdMediaCommentId
				}
				if bodyGradeDataStudentIdMediaCommentType != "" {
					body["grade_data[<student_id>][media_comment_type]"] = bodyGradeDataStudentIdMediaCommentType
				}
				if bodyGradeDataStudentIdFileIds != 0 {
					body["grade_data[<student_id>][file_ids][]"] = bodyGradeDataStudentIdFileIds
				}
				if bodyGradeDataAssignmentIdStudentId != 0 {
					body["grade_data[<assignment_id>][<student_id>]"] = bodyGradeDataAssignmentIdStudentId
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "submissions", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "submissions", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "submissions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyGradeDataStudentIdPostedGrade, "grade-data-student-id-posted-grade", "", "See documentation for the posted_grade argument in the Submissions Update documentation")
	cmd.Flags().BoolVar(&bodyGradeDataStudentIdExcuse, "grade-data-student-id-excuse", false, "See documentation for the excuse argument in the Submissions Update documentation")
	cmd.Flags().StringVar(&bodyGradeDataStudentIdRubricAssessment, "grade-data-student-id-rubric-assessment", "", "See documentation for the rubric_assessment argument in the Submissions Update documentation")
	cmd.Flags().StringVar(&bodyGradeDataStudentIdTextComment, "grade-data-student-id-text-comment", "", "no description")
	cmd.Flags().BoolVar(&bodyGradeDataStudentIdGroupComment, "grade-data-student-id-group-comment", false, "no description")
	cmd.Flags().StringVar(&bodyGradeDataStudentIdMediaCommentId, "grade-data-student-id-media-comment-id", "", "no description")
	cmd.Flags().StringVar(&bodyGradeDataStudentIdMediaCommentType, "grade-data-student-id-media-comment-type", "", "no description Allowed values: audio, video")
	cmd.Flags().IntVar(&bodyGradeDataStudentIdFileIds, "grade-data-student-id-file-ids", 0, "See documentation for the comment[] arguments in the Submissions Update documentation")
	cmd.Flags().IntVar(&bodyGradeDataAssignmentIdStudentId, "grade-data-assignment-id-student-id", 0, "Specifies which assignment to grade. This argument is not necessary when using the assignment-specific endpoints.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
