// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newSubmissionsCreate2Cmd(flags *rootFlags) *cobra.Command {
	var bodyCommentTextComment string
	var bodySubmissionGroupComment bool
	var bodySubmissionSubmissionType string
	var bodySubmissionBody string
	var bodySubmissionUrl string
	var bodySubmissionFileIds int
	var bodySubmissionMediaCommentId string
	var bodySubmissionMediaCommentType string
	var bodySubmissionUserId int
	var bodySubmissionAnnotatableAttachmentId int
	var bodySubmissionSubmittedAt string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create-2 <section_id> <assignment_id>",
		Short: "Submit an assignment",
		// TODO: replace placeholder example values before relying on this for live dogfood.
		Example:     "  canvas-cli submissions create-2 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 --submission-submission-type example-value",
		Annotations: map[string]string{"pp:endpoint": "submissions.create_2", "pp:method": "POST", "pp:path": "/api/v1/sections/{section_id}/assignments/{assignment_id}/submissions"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("submission-submission-type") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "submission-submission-type")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/sections/{section_id}/assignments/{assignment_id}/submissions"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("section_id is required\nUsage: %s <%s>", cmd.CommandPath(), "section_id"))
			}
			path = replacePathParam(path, "section_id", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("assignment_id is required\nUsage: %s <%s>", cmd.CommandPath(), "assignment_id"))
			}
			path = replacePathParam(path, "assignment_id", args[1])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCommentTextComment != "" {
					body["comment[text_comment]"] = bodyCommentTextComment
				}
				if cmd.Flags().Changed("submission-group-comment") {
					body["submission[group_comment]"] = bodySubmissionGroupComment
				}
				if bodySubmissionSubmissionType != "" {
					body["submission[submission_type]"] = bodySubmissionSubmissionType
				}
				if bodySubmissionBody != "" {
					body["submission[body]"] = bodySubmissionBody
				}
				if bodySubmissionUrl != "" {
					body["submission[url]"] = bodySubmissionUrl
				}
				if bodySubmissionFileIds != 0 {
					body["submission[file_ids][]"] = bodySubmissionFileIds
				}
				if bodySubmissionMediaCommentId != "" {
					body["submission[media_comment_id]"] = bodySubmissionMediaCommentId
				}
				if bodySubmissionMediaCommentType != "" {
					body["submission[media_comment_type]"] = bodySubmissionMediaCommentType
				}
				if bodySubmissionUserId != 0 {
					body["submission[user_id]"] = bodySubmissionUserId
				}
				if bodySubmissionAnnotatableAttachmentId != 0 {
					body["submission[annotatable_attachment_id]"] = bodySubmissionAnnotatableAttachmentId
				}
				if bodySubmissionSubmittedAt != "" {
					body["submission[submitted_at]"] = bodySubmissionSubmittedAt
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "submissions", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "submissions", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "submissions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyCommentTextComment, "comment-text-comment", "", "Include a textual comment with the submission.")
	cmd.Flags().BoolVar(&bodySubmissionGroupComment, "submission-group-comment", false, "Whether or not this comment should be sent to the entire group (defaults to false).")
	cmd.Flags().StringVar(&bodySubmissionSubmissionType, "submission-submission-type", "", "The type of submission being made.")
	cmd.Flags().StringVar(&bodySubmissionBody, "submission-body", "", "Submit the assignment as an HTML document snippet.")
	cmd.Flags().StringVar(&bodySubmissionUrl, "submission-url", "", "Submit the assignment as a URL. The URL scheme must be 'http' or 'https', no 'ftp' or other URL schemes are allowed.")
	cmd.Flags().IntVar(&bodySubmissionFileIds, "submission-file-ids", 0, "Submit the assignment as a set of one or more previously uploaded files residing in the submitting user's files section")
	cmd.Flags().StringVar(&bodySubmissionMediaCommentId, "submission-media-comment-id", "", "The media comment id to submit.")
	cmd.Flags().StringVar(&bodySubmissionMediaCommentType, "submission-media-comment-type", "", "The type of media comment being submitted. Allowed values: audio, video")
	cmd.Flags().IntVar(&bodySubmissionUserId, "submission-user-id", 0, "Submit on behalf of the given user. Requires grading permission.")
	cmd.Flags().IntVar(&bodySubmissionAnnotatableAttachmentId, "submission-annotatable-attachment-id", 0, "The Attachment ID of the document being annotated. This should match the annotatable_attachment_id on the assignment.")
	cmd.Flags().StringVar(&bodySubmissionSubmittedAt, "submission-submitted-at", "", "Choose the time the submission is listed as submitted at. Requires grading permission.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
