// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newSubmissionsUpdate2Cmd(flags *rootFlags) *cobra.Command {
	var bodyCommentTextComment string
	var bodyCommentAttempt int
	var bodyCommentGroupComment bool
	var bodyCommentMediaCommentId string
	var bodyCommentMediaCommentType string
	var bodyCommentFileIds int
	var bodyInclude string
	var bodyPreferPointsOverScheme bool
	var bodySubmissionPostedGrade string
	var bodySubmissionExcuse bool
	var bodySubmissionLatePolicyStatus string
	var bodySubmissionSticker string
	var bodySubmissionSecondsLateOverride int
	var bodySubmissionPeerReview bool
	var bodyRubricAssessment string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "update-2 <section_id> <assignment_id> <user_id>",
		Short:       "Grade or comment on a submission",
		Example:     "  canvas-pp-cli submissions update-2 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "submissions.update_2", "pp:method": "PUT", "pp:path": "/api/v1/sections/{section_id}/assignments/{assignment_id}/submissions/{user_id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/sections/{section_id}/assignments/{assignment_id}/submissions/{user_id}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("section_id is required\nUsage: %s <%s>", cmd.CommandPath(), "section_id"))
			}
			path = replacePathParam(path, "section_id", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("assignment_id is required\nUsage: %s <%s>", cmd.CommandPath(), "assignment_id"))
			}
			path = replacePathParam(path, "assignment_id", args[1])
			if len(args) < 3 || args[2] == "" {
				return usageErr(fmt.Errorf("user_id is required\nUsage: %s <%s>", cmd.CommandPath(), "user_id"))
			}
			path = replacePathParam(path, "user_id", args[2])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyCommentTextComment != "" {
					body["comment[text_comment]"] = bodyCommentTextComment
				}
				if bodyCommentAttempt != 0 {
					body["comment[attempt]"] = bodyCommentAttempt
				}
				if cmd.Flags().Changed("comment-group-comment") {
					body["comment[group_comment]"] = bodyCommentGroupComment
				}
				if bodyCommentMediaCommentId != "" {
					body["comment[media_comment_id]"] = bodyCommentMediaCommentId
				}
				if bodyCommentMediaCommentType != "" {
					body["comment[media_comment_type]"] = bodyCommentMediaCommentType
				}
				if bodyCommentFileIds != 0 {
					body["comment[file_ids][]"] = bodyCommentFileIds
				}
				if bodyInclude != "" {
					body["include[]"] = bodyInclude
				}
				if cmd.Flags().Changed("prefer-points-over-scheme") {
					body["prefer_points_over_scheme"] = bodyPreferPointsOverScheme
				}
				if bodySubmissionPostedGrade != "" {
					body["submission[posted_grade]"] = bodySubmissionPostedGrade
				}
				if cmd.Flags().Changed("submission-excuse") {
					body["submission[excuse]"] = bodySubmissionExcuse
				}
				if bodySubmissionLatePolicyStatus != "" {
					body["submission[late_policy_status]"] = bodySubmissionLatePolicyStatus
				}
				if bodySubmissionSticker != "" {
					body["submission[sticker]"] = bodySubmissionSticker
				}
				if bodySubmissionSecondsLateOverride != 0 {
					body["submission[seconds_late_override]"] = bodySubmissionSecondsLateOverride
				}
				if cmd.Flags().Changed("submission-peer-review") {
					body["submission[peer_review]"] = bodySubmissionPeerReview
				}
				if bodyRubricAssessment != "" {
					body["rubric_assessment"] = bodyRubricAssessment
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "submissions", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "submissions", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "submissions",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "submissions", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyCommentTextComment, "comment-text-comment", "", "Add a textual comment to the submission.")
	cmd.Flags().IntVar(&bodyCommentAttempt, "comment-attempt", 0, "The attempt number (starts at 1) to associate the comment with.")
	cmd.Flags().BoolVar(&bodyCommentGroupComment, "comment-group-comment", false, "Whether or not this comment should be sent to the entire group (defaults to false).")
	cmd.Flags().StringVar(&bodyCommentMediaCommentId, "comment-media-comment-id", "", "Add an audio/video comment to the submission.")
	cmd.Flags().StringVar(&bodyCommentMediaCommentType, "comment-media-comment-type", "", "The type of media comment being added. Allowed values: audio, video")
	cmd.Flags().IntVar(&bodyCommentFileIds, "comment-file-ids", 0, "Attach files to this comment that were previously uploaded using the Submission Comment API's files action")
	cmd.Flags().StringVar(&bodyInclude, "include", "", "Associations to include with the submission. 'submission_comments' is always included by default.")
	cmd.Flags().BoolVar(&bodyPreferPointsOverScheme, "prefer-points-over-scheme", false, "Treat posted_grade as points if the value matches a grading scheme value")
	cmd.Flags().StringVar(&bodySubmissionPostedGrade, "submission-posted-grade", "", "Assign a score to the submission, updating both the 'score' and 'grade' fields on the submission record.")
	cmd.Flags().BoolVar(&bodySubmissionExcuse, "submission-excuse", false, "Sets the 'excused' status of an assignment.")
	cmd.Flags().StringVar(&bodySubmissionLatePolicyStatus, "submission-late-policy-status", "", "Sets the late policy status to either 'late', 'missing', 'extended', 'none', or null.")
	cmd.Flags().StringVar(&bodySubmissionSticker, "submission-sticker", "", "Sets the sticker for the submission.")
	cmd.Flags().IntVar(&bodySubmissionSecondsLateOverride, "submission-seconds-late-override", 0, "Sets the seconds late if late policy status is 'late'")
	cmd.Flags().BoolVar(&bodySubmissionPeerReview, "submission-peer-review", false, "When true, updates the peer review sub assignment submission instead of the parent assignment submission.")
	cmd.Flags().StringVar(&bodyRubricAssessment, "rubric-assessment", "", "Assign a rubric assessment to this assignment submission.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
