// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newSubmissionsForStudents2Cmd(flags *rootFlags) *cobra.Command {
	var flagStudentIds string
	var flagAssignmentIds string
	var flagGrouped bool
	var flagPostToSis bool
	var flagSubmittedSince string
	var flagGradedSince string
	var flagGradingPeriodId string
	var flagWorkflowState string
	var flagEnrollmentState string
	var flagStateBasedOnDate bool
	var flagOrder string
	var flagOrderDirection string
	var flagInclude string

	cmd := &cobra.Command{
		Use:         "for-students-2 <section_id>",
		Short:       "List submissions for multiple assignments",
		Example:     "  canvas-pp-cli submissions for-students-2 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "submissions.for_students_2", "pp:method": "GET", "pp:path": "/api/v1/sections/{section_id}/students/submissions", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/sections/{section_id}/students/submissions"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("section_id is required\nUsage: %s <%s>", cmd.CommandPath(), "section_id"))
			}
			path = replacePathParam(path, "section_id", args[0])
			params := map[string]string{}
			if flagStudentIds != "" {
				params["student_ids[]"] = formatCLIParamValue(flagStudentIds)
			}
			if flagAssignmentIds != "" {
				params["assignment_ids[]"] = formatCLIParamValue(flagAssignmentIds)
			}
			if flagGrouped != false {
				params["grouped"] = formatCLIParamValue(flagGrouped)
			}
			if flagPostToSis != false {
				params["post_to_sis"] = formatCLIParamValue(flagPostToSis)
			}
			if flagSubmittedSince != "" {
				params["submitted_since"] = formatCLIParamValue(flagSubmittedSince)
			}
			if flagGradedSince != "" {
				params["graded_since"] = formatCLIParamValue(flagGradedSince)
			}
			if flagGradingPeriodId != "" {
				params["grading_period_id"] = formatCLIParamValue(flagGradingPeriodId)
			}
			if flagWorkflowState != "" {
				params["workflow_state"] = formatCLIParamValue(flagWorkflowState)
			}
			if flagEnrollmentState != "" {
				params["enrollment_state"] = formatCLIParamValue(flagEnrollmentState)
			}
			if flagStateBasedOnDate != false {
				params["state_based_on_date"] = formatCLIParamValue(flagStateBasedOnDate)
			}
			if flagOrder != "" {
				params["order"] = formatCLIParamValue(flagOrder)
			}
			if flagOrderDirection != "" {
				params["order_direction"] = formatCLIParamValue(flagOrderDirection)
			}
			if flagInclude != "" {
				params["include[]"] = formatCLIParamValue(flagInclude)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "submissions", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStudentIds, "student-ids", "", "List of student ids to return submissions for. If this argument is omitted, return submissions for the calling user.")
	cmd.Flags().StringVar(&flagAssignmentIds, "assignment-ids", "", "List of assignments to return submissions for. If none are given, submissions for all assignments are returned.")
	cmd.Flags().BoolVar(&flagGrouped, "grouped", false, "If this argument is present, the response will be grouped by student, rather than a flat array of submissions.")
	cmd.Flags().BoolVar(&flagPostToSis, "post-to-sis", false, "If this argument is set to true")
	cmd.Flags().StringVar(&flagSubmittedSince, "submitted-since", "", "If this argument is set, the response will only include submissions that were submitted after the specified date_time.")
	cmd.Flags().StringVar(&flagGradedSince, "graded-since", "", "If this argument is set, the response will only include submissions that were graded after the specified date_time.")
	cmd.Flags().StringVar(&flagGradingPeriodId, "grading-period-id", "", "The id of the grading period in which submissions are being requested (Requires grading periods to exist on the account)")
	cmd.Flags().StringVar(&flagWorkflowState, "workflow-state", "", "The current status of the submission Allowed values: submitted, unsubmitted, graded, pending_review")
	cmd.Flags().StringVar(&flagEnrollmentState, "enrollment-state", "", "The current state of the enrollments. If omitted will include all enrollments that are not deleted.")
	cmd.Flags().BoolVar(&flagStateBasedOnDate, "state-based-on-date", false, "If omitted it is set to true.")
	cmd.Flags().StringVar(&flagOrder, "order", "", "The order submissions will be returned in. Defaults to 'id'. Doesn't affect results for 'grouped' mode.")
	cmd.Flags().StringVar(&flagOrderDirection, "order-direction", "", "Determines whether ordered results are returned in ascending or descending order. Defaults to 'ascending'.")
	cmd.Flags().StringVar(&flagInclude, "include", "", "Associations to include with the group. total_scores requires the grouped argument.")

	return cmd
}
