// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/johnnyrobot/canvas-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newTailCmd(flags *rootFlags) *cobra.Command {
	var resource string
	var interval time.Duration
	var follow bool

	cmd := &cobra.Command{
		Use:         "tail [resource]",
		Short:       "Stream live changes by polling the API at regular intervals",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:no-error-path-probe": "true"},
		Long: `Tail streams live data changes by polling the API at configurable intervals.
Events are emitted as NDJSON to stdout for piping to other tools.
Gracefully shuts down on SIGTERM/SIGINT.

Note: For APIs with WebSocket or SSE support, a future version will use
native streaming instead of polling.`,
		Example: `  # Tail all changes every 10 seconds
  canvas-pp-cli tail --interval 10s

  # Tail a specific resource
  canvas-pp-cli tail messages --interval 5s

  # Pipe to jq for filtering
  canvas-pp-cli tail events --interval 30s | jq 'select(.type == "error")'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				resource = args[0]
			}
			// JSON help envelope: when called with no resource AND --json,
			// surface the list of known resources so agents can discover
			// what to pass without parsing a usage error message.
			// Envelope: {resources: [...], note}.
			if resource == "" && flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"resources": tailKnownResources(),
					"note":      "tail requires a resource name; pass one of the listed names",
				}, flags)
			}
			if resource == "" {
				return fmt.Errorf("resource name required (e.g., 'tail messages')")
			}
			// Reject a resource this CLI does not expose before binding the poll
			// loop: an unknown name only ever 404s, so failing fast with a
			// non-zero exit (and the valid set) beats warning once per poll
			// forever. Also satisfies the invalid-argument contract the dogfood
			// error-path probe checks.
			knownResource := false
			for _, r := range tailKnownResources() {
				if r == resource {
					knownResource = true
					break
				}
			}
			if !knownResource {
				return fmt.Errorf("unknown resource %q; known resources: %v", resource, tailKnownResources())
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c.NoCache = true
			if cliutil.IsDogfoodEnv() {
				follow = false
			}

			path := "/" + resource

			sig := make(chan os.Signal, 1)
			signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)

			enc := json.NewEncoder(os.Stdout)

			if follow {
				fmt.Fprintf(os.Stderr, "Tailing %s every %s (Ctrl+C to stop)\n", resource, interval)
			}

			// Initial fetch
			if err := fetchAndEmit(cmd.Context(), c, path, enc); err != nil {
				fmt.Fprintf(os.Stderr, "warning: initial fetch failed: %v\n", err)
			}
			if !follow {
				return nil
			}

			ticker := time.NewTicker(interval)
			defer ticker.Stop()

			for {
				select {
				case <-sig:
					fmt.Fprintln(os.Stderr, "\nShutting down gracefully...")
					return nil
				case <-ticker.C:
					if err := fetchAndEmit(cmd.Context(), c, path, enc); err != nil {
						fmt.Fprintf(os.Stderr, "warning: poll failed: %v\n", err)
					}
				}
			}
		},
	}

	cmd.Flags().StringVar(&resource, "resource", "", "Resource type to tail")
	cmd.Flags().DurationVar(&interval, "interval", 10*time.Second, "Poll interval")
	cmd.Flags().BoolVar(&follow, "follow", true, "Keep running (set --follow=false for single poll)")

	return cmd
}

// tailKnownResources returns the resource names this CLI exposes, so the
// no-arg JSON help envelope can list them without depending on sync's
// defaultSyncResources (which only exists when sync is generated).
func tailKnownResources() []string {
	return []string{
		"access_tokens",
		"accessibility_course_scans",
		"accessibility_course_statistics",
		"account_calendars",
		"account_domain_lookups",
		"account_notifications",
		"account_reports",
		"accounts",
		"admins",
		"ai_conversations",
		"ai_experiences",
		"analytics_resource",
		"announcement_external_feeds",
		"announcements",
		"api_token_scopes",
		"appointment_groups",
		"assessment_question_banks",
		"assignment_extensions",
		"assignment_groups",
		"assignments",
		"authentication_providers",
		"authentications_log",
		"blackout_dates",
		"blockeditortemplate",
		"blueprint_courses",
		"bookmarks",
		"brand_configs",
		"calendar_events",
		"canvas_career_experiences",
		"collaborations",
		"commmessages",
		"communication_channels",
		"conferences",
		"content_exports",
		"content_migrations",
		"content_security_policy_settings",
		"content_shares",
		"conversations",
		"course_audit_log",
		"course_pace",
		"course_quiz_extensions",
		"course_reports",
		"courses",
		"custom_gradebook_columns",
		"developer_key_account_bindings",
		"developer_keys",
		"discovery_pages",
		"discussion_topics",
		"enrollment_terms",
		"enrollments",
		"eportfolios",
		"epub_exports",
		"error_reports",
		"external_tools",
		"favorites",
		"feature_flags",
		"files",
		"grade_change_log",
		"gradebook_history",
		"grading_period_sets",
		"grading_periods",
		"grading_standards",
		"group_categories",
		"groups",
		"history_resource",
		"instaccess_tokens",
		"jwts",
		"late_policy",
		"learning_object_dates",
		"liveassessments",
		"logins",
		"lti_contextcontrols",
		"lti_launch_definitions",
		"lti_registrations",
		"lti_resource_links",
		"media_objects",
		"moderated_grading",
		"modules",
		"notification_preferences",
		"outcome_groups",
		"outcome_imports",
		"outcome_results",
		"outcomes",
		"pages",
		"peer_reviews",
		"planner",
		"poll_sessions",
		"pollchoices",
		"polls",
		"pollsubmissions",
		"proficiency_ratings",
		"progress",
		"quiz_assignment_overrides",
		"quiz_extensions",
		"quiz_ip_filters",
		"quiz_question_groups",
		"quiz_questions",
		"quiz_reports",
		"quiz_statistics",
		"quiz_submission_events",
		"quiz_submission_files",
		"quiz_submission_questions",
		"quiz_submission_user_list",
		"quiz_submissions",
		"quizzes",
		"roles",
		"rubrics",
		"search_resource",
		"sections",
		"services",
		"shared_brand_configs",
		"sis_import_errors",
		"sis_imports",
		"smart_search",
		"study_assist",
		"submission_comments",
		"submissions",
		"tabs",
		"temporary_enrollment_pairings",
		"user_observees",
		"users",
		"what_if_grades",
	}
}

func fetchAndEmit(ctx context.Context, c interface {
	Get(context.Context, string, map[string]string) (json.RawMessage, error)
}, path string, enc *json.Encoder) error {
	data, err := c.Get(ctx, path, nil)
	if err != nil {
		return err
	}

	var items []json.RawMessage
	if err := json.Unmarshal(data, &items); err != nil {
		event := map[string]any{
			"event":     "data",
			"timestamp": time.Now().UTC().Format(time.RFC3339),
			"data":      json.RawMessage(data),
		}
		return enc.Encode(event)
	}

	for _, item := range items {
		event := map[string]any{
			"event":     "data",
			"timestamp": time.Now().UTC().Format(time.RFC3339),
			"data":      item,
		}
		if err := enc.Encode(event); err != nil {
			return err
		}
	}
	return nil
}
