// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUserObserveesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "user-observees",
		Short:       "API for managing linked observers and observees",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUserObserveesCreateCmd(flags))
	cmd.AddCommand(newUserObserveesCreate2Cmd(flags))
	cmd.AddCommand(newUserObserveesDestroyCmd(flags))
	cmd.AddCommand(newUserObserveesIndexCmd(flags))
	cmd.AddCommand(newUserObserveesObserversCmd(flags))
	cmd.AddCommand(newUserObserveesShowCmd(flags))
	cmd.AddCommand(newUserObserveesShowObserverCmd(flags))
	cmd.AddCommand(newUserObserveesUpdateCmd(flags))
	return cmd
}
