// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newUsersSettings2Cmd(flags *rootFlags) *cobra.Command {
	var bodyManualMarkAsRead bool
	var bodyReleaseNotesBadgeDisabled bool
	var bodyCollapseGlobalNav bool
	var bodyCollapseCourseNav bool
	var bodyHideDashcardColorOverlays bool
	var bodyCommentLibrarySuggestionsEnabled bool
	var bodyElementaryDashboardDisabled bool
	var bodyWidgetDashboardUserPreference bool
	var bodyWidgetDashboardDarkMode bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "settings-2 <id>",
		Short:       "Update user settings.",
		Example:     "  canvas-pp-cli users settings-2 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "users.settings_2", "pp:method": "PUT", "pp:path": "/api/v1/users/{id}/settings"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/users/{id}/settings"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("id is required\nUsage: %s <%s>", cmd.CommandPath(), "id"))
			}
			path = replacePathParam(path, "id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if cmd.Flags().Changed("manual-mark-as-read") {
					body["manual_mark_as_read"] = bodyManualMarkAsRead
				}
				if cmd.Flags().Changed("release-notes-badge-disabled") {
					body["release_notes_badge_disabled"] = bodyReleaseNotesBadgeDisabled
				}
				if cmd.Flags().Changed("collapse-global-nav") {
					body["collapse_global_nav"] = bodyCollapseGlobalNav
				}
				if cmd.Flags().Changed("collapse-course-nav") {
					body["collapse_course_nav"] = bodyCollapseCourseNav
				}
				if cmd.Flags().Changed("hide-dashcard-color-overlays") {
					body["hide_dashcard_color_overlays"] = bodyHideDashcardColorOverlays
				}
				if cmd.Flags().Changed("comment-library-suggestions-enabled") {
					body["comment_library_suggestions_enabled"] = bodyCommentLibrarySuggestionsEnabled
				}
				if cmd.Flags().Changed("elementary-dashboard-disabled") {
					body["elementary_dashboard_disabled"] = bodyElementaryDashboardDisabled
				}
				if cmd.Flags().Changed("widget-dashboard-user-preference") {
					body["widget_dashboard_user_preference"] = bodyWidgetDashboardUserPreference
				}
				if cmd.Flags().Changed("widget-dashboard-dark-mode") {
					body["widget_dashboard_dark_mode"] = bodyWidgetDashboardDarkMode
				}
			}
			data, statusCode, err := c.PutWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "users", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "users", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "users",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&bodyManualMarkAsRead, "manual-mark-as-read", false, "If true, require user to manually mark discussion posts as read (don't auto-mark as read).")
	cmd.Flags().BoolVar(&bodyReleaseNotesBadgeDisabled, "release-notes-badge-disabled", false, "If true, hide the badge for new release notes.")
	cmd.Flags().BoolVar(&bodyCollapseGlobalNav, "collapse-global-nav", false, "If true, the user's page loads with the global navigation collapsed")
	cmd.Flags().BoolVar(&bodyCollapseCourseNav, "collapse-course-nav", false, "If true, the user's course pages will load with the course navigation collapsed.")
	cmd.Flags().BoolVar(&bodyHideDashcardColorOverlays, "hide-dashcard-color-overlays", false, "If true, images on course cards will be presented without being tinted to match the course color.")
	cmd.Flags().BoolVar(&bodyCommentLibrarySuggestionsEnabled, "comment-library-suggestions-enabled", false, "If true, suggestions within the comment library will be shown.")
	cmd.Flags().BoolVar(&bodyElementaryDashboardDisabled, "elementary-dashboard-disabled", false, "If true, will display the user's preferred class Canvas dashboard view instead of the canvas for elementary view.")
	cmd.Flags().BoolVar(&bodyWidgetDashboardUserPreference, "widget-dashboard-user-preference", false, "If true, enables the widget dashboard for the user.")
	cmd.Flags().BoolVar(&bodyWidgetDashboardDarkMode, "widget-dashboard-dark-mode", false, "If true, enables the dark color theme for the widget dashboard.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
