// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "users",
		Short:       "API for accessing information on the current and other users.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUsersActivityStreamCmd(flags))
	cmd.AddCommand(newUsersActivityStream2Cmd(flags))
	cmd.AddCommand(newUsersActivityStreamSummaryCmd(flags))
	cmd.AddCommand(newUsersApiIndexCmd(flags))
	cmd.AddCommand(newUsersApiShowCmd(flags))
	cmd.AddCommand(newUsersBatchQueryCmd(flags))
	cmd.AddCommand(newUsersBatchQueryResultsCmd(flags))
	cmd.AddCommand(newUsersClearCmd(flags))
	cmd.AddCommand(newUsersCreateCmd(flags))
	cmd.AddCommand(newUsersCreateFileCmd(flags))
	cmd.AddCommand(newUsersCreateSelfRegisteredUserCmd(flags))
	cmd.AddCommand(newUsersDeleteCmd(flags))
	cmd.AddCommand(newUsersDeleteDataCmd(flags))
	cmd.AddCommand(newUsersExpireMobileSessionsCmd(flags))
	cmd.AddCommand(newUsersExpireMobileSessions2Cmd(flags))
	cmd.AddCommand(newUsersGetCustomColorCmd(flags))
	cmd.AddCommand(newUsersGetCustomColorsCmd(flags))
	cmd.AddCommand(newUsersGetDashboardPositionsCmd(flags))
	cmd.AddCommand(newUsersGetDataCmd(flags))
	cmd.AddCommand(newUsersIgnoreAllStreamItemsCmd(flags))
	cmd.AddCommand(newUsersIgnoreStreamItemCmd(flags))
	cmd.AddCommand(newUsersIndexCmd(flags))
	cmd.AddCommand(newUsersIndex2Cmd(flags))
	cmd.AddCommand(newUsersMergeIntoCmd(flags))
	cmd.AddCommand(newUsersMergeInto2Cmd(flags))
	cmd.AddCommand(newUsersMissingSubmissionsCmd(flags))
	cmd.AddCommand(newUsersPandataEventsTokenCmd(flags))
	cmd.AddCommand(newUsersPollBatchQueryCmd(flags))
	cmd.AddCommand(newUsersPollQueryCmd(flags))
	cmd.AddCommand(newUsersProfilePicsCmd(flags))
	cmd.AddCommand(newUsersQueryCmd(flags))
	cmd.AddCommand(newUsersQueryResultsCmd(flags))
	cmd.AddCommand(newUsersSetCustomColorCmd(flags))
	cmd.AddCommand(newUsersSetDashboardPositionsCmd(flags))
	cmd.AddCommand(newUsersSetDataCmd(flags))
	cmd.AddCommand(newUsersSetFilesUiVersionPreferenceCmd(flags))
	cmd.AddCommand(newUsersSetTextEditorPreferenceCmd(flags))
	cmd.AddCommand(newUsersSettingsCmd(flags))
	cmd.AddCommand(newUsersSettings2Cmd(flags))
	cmd.AddCommand(newUsersSettings3Cmd(flags))
	cmd.AddCommand(newUsersShowCmd(flags))
	cmd.AddCommand(newUsersSplitCmd(flags))
	cmd.AddCommand(newUsersTerminateSessionsCmd(flags))
	cmd.AddCommand(newUsersTodoItemCountCmd(flags))
	cmd.AddCommand(newUsersTodoItemsCmd(flags))
	cmd.AddCommand(newUsersUpcomingEventsCmd(flags))
	cmd.AddCommand(newUsersUpdateCmd(flags))
	cmd.AddCommand(newUsersUpdate2Cmd(flags))
	cmd.AddCommand(newUsersUserGradedSubmissionsCmd(flags))
	return cmd
}
