// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strconv"

	"github.com/spf13/cobra"
)

func newUsersCreateSelfRegisteredUserCmd(flags *rootFlags) *cobra.Command {
	var bodyUserName string
	var bodyUserShortName string
	var bodyUserSortableName string
	var bodyUserTimeZone string
	var bodyUserLocale string
	var bodyUserTermsOfUse string
	var bodyPseudonymUniqueId string
	var bodyCommunicationChannelType string
	var bodyCommunicationChannelAddress string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-self-registered-user <account_id>",
		Short:       "[DEPRECATED] Self register a user",
		Example:     "  canvas-pp-cli users create-self-registered-user 550e8400-e29b-41d4-a716-446655440000 --user-name example-resource",
		Annotations: map[string]string{"pp:endpoint": "users.create_self_registered_user", "pp:method": "POST", "pp:path": "/api/v1/accounts/{account_id}/self_registration"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("user-name") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "user-name")
				}
				if !cmd.Flags().Changed("user-terms-of-use") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "user-terms-of-use")
				}
				if !cmd.Flags().Changed("pseudonym-unique-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "pseudonym-unique-id")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/v1/accounts/{account_id}/self_registration"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("account_id is required\nUsage: %s <%s>", cmd.CommandPath(), "account_id"))
			}
			path = replacePathParam(path, "account_id", args[0])
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyUserName != "" {
					body["user[name]"] = bodyUserName
				}
				if bodyUserShortName != "" {
					body["user[short_name]"] = bodyUserShortName
				}
				if bodyUserSortableName != "" {
					body["user[sortable_name]"] = bodyUserSortableName
				}
				if bodyUserTimeZone != "" {
					body["user[time_zone]"] = bodyUserTimeZone
				}
				if bodyUserLocale != "" {
					body["user[locale]"] = bodyUserLocale
				}
				if bodyUserTermsOfUse != "" {
					parsedUserTermsOfUse, err := strconv.ParseBool(bodyUserTermsOfUse)
					if err != nil {
						return fmt.Errorf("parsing --user-terms-of-use as bool: %w", err)
					}
					body["user[terms_of_use]"] = parsedUserTermsOfUse
				}
				if bodyPseudonymUniqueId != "" {
					body["pseudonym[unique_id]"] = bodyPseudonymUniqueId
				}
				if bodyCommunicationChannelType != "" {
					body["communication_channel[type]"] = bodyCommunicationChannelType
				}
				if bodyCommunicationChannelAddress != "" {
					body["communication_channel[address]"] = bodyCommunicationChannelAddress
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "users", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "users", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "users",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "users", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyUserName, "user-name", "", "The full name of the user. This name will be used by teacher for grading.")
	cmd.Flags().StringVar(&bodyUserShortName, "user-short-name", "", "User's name as it will be displayed in discussions, messages, and comments.")
	cmd.Flags().StringVar(&bodyUserSortableName, "user-sortable-name", "", "User's name as used to sort alphabetically in lists.")
	cmd.Flags().StringVar(&bodyUserTimeZone, "user-time-zone", "", "The time zone for the user. Allowed time zones are IANA time zones or friendlier Ruby on Rails time zones.")
	cmd.Flags().StringVar(&bodyUserLocale, "user-locale", "", "The user's preferred language, from the list of languages Canvas supports. This is in RFC-5646 format.")
	cmd.Flags().StringVar(&bodyUserTermsOfUse, "user-terms-of-use", "", "Whether the user accepts the terms of use.")
	cmd.Flags().StringVar(&bodyPseudonymUniqueId, "pseudonym-unique-id", "", "User's login ID. Must be a valid email address.")
	cmd.Flags().StringVar(&bodyCommunicationChannelType, "communication-channel-type", "", "The communication channel type, e.g. 'email' or 'sms'.")
	cmd.Flags().StringVar(&bodyCommunicationChannelAddress, "communication-channel-address", "", "The communication channel address, e.g. the user's email address.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
