// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"runtime/debug"
	"strings"

	"github.com/spf13/cobra"
)

// version is the printed CLI's version, overridable at build time via ldflags.
var version = "1.0.0"

// defaultVersion mirrors the literal above. `-X` only overwrites a string var
// with a constant initializer, so version keeps one; comparing against this
// copy is how resolveVersion tells a stamped build from an unstamped one.
const defaultVersion = "1.0.0"

// init promotes the resolved version into version so every consumer -- the
// version command, rootCmd.Version, doctor, agent-context -- reports one string.
func init() { version = resolveVersion() }

// resolveVersion prefers the ldflags stamp used by goreleaser releases, then
// falls back to the module version the toolchain records in the binary.
// `go install <module>@vX.Y.Z` sets only the latter.
func resolveVersion() string { return pickVersion(version, moduleVersion()) }

// pickVersion returns stamped when ldflags overrode the compiled-in default,
// otherwise the module version, otherwise the default. Split out from
// resolveVersion so the rule is testable without producing a real build.
func pickVersion(stamped, module string) string {
	if stamped != defaultVersion {
		return stamped
	}
	if v := strings.TrimPrefix(module, "v"); v != "" && v != "(devel)" {
		return v
	}
	return stamped
}

// moduleVersion reports the version the toolchain recorded in this binary,
// empty when it was not built from a module the toolchain could version.
func moduleVersion() string {
	if bi, ok := debug.ReadBuildInfo(); ok {
		return bi.Main.Version
	}
	return ""
}

// newVersionCmd prints the CLI name and version. Shared by the HTTP and device
// generators so both printed-CLI shapes carry an identical version command.
func newVersionCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("%s %s\n", cmd.Root().Name(), version)
		},
	}
}
